### ISSUE TITLE
permute_axes without swapping memory::tag (convolution -> matmul)

### ISSUE THREAD

**Issue by rosspleban** [oneapi-src/oneDNN#1011]
Is there a way to permute_axes without changing the underlying tag?

My understanding is permute_axes() will swap the logical dimensions and also swap the tag (dimension meaning).  From dnnl.hpp comments:
```
dnnl::memory::desc in_md(
        {2, 3}, data_type, memory::format_tag::ab);
dnnl::memory::desc expect_out_md(
        {3, 2}, data_type, memory::format_tag::ba);

assert(in_md.permute_axes(permutation) == expect_out_md);
```

I would like the output of the above snippet `expect_out_md` to be {3,2} tag:ab.

This situation arrises from a convolution followed by a matmul.  I want the matmul input_features to be 48 (oneDNN doc calls this k).

```
        convolution
            |
            | [1, 48, 1, 75] nchw
            |
      permute_axes({0, 3, 2, 1})
            |
            | [1, 75, 1, 48] nwhc
            |
        reshape({1, 75, 48})
            |
            | [1, 75, 48]    abc
            |
          matmul 
            |
            | [1, 75, 32]    abc

```

Note: I'm using master v2.2.0 (commit 98ec1546654afd51d056da068afb706e51d4b758)

**Comment by igorsafo** [comment]
Hi @rosspleban ,
oneDNN memory descriptor consists of logical and physical parts. For example, matmul operation expects matrix A to have dimensions {M, K} in that particular order. This is logical representation ad it is defined by `dims`. Physically matrix A can be stored in many ways, for example it can be stored as a 2D array {M, K} with strides {K, 1} or it can be stored as a 3D array {M / 8, K, 8} with strides {8*K, 8, 1}. This information is defined by `format_desc`. These 2 parts are connected with each other. If you permute logical dimensions, they also should be adjusted in `format_desc`.
The methods `permute_axes` and 'reshape' reinterpret memory descriptor, but they do not modify actual values inside memory. To reorder memory between logically the same memory but with different physically representations reorder primitive should be used. For example:
```
        convolution
            |
            | [1, 48, 1, 75] nchw
            |
      permute_axes({0, 3, 2, 1})
            |
            | [1, 75, 1, 48] nwhc
            |
        reshape({1, 75, 48})
            |
            | [1, 75, 48]    acb
            |
        reorder({{1, 75, 48}, acb}, {{1, 75, 48}, abc})
            |
            | [1, 75, 48]    abc
            |
          matmul 
            |
            | [1, 75, 32]    abc
```

Another option would be to compute convolution with `nhwc` tag for src and dst. In this case channels will be the innermost dimension in convolution destination and adding `permute_axis` and `reshape` will be enough:
```
        convolution
            |
            | [1, 48, 1, 75] nhwc
            |
      permute_axes({0, 3, 2, 1})
            |
            | [1, 75, 1, 48] nchw
            |
        reshape({1, 75, 48})
            |
            | [1, 75, 48]    abc
            |
          matmul 
            |
            | [1, 75, 32]    abc
```

However I wouldn't recommend forcing convolution or matmul primitives to work with some particular format tag because its performance will be sub-optimal and usually these primitives are the biggest ones in terms of time spent across a model. The main rule is to create convolution and matmul primitives with format tag `any` for all memory descriptors if possible and then handle reorders if they are required.

[An example with reorder primitive](https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/reorder.cpp) 

Regards,
Igor Safonov
