### ISSUE TITLE
didn't understand the function adjust_thread_count

### ISSUE THREAD

**Issue by Daniel-NJ** [oneapi-src/oneDNN#1015]
sgemm_threading_driver use a function call adjust_thread_count, I did't understand  what these condition means,
if (omp_cycles * i < gemm_cycles * (i - 1)) break ,thanks!

```
`template <typename T>
static inline void adjust_thread_count(dim_t m, dim_t n, dim_t k, int *nthrs) {
    double gemm_cycles = m * n * k / fp_per_cycle;
    gemm_cycles *= is_f32 ? 2.0 : 8.0;

    int i = *nthrs;

    // Use a different model for omp overheads if nthrs is <= 4
    if (*nthrs <= 4 && omp_overhead_small_core > 0) {
        double omp_cycles = omp_overhead_small_core;
        if (gemm_cycles < omp_cycles) {
            *nthrs = 1;
            return;
        } else {
            while (i > 1) {
                if (omp_cycles * i < gemm_cycles * (i - 1)) break;
                --i;
            }
        }
    } else {
        if (gemm_cycles < (omp_intercept_big_core + 2 * omp_slope_big_core)) {
            *nthrs = 1;
            return;
        }

        // adaptive decrement to march faster·
        while (i > 1) {
            double omp_cycles = omp_intercept_big_core + i * omp_slope_big_core;
            if (omp_cycles * i < gemm_cycles * (i - 1)) break;//didn't understand these condition means?

            if (i < 10)
                i -= 2;
            else if (i < 30)
                i -= 4;
            else
                i -= 8;
        }
    }

    if (i < 1) i = 1;

    *nthrs = i;
}`
```

**Comment by dzarukin** [comment]
Hi @Daniel-NJ, thank you for the question.

@aaraujom, could you help with an answer, please?

**Comment by aaraujom** [comment]
Hi @Daniel-NJ - Spawning threads has a cost that can be significant if problem size is small. We try to adjust (reduce) the number of threads used to minimize the overhead using a simple model. The model is not perfect and can probably be improved.

This is beyond my time and I can only guess what original contributor was thinking. Probably `omp_intercept_big_core` and `omp_slope_big_core` were chosen based on benchmark data. The model for the overhead is probably `omp_cycles` scaled by `i / (i - 1)`. This way, if this model for thread spawn overhead, `(omp_intercept_big_core + i * omp_slope_big_core) * i / (i - 1)`, is less than the time to compute then we use `i` as the number of threads, otherwise we try to reduce number threads and check if overhead is small.

**Comment by Daniel-NJ** [comment]
@aaraujom thanks very much for you feedback，your explaining seems reasonable.

**Comment by aaraujom** [comment]
@Daniel-NJ Good to know. Feel free to ask further questions related here or close the issue.
