### ISSUE TITLE
Acceptable error tolerance of benchdnn eltwise

### ISSUE THREAD

**Issue by kawakami-k** [oneapi-src/oneDNN#1021]
In the benchdnn, 4e-5 is set as the the acceptable error tolerance for the alg_t::TANH of eltwise. 
https://github.com/oneapi-src/oneDNN/blob/090d3eb9193fe5125f198ebf8872f36400827331/tests/benchdnn/eltwise/eltwise.cpp#L181

We would like to increase this value to about 2e-4 in the case of AArch64. Is there a problem with this change? The Arm SVE instruction set has FRECPE and FRECPS instructions, which can calculate second-order approximate values efficiently. If the acceptable error tolerance is relaxed, the JIT implementation of TANH becomes much simpler, https://github.com/fujitsu/oneDNN/commit/0c4aae1a6fd091fb8e00947edc0d03b4ff96a548 

Thanks!

**Comment by alenik01** [comment]
>We would like to increase this value to about 2e-4 in the case of AArch64.

I also support this proposal, the problem with `e-5` relative tolerance is that it may be too strict, some implementations of `tanh` may have a "spike" in tolerance near 0.

**Comment by mgouicem** [comment]
In all generality, I agree that such accuracy level is unnecessary for DNN workloads (since most workloads seem to tolerate using things like bf16 and fp16).  However, in this particular case, we had a few issues with customers complaining about inaccuracies when cancellation happens (e.g tanh_bwd = 1 - tanh^2(x), or LSTM where we could have situation where we compute 1 - tanh(x)).

So far, we just tried to get a level of accuracy similar to glibc, so that customers switching from reference implementations to oneDNN would likely not see any accuracy issue.
If we are to switch the accuracy checking here, I would prefer we move to something like [numpy.isclose](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html), instead of reducing this threshold. This would allow to ignore errors for tiny numbers but keep reasonable relative error for "large" values (as mentioned by @alenik01 ). @kawakami-k , would it be fine in your case?

**Comment by kawakami-k** [comment]
HI, @mgouicem.
Thank you for the comment. I see that there are cases where the same accuracy as glibc is required.
