### ISSUE TITLE
dnnl gemm u8s8s32 performance

### ISSUE THREAD

**Issue by affranchi** [oneapi-src/oneDNN#1040]
Hello,

I'm testing dnnl::gemm_u8s8s32 and notice that there is some unexpected gap between some sizes.
I tested:

Test1
A: 1x1024 uint8_t / B: 4096x1024 int8_t (transposed) / Out: 1x4096 int32_t
Test2
A: 2x1024 uint8_t / B: 4096x1024 int8_t (transposed) / Out: 2x4096 int32_t
Test3
A: 4x1024 uint8_t / B: 4096x1024 int8_t (transposed) / Out: 4x4096 int32_t

And the result is:
in AWS M5, oneDNN SEQ mode (no thread), version 2.2.1

Test1: 180us
Test2: 576us
Test3: 658us

I'm wondering why it's having larger gap between Test1 and Test2 compared with the gap between Test2 and Test3.
Also, Test1 is actually in the expected range but Test2/Test3 is outside of the range. FYI, I ran gemm with the same size just before each Test for warming up. Do I miss some trick to improve the performance of the gemm? And do you have any plan to improve this gemm(u8s8s32/s8s8s32) performance?

FYI, I tested with MatMul and got worse performance in Test2 case:
```
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_u8::blocked:ab:f0 wei_s8::blocked:ba:f0 dst_s32::blocked:ab:f0,,,2x1024:1024x4096:2x4096,0.723877
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_u8::blocked:ab:f0 wei_s8::blocked:ba:f0 dst_s32::blocked:ab:f0,,,2x1024:1024x4096:2x4096,0.723877
```

Test codes are below:

```
    //Test1
    dnnl::memory::desc src_desc({1,1024},data_type::u8,{1024,1});
    dnnl::memory::desc weight_desc({4096,1024},data_type::s8,{1024,1});
    dnnl::memory::desc dst_desc({1,4096},data_type::s32,{4096,1});

    //Test2
    dnnl::memory::desc src_desc_2({2,1024},data_type::u8,{1024,1});
    dnnl::memory::desc weight_desc_2({4096,1024},data_type::s8,{1024,1});
    dnnl::memory::desc dst_desc_2({2,4096},data_type::s32,{4096,1});

    //Test3
    dnnl::memory::desc src_desc_4({4,1024},data_type::u8,{1024,1});
    dnnl::memory::desc weight_desc_4({4096,1024},data_type::s8,{1024,1});
    dnnl::memory::desc dst_desc_4({4,4096},data_type::s32,{4096,1});
...
..

    // Run warm-up gemms before Test1/Test2/Test3

    // Test1
    dnnl::gemm_u8s8s32('n','t','F',1,4096,1024, 1,
                       src_data,
                       1024, 0,
                       weight_data,
                       1024, 0, 0,
                       dst_data,
                       4096, &co);
 
    // Test2
    dnnl::gemm_u8s8s32('n','t','F',2,4096,1024, 1,
                       src_data_2,
                       1024, 0,
                       weight_data_2,
                       1024, 0, 0,
                       dst_data_2,
                       4096, &co);
   
    // Test3
    dnnl::gemm_u8s8s32('n','t','F',4,4096,1024, 1,
                       src_data_4,
                       1024, 0,
                       weight_data_4,
                       1024, 0, 0,
                       dst_data_4,
                       4096, &co);
```

Thanks!

**Comment by igorsafo** [comment]
Hi @affranchi , Thank you for your report.
I believe this is because the case 1x1024 is a typical case used in DNNs (fully connected where batch is 1, input channels are 1024) and it was spotted and optimized, while other cases were not. Could you please clarify whether this case is used in some model and important for you or it is just a random test case?

Casting @aaraujom for more details on gemm implementation.

Regards,
Igor Safonov

**Comment by affranchi** [comment]
@igorsafo Thank you for your quick response. Currently, most cases are batch size 1 so it's OK. But we are trying to show that oneDNN could support multiple batches better, too. It would be great if we can show that for 5 batches or something.

I have follow-up question. The current implementation is optimized with all batch 1 size or just for 1024 input channel size? I tried 1x2048 / 8192x2048 / 1x8192 and it took 1.5ms. Is it also because this size is not optimized yet? I'm trying to test bigger sizes.

**Comment by aaraujom** [comment]
> The current implementation is optimized with all batch 1 size or just for 1024 input channel size? I tried 1x2048 / 8192x2048 / 1x8192 and it took 1.5ms. Is it also because this size is not optimized yet?

There are 2 cases:
* _case 1_ : A = 1x1024 | B = 4096x1024 | C = 1x4096: M = 1, N = 4096, K = 1024 : Ops =  8388608 -> 180us ->  180us
* _case 2_ : A = 1x2048 | B = 8192x2048 | C = 1x8192: M = 1, N = 8192, K = 2048 : Ops = 33554432 -> 1.5ms -> 1500us

On _case 2_ there is **4x more computations** to be done, so it should take at least **4x the time** of _case 1_. The **performance gap** for _case 2_ vs _case 1 (scaled)_ is about 1500us / 720us = **2x slower**.

When `m = 1`, we take an algorithm that access original data directly, therefore it will be more sensible to the matrices leading dimension. **Large powers of 2** reduces the total amount of addressable cache, consequentially **performance will be lower**. Try to avoid having large powers of 2 as leading dimensions.

With that said, I tested your cases on a Cascade Lake machine with Intel DL Boost, where VNNI instructions are available. It seems you are interested in using B transpose, so I used `--wtag=ba` in `benchdnn`. 

### Case 1 (with `--wtag=ba`):
```
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_u8::blocked:ab:f0 wei_s8::blocked:ba:f0 dst_s32::blocked:ab:f0,,,1x1024:1024x4096:1x4096,0.115967
perf,cpu,gemm:jit,,--matmul --cfg=u8s8s32 --wtag=ba 1x1024:1024x4096:1x4096,0.00838861,0,0.163086,51.4367,0.179781,46.6601
```

### Case 2 (with `--wtag=ba`):
```
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_u8::blocked:ab:f0 wei_s8::blocked:ba:f0 dst_s32::blocked:ab:f0,,,1x2048:2048x8192:1x8192,0.4021
perf,cpu,gemm:jit,,--matmul --cfg=u8s8s32 --wtag=ba 1x2048:2048x8192:1x8192,0.0335544,0,0.65625,51.1306,0.659544,50.8752
```

**Time roughly increased by 4x as expected**. For reference, I'm also including the timings for the case without using `--wtag=ba` in `benchdnn` below. Time also was roughly increased by 4x. Perhaps you compared timings for B non-transposed case against B transposed case?

### Case 1 (without `--wtag=ba`):
```
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_u8::blocked:ab:f0 wei_s8::blocked:ab:f0 dst_s32::blocked:ab:f0,,,1x1024:1024x4096:1x4096,0.406982
perf,cpu,gemm:jit,,--matmul --cfg=u8s8s32 1x1024:1024x4096:1x4096,0.00838861,0,0.483398,17.3534,0.500249,16.7689
```

### Case 2 (without `--wtag=ba`):
```
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_u8::blocked:ab:f0 wei_s8::blocked:ab:f0 dst_s32::blocked:ab:f0,,,1x2048:2048x8192:1x8192,1.82788
perf,cpu,gemm:jit,,--matmul --cfg=u8s8s32 1x2048:2048x8192:1x8192,0.0335544,0,1.84863,18.1509,1.8712,17.932
```

> I'm wondering why it's having larger gap between Test1 and Test2 compared with the gap between Test2 and Test3.

If `m != 1`, we use an algorithm that copies the data to (internal) temporary buffers. We need to perform copy operation such that the data is in vnni layout. This copy overhead can't be avoided when using integer gemm API (`gemm_u8s8s32`). Such overhead is more expensive for smaller problem sizes (such as `m <= 5` that you are interested). This is probably the reason you see a bigger jump in performance when `m` changes from 1 (test 1) to 2 (test 2) instead of when `m` changes from 2 (test 2) to 4 (test 3).

> FYI, I tested with MatMul and got worse performance in Test2 case:

I'm not sure why `matmul` is performing slower. Perhaps the difference comes from using different benchmarks (verbose output vs `benchdnn` vs your benchmark). From the verbose output you included, it seems `matmul` is relying on integer `gemm` implementation. As I explained above, could you double check if you are comparing times using the same transpose parameters for B matrix?

> Do I miss some trick to improve the performance of the gemm? And do you have any plan to improve this gemm(u8s8s32/s8s8s32) performance?

As far as I know, `matmul` will rely on `brgemm` internal implementation in a not so distant future. @igorsafo  and @akharito  can probably give a better status on that. The advantage of using `matmul` based on `brgemm` implementation is that weights might be prepacked, avoiding copy overhead. This improves overall performance, besides `brgemm` being more performance friendly if you need to apply postops.

**Comment by affranchi** [comment]
Thank you for all detailed answer, @aaraujom .

FYI, in my environment with same stride without verbose option, it's always slow. I'll post the question regarding this with codes if it's not expected behavior.

One follow up question is that, then, do you recommend to do 1x1024 / 1024*4096 twice (for each row of the source) instead of doing 2x1024 / 1024*4096 gemm?

Once again, thank you for your all detailed information.

**Comment by aaraujom** [comment]
> FYI, in my environment with same stride without verbose option, it's always slow. I'll post the question regarding this with codes if it's not expected behavior.

I'm not sure which case you are referring to. Are you referring to Test 2 in your original question, comparing `matmul` vs `dnnl_gemm_u8s8s32`? If yes can you show the verbose output for those cases. I need to check if underneath gemm implementation is using same transpose parameters.

> One follow up question is that, then, do you recommend to do 1x1024 / 10244096 twice (for each row of the source) instead of doing 2x1024 / 10244096 gemm?

Looping over `m = 1` case might provide some performance improvements if `m` is small. So yes you can try that approach and tweak threshold to when to call which. Nevertheless, prepacking ahead once will probably provide more benefits.
