### ISSUE TITLE
How to select xb and yb blocking parameters in FP32 winograd code

### ISSUE THREAD

**Issue by llxingkongxia** [oneapi-src/oneDNN#1055]
In file jit_avx512_core_f32_wino_conv_2x3.cpp([code](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_2x3.cpp#L672-L762))  select xb and yb blocking size dynamically according to the gemm dimension.
The effect factor is the sum of memory, thread, workload, and register, but what is the relationship between them?
```C++
float outer_eff = thr_eff + work_eff + reg_eff + mem_eff;
...
float inner_eff = thr_eff + work_eff + mem_eff + par_eff;
```
For example, in lambda find_m_n2_blocks()
```C++
cur_reg_eff = ((float)in2 * im)/(im + in2) / 2.5f,  
```
I don't understand why is 2.5, not 1.5 or  some other value. 
If this parameter is set small or big, it may be affected outer_eff. 
In the same way,
mem_eff:  */2.f and */3.f
```C++
    if (req_mem > L2_capacity / 2) {
           if (req_mem > ((L2_capacity + L3_cap_per_core) * 4) / 7)
               mem_eff /= (n2_b + 1) / 2.f;
           else
               mem_eff /= (n2_b + 1) / 3.f;
    }
```
par_eff:  1 / (2.f * nblocks);
```C++
  par_eff = 1 / (2.f * nblocks);
```
Please help. Thank you very much.

**Comment by kwiersch** [comment]
Hi @llxingkongxia, thanks for your question. As far as I understand, these parameters are chosen empirically based on performance tuning on real hardware. For the case of `cur_reg_eff`, I think the factor of `2.5f` might have been chosen to normalize the efficiency between `0.f` and `1.f`, as in theory the best available register blocking is `in2=4, im=6` which has `6 * 4 / (6 + 4) = 2.4`. But I agree it's not easy to guess what they mean -- that's partly why in the oneDNN [coding standard](https://github.com/oneapi-src/oneDNN/blob/master/CODING_STANDARDS.md) it is mentioned that properly named constants should be used (but we didn't always follow this rule so well).

Tagging @ankalinin in case he has any insight to share.

**Comment by llxingkongxia** [comment]
Hi @kwiersch , Thanks for responding so quickly.  as you said, let in2=x, im=y, xy + x <= 30 and find the maximum value of xy/(x+y) and then the value of x and y,  so x=5 y=5 , the max factor is 2.5, so all valid cur_reg_eff are between 0.f and 1.f.
And so on, if it's an AVX2 instruction set, xy + y <= 15 and gets the maximum factor , which is about 1.72, the formula should be
```C++
float cur_reg_eff = ((float)in2 * im) / (im + in2) / 1.72f;
```
However, I still have a question about the formula. the maximum utilization of registers should be (in2 * im)/(1+ in2), because only one zmm [(vreg_src)](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_2x3.cpp#L401) is used in the gemm kernel process. I don't know if my idea is correct, thank you.

**Comment by kwiersch** [comment]
Hi @llxingkongxia, thanks for correction! Yes, the 5x5 blocking is better in theory, and since its efficiency becomes exactly `1.f`, I am now convinced that's what the value `2.5f` represents.

About the formula: I think it uses `im + in2` instead of `1 + in2` because the denominator represents the memory access part of the blocking scheme. So even if `m` dimension uses only `1` register, there are still `m` memory accesses per block.

**Comment by llxingkongxia** [comment]
Hi @kwiersch  I understand, thanks. 
The last question, would you please explain the meaning of "req_mem > ((L2_capacity + L3_cap_per_core) * 4) / 7) " and "mem_eff /= (n2_b + 1) / 2.f".  thanks
```C++
    req_mem = (((float)ix + 2) * (iy + 2) + aa * M) * Z + aa * Y;
    if (req_mem > L2_capacity / 2) {
           if (req_mem > ((L2_capacity + L3_cap_per_core) * 4) / 7)
               mem_eff /= (n2_b + 1) / 2.f;
           else
               mem_eff /= (n2_b + 1) / 3.f;
    }
```

**Comment by kwiersch** [comment]
Hi @llxingkongxia. Sorry, but I am not so sure that I understand it myself. The general idea is that we want to add some penalty for blocking configurations that do not fit into L2 and/or L3 cache. As to why this should depend on `n2_b` (which is related to register blocking, not cache blocking), my best guess is that we want to slightly prefer register blockings with smaller `n2_b` (and by extension larger `m` due to the effect of the register efficiency heuristic). If you take a look at the compute kernel ([here](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_2x3.cpp#L448)), you will see that for "outer threading" strategy (ie `jcp.small_mb = false`) we loop over full `N` dimension of weights by chunks of size `jcp.n2_block * jcp.oc_block`. So maybe by taking smaller `N` chunks in cases where src + weights does not fit into cache, we have a better chance of src still fitting into cache (since chunk of weights will be smaller). But it's just a guess...

**Comment by llxingkongxia** [comment]
close it, thanks!
