### ISSUE TITLE
Which extension of SIMD instruction set will be use in my example?

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1078]
Hi, 
I'm running one of this library examples and found that the library enters the "jit_avx2_convolution_fwd_t::execute_forward" function while I know that my CPU does not support AVX2 (it supports just AVX). Is it up to me to control which extension of SIMD instruction sets it should use or not? If yes how could I config it to use desired instructions?

**Comment by densamoilov** [comment]
Hi @kokhazade, oneDNN has a mechanism that identifies available ISA in the system. Based on the identified ISA oneDNN selects an implementation of the requested primitive.

Some implementations may not use AVX2 specific instructions and they will work fine one either AVX or AVX2 systems.

oneDNN provides a way to control the mechanism, please see the [documentation](https://oneapi-src.github.io/oneDNN/dev_guide_cpu_dispatcher_control.html).

**Comment by vpirogov** [comment]
I believe the system has Intel AVX2 support, as oneDNN relies on CPUID information to detect instructions. If this implementation was dispatched on a processor without Intel AVX2 support the example would crash with illegal instruction message.

**Comment by kwiersch** [comment]
Actually, in this case I would not be surprised if the CPU really does only have AVX support. The reason is that AVX support was grafted onto the AVX2 implementation (there is relatively little difference between AVX and AVX2 when it comes to f32 computations).

@kokhazade If you are interested, you can see the main difference between AVX and AVX2 versions of the "AVX2" convolution implementation in this file: [src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L726](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L726). Probably we should rename the related files and classes to make it clear it is a duel AVX/AVX2 kernel, or at least update the implementation string to properly report `jit:avx` on AVX machines and `jit:avx2` on AVX2 machines. Sorry for the confusion!

**Comment by vpirogov** [comment]
Thanks, @kwiersch. It did not occur to me that the implementation may be mislabeled.

**Comment by vpirogov** [comment]
Thanks to @kwiersch the implementation name is fixed in fa69637a967fc80ef2f0ee666c218700af39524e.
