### ISSUE TITLE
How to access the kernel_ code?

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1079]
Hi,
Two questions:
1- Which kind of convolution methods the library supports for convolution layers? As I know it supports **Direct** and **Winograd** methods for convolution. Am I right or there is something more?

2- I want to debug the code (application + library) on eclipse IDE and see the way you have implemented the convolution method. After following some steps I reached to `jit_avx2_convolution_fwd_t::execute_forward(const exec_ctx_t &ctx)`. As I have found, it dispatches calculations to some threads and in each thread calculates some parameters and passes these parameters to a kernel function (`kernel_` function pointer) via command bellow to do the main algorithm of convolution. 

> (*kernel_)(&par_conv);

As I found, the content of this `kernel_` function will be produced and compiled at run time. I want to know how to access the content of this function. Is there any file to look for (Does it write the produced code into any file)? Or any debug method to get into `kernel_` function?
Where does the `kernel_` function pointer is being set to the proper function of convolution (in this case convolution)?

**Comment by kwiersch** [comment]
Hi @kokhazade,

1. Yes, that's correct. There is also `dnnl::algorithm::convolution_auto` that dispatches to Winograd for cases where it's likely to improve performance, and to direct convolution otherwise.
2. The easiest way to view the JIT kernels is by dumping the binary code as described in the documentation: [Inspecting JIT Code](https://oneapi-src.github.io/oneDNN/dev_guide_inspecting_jit.html). You can also try stepping into the kernel and viewing the assembly -- for example, with gdb you can use `x /10i $pc` to view the next 10 assembly instructions.

**Comment by kokhazade** [comment]
Thank you @kwiersch.
I followed the link and found the assembly instructions. But I guess I made mistake in asking what I want. I just want to get into the C++ code of convolution. Is that inside `kernel_` function pointer? If so, is there any function or class constructor that initializes the `kernel_` function pointer to the proper convolution function pointer? If not, where is the main process of convolution and how it is being introduced to my primitive object?
Shortly: I studied [this link](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html) that describes convolution method. But I want to find the C++ implementations of direct and winograd convolution in your library.

**Comment by kwiersch** [comment]
Hi @kokhazade,

In general, the convolution code is split into a driver and a kernel. The driver handles things like threading and thread balancing, while the main compute-intensive portion of the convolution is inside the kernel.

For optimized convolution implementations, oneDNN uses JIT (or just-in-time) compiled kernels. These are not C++ kernels, but binary code generated with assembly-like instructions via the [xbyak](https://github.com/herumi/xbyak) library. This allows for optimizations (such as register unrolling) that are tailored to a specific convolution. During the oneDNN primitive creation step, the binary code is generated and the kernel function pointer is assigned to it. Then during execution, the same generated kernel can be used over and over again (for a given convolution shape, that is).

If you just want to understand exactly how convolution is calculated, you can look at our reference implementation: [src/cpu/ref_convolution.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_convolution.cpp). If you want to understand the optimized code, the driver and kernel are in separate files:
- driver: [src/cpu/x64/jit_avx2_convolution.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx2_convolution.cpp)
- kernel: [src/cpu/x64/jit_avx2_conv_kernel_f32.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp)

For Winograd, there is only optimized version in oneDNN:
- driver: [src/cpu/x64/jit_avx512_common_convolution_winograd.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx512_common_convolution_winograd.cpp)
- kernel: [src/cpu/x64/jit_avx512_common_conv_winograd_kernel_f32.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx512_common_conv_winograd_kernel_f32.cpp)

However, there is a reference implementation in our benchmarking tool, benchdnn: [tests/benchdnn/conv/ref_wino.cpp](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/conv/ref_wino.cpp).

**Comment by kokhazade** [comment]
Thank you @kwiersch for the complete answer.
My goal is to find a C kernel and replace it with my-own kernel code to test it. Is there anyway to force my application to use your [reference implementation](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_convolution.cpp) instead of jit kernels? I mean `ref_convolution_fwd_t<src_type, wei_type, dst_type, acc_type>::execute_forward`. 
If not, how can I import my kernel to your library?

**Comment by kwiersch** [comment]
Hi @kokhazade,

Generally the first suitable candidate from a ranked list of implementations is chosen. So if you want to force the reference implementation, you can edit https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/cpu_convolution_list.cpp so that it is the 1st implementation in each list instead of the last (either by commenting out the other implementations or by moving it to the 1st position).

Another way to choose the reference implementation is to check the implementation string via [dnnl::primitive_desc_base::impl_info_str()](https://oneapi-src.github.io/oneDNN/structdnnl_1_1primitive__desc__base.html#a28661bd29607c71ecb8602d6c98adbc5) and use [dnnl::primitive_desc::next_impl()](https://oneapi-src.github.io/oneDNN/structdnnl_1_1primitive__desc.html#a841df469ca54c3de2d233e46f48322b2) to get the next suitable candidate until it matches "ref". Note that this way requires changes to your application.

If you want to create your own kernel, you can use the reference kernel as an example of what needs to be included, then add your new kernel to the implementation list and use one of the two methods mentioned above to have it chosen by your application.
