### ISSUE TITLE
Does oneDNN support AMD GPU

### ISSUE THREAD

**Issue by zhangqiang-hf** [oneapi-src/oneDNN#1084]
Dear sirs,
  From the readme, I learned that oneDNN can be executed on GPU :
The library is optimized for the following GPUs:

    Intel HD Graphics
    Intel UHD Graphics
    Intel Iris Plus Graphics
    Xe architecture-based Graphics (code named DG1 and Tiger Lake)

I want to execute on AMD GPU. Does it support AMD GPU?

Thank you!

**Comment by igorsafo** [comment]
Hello @zhangqiang-hf ,
oneDNN doesn't support AMD GPUs: [here is the check](https://github.com/oneapi-src/oneDNN/blob/8715d47411778baaaaf1472092fe80e88b6a4a32/src/gpu/ocl/ocl_gpu_device_info.cpp#L31)
The reason is the kernels are implemented either on OpenCL using Intel extension to get the best performance or on Intel GPU assembly using nGEN. Both of these approaches require support of Intel-specific instructions, which might not be available on AMD GPU (however I am not familiar with AMD GPUs). Intel GPU support is based on OpenCL and DPCPP runtimes and NVidia GPUs are supported using a special DPCPP with Nvidia GPU support. So to enable AMD GPUs in oneDNN the following criteria should be met:
- Existing oneDNN runtimes support AMD GPUs (OpenCL or DPCPP)
- New kernels targeting AMD GPUs are implemented from scratch or existing OpenCL kernels with Intel extensions are ported to AMD analogues. 

Regards,
Igor Safonov

**Comment by zhangqiang-hf** [comment]
Dear sir,
You mean we can use AMD GPU to execute oneDNN?  with the two critera:
1)Existing oneDNN runtimes support AMD GPUs (OpenCL or DPCPP)-> we can use opencl
2)New kernels targeting AMD GPUs are implemented from scratch or existing OpenCL kernels with Intel extensions are ported to AMD analogues.-> if we can not port Intel extensions to the OpenCL kernels, whether it can be run?  use Opencl kernel without Intel extensions  still ok? Just performance will be missed a little?

**Comment by igorsafo** [comment]
@zhangqiang-hf Yes, correct. Kernels which don't use Intel extensions should work fine but might have suboptimal performance.

**Comment by vpirogov** [comment]
@zhangqiang-hf,

Just wanted to mention that if you plan to get oneDNN running on AMD GPUs we'll be glad to accept these contributions.
