### ISSUE TITLE
Build failed with CMake 3.20+ & DPCPP  

### ISSUE THREAD

**Issue by KimBioInfoStudio** [oneapi-src/oneDNN#1095]
# Summary
According  to https://cmake.org/cmake/help/v3.20/release/3.20.html 
and  https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5594

when build oneDNN with uisng dpcpp & CMake >3.20 https://github.com/oneapi-src/oneDNN/blob/master/cmake/SYCL.cmake#L33 will fail like
```
CMake Error at third_party/oneDNN/cmake/SYCL.cmake:67 (message):
  IntelLLVM is not Intel oneAPI DPC++ Compiler
```

**Comment by vpirogov** [comment]
Could you please include CMake command line you are using and the CMake log?

[oneDNN developer guide](https://oneapi-src.github.io/oneDNN/dev_guide_build.html) recommends the following command line for DPC++ builds:
```
export CC=clang
export CXX=clang++
cmake .. \
          -DDNNL_CPU_RUNTIME=DPCPP
          -DDNNL_GPU_RUNTIME=DPCPP
```

**Comment by densamoilov** [comment]
Hi @KimBioInfoStudio, the line in the CMake that you are referring to simply checks whether the compiler specified with `CMAKE_CXX_COMPILER` supports `-fsycl` option, which is required to compile oneDNN with DPCPP runtime. Both, `icx` and `dpcpp` drivers support that option so it looks unexpected that you observe the issue. As Vadim already said we need more information to understand what's going on.

A side note, the new CMake versions (3.20 and newer) doesn't allow to use `clang` and `clang++` oneAPI DPC++ Compiler drivers on Windows because CMake expects the driver to support MSVC-like command line while `clang` and `clang++` support UNIX-like command line. However, the `dpcpp` driver cannot be used either because CMake has an issue with defining proper linker when `dpcpp` driver is used which results in throwing out device code from object files during linking. We are working to solve this problem.

The best solution at this point would be downgrading CMake version to 3.19 or older.

**Comment by KimBioInfoStudio** [comment]
@densamoilov @vpirogov  i find this only when i tried to build ipex-gpu, and  not reproduce when build oneDNN only
