### ISSUE TITLE
Installation on aarch64 platform

### ISSUE THREAD

**Issue by AnonymousYWL** [oneapi-src/oneDNN#1114]
Hello!

‘HWCAP_ATOMICS’ was not declared in this scope. 
The above error occurred during installation.

**Comment by igorsafo** [comment]
Hi @AnonymousYWL , thanks for the question.
Could you please share a log with the error? What oneDNN version did you try to install? What OS do you use?
Casting @kawakami-k since the issue seems to be relevant to HW capabilities detection in [xbyak_aarch64](https://github.com/oneapi-src/oneDNN/blob/b5641adb162900eb6c0f5d01a800c38e79dd91a6/src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_util.h#L25)

**Comment by AnonymousYWL** [comment]
Thank you for your reply

oneDNN-master/src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_util.h:87:17: error: ‘HWCAP_ATOMICS’ was not declared in this scope
     if (hwcap & HWCAP_ATOMICS) {


oneDNN v2.3
Linux version 3.14.57

**Comment by kawakami-k** [comment]
Hi, @AnonymousYWL 
Could you provide me with the following additional information?
- Linux distribution name
- Compiler (GCC?)
- Compiler version

**Comment by AnonymousYWL** [comment]
Can onednn provide backward propagation convolution on armv8 platform (non SVE)?

**Comment by igorsafo** [comment]
Hi @AnonymousYWL , please create a separate issue for each question to not mix up the requests.
Casting @nSircombe and @alenik01 for more details on backward convolution support.

**Comment by alenik01** [comment]
>Casting @nSircombe and @alenik01 for more details on backward convolution support.

Hello to everybody. Firstly, there are several types of backward convolutions. Secondly, we are limited at the moment with the functionality of [Compute Library](https://github.com/ARM-software/ComputeLibrary). I hope this answers the question because no details were provided on "backward propagation convolution" request in the comment above.

**Comment by vpirogov** [comment]
Closing the issue as stale. Feel free to reopen with additional information.
