### ISSUE TITLE
Explain what the precision difference between Mkldnn Gelu and Gelu's erf algorithm implementation

### ISSUE THREAD

**Issue by yanbing-j** [oneapi-src/oneDNN#1122]
### Summary
We found that Mkldnn Gelu implementation and Gelu's original erf algorithm implementation have a precision difference, which is not tolerated by torch::allclose's default tolerance (rtol=1e-05, atol=1e-08). Could you please explicitly explain what the precision difference is?
### Steps to reproduce
- **Input**: x = torch::linspace(-3.0, 3.0, 100);
- **Expected output** (using erf algorithm): y_exp = x * 0.5 * (1.0 + torch::erf(x / std::sqrt(2.0)));
- **Mkldnn output**: y = mkldnn_gelu(x)
- **Output check**: ASSERT_TRUE(torch::allclose(y, y_exp)); This check will fail.

**Comment by igorsafo** [comment]
Hi @yanbing-j ,
Did you try to to use algorithm `dnnl_eltwise_gelu_erf` ?
oneDNN supports 2 algorithms for gelu operation: `dnnl_eltwise_gelu_erf` and `dnnl_eltwise_gelu_tanh`. The `dnnl_eltwise_gelu` is an alias for `dnnl_eltwise_gelu_tanh`. Here is the documentation which explains the difference between these 2 algorithms: https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html 
<html>
<body>


Operation | oneDNN algorithm kind | Forward formula | Backward formula (from src) | Backward formula (from dst)
-- | -- | -- | -- | --
gelu_erf | dnnl_eltwise_gelu_erf | d=0.5s(1+erf[s√2])d=0.5s(1+erf⁡[s2]) | ds=dd⋅(0.5+0.5erf(s√2)+s√2πe−0.5s2)ds=dd⋅(0.5+0.5erf⁡(s2)+s2πe−0.5s2) | –
gelu_tanh | dnnl_eltwise_gelu_tanh | d=0.5s(1+tanh[√2π(s+0.044715s3)])d=0.5s(1+tanh⁡[2π(s+0.044715s3)]) | See (1).See (1). | –


</body>
</html>

Regards,
Igor Safonov

**Comment by yanbing-j** [comment]
Hi @igorsafo ,
Thank you for your response. I am using `dnnl_eltwise_gelu_erf` to replace Gelu's original implementation. And I see you find that PR. https://github.com/pytorch/pytorch/pull/58525/files#diff-6490854d49e89412f60efcbdd2abfcfe1beda17ebe2369425841dbb91c0d516dR37
The test case is from pytorch/test/cpp/api/modules.cpp. It uses gelu erf algorithm as an expected result. Since `y` and `y_exp` are both using gelu erf algorithm, where does the precision difference come from?

**Comment by dzarukin** [comment]
Hi @yanbing-j, let me jump into the conversation. It's most likely that the cases uses optimized implementation which [approximates erf with a set of instructions](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/injectors/jit_uni_eltwise_injector.cpp#L1095). This set may bring precision difference due to implementations of standard math functions may vary from system to system (based on libm implementation or any 3rd party library implementation).

If I understand it right, the test checks absolute difference of values to be 1e-8 or smaller which is incredibly small number for a transcendental function like GeLU. I've run benchdnn test case to see the absolute difference between optimized version and [reference one](https://github.com/oneapi-src/oneDNN/blob/master/src/common/math_utils.hpp#L374) (that calls libm erf). I see for some points the absolute difference on AVX2 platform may reach a magnitude of 2e-7 (in a tested interval of [-3; 3]) which is 20x bigger than expected. And this is normal, and actually very precise result since rtol is of 1e-7 for such points.
Additionally, there are points close to 0 where rtol may be higher than 4e-5. Computations around 0 are likely have cancellation issues and validating those with plain errors is not a good idea. I may make an assumption that this test would reliably tell whether the got result follows the test reference but won't check how "good" got result is.

If you still feel that oneDNN has a correctness issue, please share with us the test case with DNNL_VERBOSE=1 on and input data where the result is not close to expected. Thanks.

**Comment by yanbing-j** [comment]
Hi @dzarukin , thanks for your explanation.
