### ISSUE TITLE
What is the right way to append GELU as post-op to integer inner-product?

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/oneDNN#1123]
Lets say computation is roughly like:
```
x * W -> int32 -> scale1 ->f32 -> gelu -> f32 -> scale2 -> int8
```

Any chance I could do a chain from post-ops? Can both scales be passed in runtime?

**Comment by dzarukin** [comment]
Hi @CaoZhongZ, thank you for questions.

> Any chance I could do a chain from post-ops?

Yes, convolution supports a chain of post-ops. In order to that, you may append more post-ops to primitive attributes. The order of appending would specify the order of execution. More information may be found [here](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html).

> Can both scales be passed in runtime?

There are several possible ways to implement quantization with oneDNN. `scale1` would be an output scale and this part is natively supports run-time values via API. More information may be found [here (Post-ops and Attributes section)](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html).

There are options for `scale2` though. Using `scale` argument of element-wise post-op doesn't provide run-time support, only at creation time when post-op is appended. But there's an option to use binary multiplication post-op with a single value for per_tensor application or num_of_channel values for per_oc application to represent `scale2` value. Since binary post-op requires additional memory argument, this value is only run-time. More information about binary post-op is available under first link.

Then convolution code should down-convert the final value to int8.

Hope it helps. Thanks.

**Comment by CaoZhongZ** [comment]
Okay, How do I specify dst_md? Is it describing final output from post-ops or intermediate result from major primitive? If i'm appending GELU after inner product, the only possible intermediate is floating point, so should I specify it or it is implicitly f32.

**Comment by dzarukin** [comment]
Didn't pay much attention it was inner product instead of convolution. Inner product doesn't support runtime output `scale1`, unfortunately. It shouldn't be difficult but we need to understand the driver and use case to prioritize this item.

> How do I specify dst_md?

For inner product dst_md is always 2D tensor - {MB, OC}. Any kind of post-ops would apply on top of this tensor.

> If i'm appending GELU after inner product, the only possible intermediate is floating point, so should I specify it or it is implicitly f32?

Eltwise is always applied in f32 data type, this is considered implicitly. As for binary post-op, it is specified by memory descriptor and may contain any data type, but to have it run it should be supported on a hardware you run (thinking of bfloat16 or float16 types). It's dimensions should have ndims=2 for inner product and be either {1, 1} or {1, OC}. Thanks.

**Comment by CaoZhongZ** [comment]
@dzarukin  Hi, sorry to bother you again. If i'm going to hack a linear + scale1 + gelu + scale2 + requant to int8 with runtime scaling factor scale1, scale2.  Which file should I modify for the functionality?

**Comment by dzarukin** [comment]
Hi @CaoZhongZ. I guess nothing should be modified if you use binary post-op after correspondent eltwise. Thanks.

**Comment by CaoZhongZ** [comment]
oh, I see. Thanks! @dzarukin

**Comment by CaoZhongZ** [comment]
@dzarukin Ah, the binary post-op is operated on int8 output, not before the quant output.

**Comment by dzarukin** [comment]
Hi @CaoZhongZ, I'm sorry, not sure I understand what's the problem. Could you, please, provide bit more details on this one? Thanks.

**Comment by CaoZhongZ** [comment]
@dzarukin  The binary post op, does it apply on final output after quantization or, apply on output before final quantization.
