### ISSUE TITLE
Modify s8 output quantize range.

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/oneDNN#1128]
Where can I made a fast change and let i8 output quantized range in [-127, 127] ?

**Comment by igorsafo** [comment]
Hello @CaoZhongZ 
Could you please clarify the question? i8 output always is in range [-127, 127].
- Do you want to quantize data with fp32 values? If so, please use reorder.
- Do you want to experiment with quantization implemented in onednn primitives?

Regards,
Igor Safonov

**Comment by CaoZhongZ** [comment]
Really? Let me check. Why I get -128.

**Comment by igorsafo** [comment]
> Really? Let me check. Why I get -128.

O, my bad, you are right. The default range is [-128, 127]

**Comment by igorsafo** [comment]
@CaoZhongZ Unfortunately there is no single place where quantization behavior can be modified. C-based implementations use the following quantization https://github.com/oneapi-src/oneDNN/blob/e05681eb5d3fbf9c3316cc8344cc02b6c9b1ca5a/src/cpu/simple_q10n.hpp#L43-L51

Some of the jit-base implementations use jit_io_helper https://github.com/oneapi-src/oneDNN/blob/e05681eb5d3fbf9c3316cc8344cc02b6c9b1ca5a/src/cpu/x64/utils/jit_io_helper.cpp#L578-L584

And some of them use their own implementation
https://github.com/oneapi-src/oneDNN/blob/e05681eb5d3fbf9c3316cc8344cc02b6c9b1ca5a/src/cpu/x64/jit_generator.hpp#L1517-L1540

All these places should be updated for s8 data type in order to get quantization [-127, 127].

What is the reason for such quantization?

**Comment by CaoZhongZ** [comment]
Great, thanks!

**Comment by CaoZhongZ** [comment]
https://github.com/oneapi-src/oneDNN/blob/e05681eb5d3fbf9c3316cc8344cc02b6c9b1ca5a/src/cpu/x64/jit_gemm_inner_product_utils.cpp#L598-L624

Since I made vreg_zero -127, can I just use vpmovdb to do the pack of int8?

**Comment by mgouicem** [comment]
Hi @CaoZhongZ , we could use `vpmovdb` to pack to int8 (independently of the value in `vreg_zero` ). However, note that `vpmovdb` is available only in the AVX512F instruction set extension. To keep this code generic and functional on all  system with SSE4.1 and above, we use this sequence of 2 call to `vpackss`.

**Comment by CaoZhongZ** [comment]
@mgouicem I see, thank you for the clarify. I'm just hacking for perf cases, have no intentionally for final production.
