### ISSUE TITLE
NCHW is far slower than NHWC layout in convolution performance benchmarking.

### ISSUE THREAD

**Issue by enszhou** [oneapi-src/oneDNN#1132]
# Summary
I use benchdnn to test the performance of 2D convolution operator implemented with AVX-512 VVNI. It is amazing that the conv2d performance with  `--stag=NHWC` is 1000x faster than the config with `--stag=NCHW`.

# Version
oneDNN v2.3

# Environment
* benchdnn
* Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
* CentOS 7
* GCC 9.3.0
* CMake version 3.15.7
* git hash 593e0de6267d2575f3e4c9e9818f0f11253d093a

# Steps to reproduce
input: (32, 64, 28, 28), logical layout: nchw
kernel: (64, 64, 3, 3), logical layout: oihw
paddings and strides is (1, 1)
so the problem is _mb32\_ic64oc64\_ih28oh28kh3sh1dh0ph1\_iw28ow28kw3sw1dw0pw1_

## NHWC physical layout
Command:
`./benchdnn --conv --engine=cpu:0 --verbose=1 --cfg=u8s8u8 --dir=FWD_I --mode=p --stag=nhwc --wtag=any --dtag=any  mb32_ic64oc64_ih28oh28kh3sh1dh0ph1_iw28ow28kw3sw1dw0pw1`

Output: 
>run: --conv --mode=P --dir=FWD_I --cfg=u8s8u8 --stag=nhwc mb32ic64ih28oc64oh28kh3ph1
>Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
>perf,cpu,brgconv:avx512_core_vnni,,--conv --mode=P --dir=FWD_I --cfg=u8s8u8 --stag=nhwc >mb32ic64ih28oc64oh28kh3ph1,1.76266,0,0.181885,9691.06,0.241879,7287.35
>tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
>total perf: min(ms):0.181885 avg(ms):0.241879

## NCHW physical layout
Command:
`./benchdnn --conv --engine=cpu:0 --verbose=1 --cfg=u8s8u8 --dir=FWD_I --mode=p --stag=nchw --wtag=any --dtag=any  mb32_ic64oc64_ih28oh28kh3sh1dh0ph1_iw28ow28kw3sw1dw0pw1`

Output:
>run: --conv --mode=P --dir=FWD_I --cfg=u8s8u8 --stag=nchw mb32ic64ih28oc64oh28kh3ph1
>Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
>perf,cpu,ref:any,,--conv --mode=P --dir=FWD_I --cfg=u8s8u8 --stag=nchw >mb32ic64ih28oc64oh28kh3ph1,1.76266,0,820.833,2.1474,891.204,1.97784
>tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
>total perf: min(ms):820.833 avg(ms):891.204

# Observed behavior
The average execution time of NHWC layout is 0.241879ms which is 1000x faster than 891.204ms when using NCHW layout. 
In addition, I observe that the library implementation of NHWC is `brgconv:avx512_core_vnni` but the implementation of NCHW is `ref:any`. I don't konw what the mean of `ref:any` implementation.

# Expected behavior
The performance of NHWC and NCHW layout should not be so different.

**Comment by dzarukin** [comment]
Hi @enszhou, thank you for reporting these considerations. oneDNN team has a priority to optimize for `NHWC` layout since this is a default layout (de-facto) for integer computations in all main frameworks using oneDNN underneath while `NCHW` is absolutely not. This is connected to the fact of convenient applicability of certain performance optimizations in `NHWC` format over `NCHW`. An assumption about same level of performance is not quite correct since VNNI instructions or any other integer instructions can't be effectively applied for the latter format because there's a huge stride between channels which may even not be divided by SIMD length.

And that's what can be observed - highly optimized convolution is picked up for `NHWC` format and none of existing int8 convolutions but plain reference is ready to work with `NCHW` format. In most real-world applications `NHWC` is used due to performance considerations. Hope it helps. Thanks.

**Comment by enszhou** [comment]
Great! I got it. Thank you for your reply. @dzarukin

> Hi @enszhou, thank you for reporting these considerations. oneDNN team has a priority to optimize for `NHWC` layout since this is a default layout (de-facto) for integer computations in all main frameworks using oneDNN underneath while `NCHW` is absolutely not. This is connected to the fact of convenient applicability of certain performance optimizations in `NHWC` format over `NCHW`. An assumption about same level of performance is not quite correct since VNNI instructions or any other integer instructions can't be effectively applied for the latter format because there's a huge stride between channels which may even not be divided by SIMD length.
> 
> And that's what can be observed - highly optimized convolution is picked up for `NHWC` format and none of existing int8 convolutions but plain reference is ready to work with `NCHW` format. In most real-world applications `NHWC` is used due to performance considerations. Hope it helps. Thanks.
