### ISSUE TITLE
errors when modify onednn with amd backend

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1186]
hello,
I'm trying to modify onednn with amd support, I added some changes to the onednn source code and a few changes to llvm.
but when I compile the program, I got these errors, I can't find why it came up, please help me.
```
In file included from ~/oneDNN-118/src/gpu/amd/sycl_hip_engine.cpp:1:
In file included from ~/llvm-release/include/sycl/CL/sycl/backend/hip.hpp:3:
In file included from ~/llvm-release/include/sycl/CL/sycl/accessor.hpp:12:
In file included from ~/llvm-release/include/sycl/CL/sycl/atomic.hpp:12:
In file included from ~/llvm-release/include/sycl/CL/sycl/access/access.hpp:10:
In file included from ~/llvm-release/include/sycl/CL/sycl/detail/common.hpp:116:
In file included from ~/llvm-release/include/sycl/CL/sycl/exception.hpp:16:

~/llvm-release/include/sycl/CL/sycl/detail/pi.h:282:42: error: use of undeclared identifier 'CL_DEVICE_SUB_GROUP_SIZES_INTEL'
  PI_DEVICE_INFO_SUB_GROUP_SIZES_INTEL = CL_DEVICE_SUB_GROUP_SIZES_INTEL,

~/llvm-release/include/sycl/CL/sycl/detail/pi.h:1543:25: error: use of undeclared identifier 'CL_DEVICE_HOST_MEM_CAPABILITIES_INTEL'
  PI_USM_HOST_SUPPORT = CL_DEVICE_HOST_MEM_CAPABILITIES_INTEL,
```
there are tons of these errors, which looks similar

**Comment by dzarukin** [comment]
Hi @MOLOjl, thanks for the question.

This error indicates that non-sycl-compatible OpenCL headers were used. There are might be two reasons:
1. You don't provide an explicit path to find these headers from dpcpp compiler. [This commit](https://github.com/oneapi-src/oneDNN/commit/b19001f637f0f28777c19be6ce114a6b8056b899) (in case you don't have it) might help.
2. You have a different version of OpenCL headers in your path which are non-sycl-compatible. We had same issues with cuda backend (since they distributed version of OpenCL headers along with cuda headers) until [this](https://github.com/oneapi-src/oneDNN/commit/6263fa2ff3e4002e14da4bc18cd1547ac6b8f848) work around was implemented. 
My suggestion would be either to adapt same work around for AMD backend (in case they distribute OpenCL headers (I just have no idea if this is the case)), or figure out which headers are used instead of ones coming from dpcpp compiler. Using preprocessor might help with it.

P.S. It might be better to keep all questions in a single tracker. If the tracker was closed, simply re-open it with a new question. This way engineers will have a full context of your problems and history. It also may help for others to check a full tracker with all comments rather that several trackers with different questions. This is just a wish, you don't have to follow it. Thank you.

**Comment by MOLOjl** [comment]
Thanks very much!
I see what's happening, I wrongly set the paths of the OpenCL headers (in where the .h files and .so library are located) to the rocm include&lib paths, which lead to this error.
Following your guide, I added an explicit path (to the OpenCL headers that llvm provided) to the `FindOpenCL.cmake` file, and fixed this error,
But I'm confused about the codes in the `FindOpenCL.cmake` file. Since llvm has provided the OpenCL headers, why don't find them in the llvm/sycl's path?

Parts of my changes to `FindOpenCL.cmake` are like this
```cmake
find_path(OpenCL_INCLUDE_DIR
  NAMES
    CL/cl.h OpenCL/cl.h
  HINTS
    # I added a path to llvm-release/sycl/CL/cl.h here
    ${opencl_root_hints}
    ENV "PROGRAMFILES(X86)"
    ENV AMDAPPSDKROOT
    ENV INTELOCLSDKROOT
    ENV NVSDKCOMPUTE_ROOT
    ENV CUDA_PATH
    ENV ATISTREAMSDKROOT
    ENV OCL_ROOT
  PATH_SUFFIXES
    include
    sycl
    OpenCL/common/inc
    "AMD APP/include")
```
by the way, my choice to find sycl header files(e.g. sycl.hpp) is to add them in the linux env `C_INCLUDE_PATH`&`CPLUS_INCLUDE_PATH`, like this:
```shell
export C_INCLUDE_PATH=~/llvm-release/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=~/llvm-release/include/:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=~/llvm-release/include/sycl:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=~/llvm-release/include/sycl:$CPLUS_INCLUDE_PATH

export LD_LIBRARY_PATH=~/llvm-release/lib:$LD_LIBRARY_PATH
```
is this why OpenCL headers can't be found?
 
P.S. thanks for your advice, I will keep my other questions in this tracker in the future.

**Comment by dzarukin** [comment]
By default compiler doesn't search for headers in `sycl` directory:
```
#include <...> search starts here:
 /path/to/compiler/include
 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9
 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9
 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/backward
 /path/to/compiler/lib/clang/14.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
```
I guess this is done on purpose so that user has a preference which headers to use. That's why you may see `sycl` in suffixes and that's a fix that we put recently.

If you use `clang++ -v -E a.cpp` you may see same output which would show the order of header files search paths and which one is actually picked up or not picked up if paths is not among search directories. I can't say what exactly may cause inability to find OpenCL headers on your side... Thanks.

**Comment by MOLOjl** [comment]
All alright, orz, I'll skip this "path find" question for now and continue my job, thanks for your advice, again.
there are other errors that came up when I try to link an already built onednn library to my program(names `test02.cpp`), they are like this:
```
/usr/bin/ld: /tmp/test02-ff1617.o: in function `dnnl::engine::get_count(dnnl::engine::kind)':
test02.cpp:(.text._ZN4dnnl6engine9get_countENS0_4kindE[_ZN4dnnl6engine9get_countENS0_4kindE]+0x16): undefined reference to `dnnl_engine_get_count'

/usr/bin/ld: /tmp/test02-ff1617.o: in function `dnnl::engine::engine(dnnl::engine::kind, unsigned long)':
test02.cpp:(.text._ZN4dnnl6engineC2ENS0_4kindEm[_ZN4dnnl6engineC2ENS0_4kindEm]+0x33): undefined reference to `dnnl_engine_create'

# and so on...
```
do you have any idea what may cause these errors? 
take the first error as an example, I found the source code here
```c++
// include\oneapi\dnnl\dnnl.hpp
struct engine : public handle<dnnl_engine_t> {
    //...
    static size_t get_count(kind akind) {
        return dnnl_engine_get_count(convert_to_c(akind));
    }
    //...
}

// src\common\engine.cpp
size_t dnnl_engine_get_count(engine_kind_t kind) {
    auto ef = get_engine_factory(kind, get_default_runtime(kind));
    return ef != nullptr ? ef->count() : 0;
}
```
it seems like the definition in `engine.cpp` is not working, I think I must have done something wrong. please help me.

**Comment by dzarukin** [comment]
It seems to me you are using dnnl.hpp core abstractions such as engine for sycl programming model which is not quite right. oneDNN ships dnnl_sycl.hpp which has proper abstractions for engine, stream and memory to operate over and API to create them. You may investigate tests/gtests/sycl/api/*.cpp files to see how it's used and called.

If this doesn't help, please provide your source and build instructions to reproduce the issue on our side. Thanks.

**Comment by MOLOjl** [comment]
Sorry about the above question
it's because I made a stupid mistake, I forgot to add the `-ldnnl` directive when I use `clang++` to compile the `test02.cpp` file
your advice is useful, ultimately, the missing of `libdnnl.so` caused this error.
thanks again.
