### ISSUE TITLE
Questions about the restriction on creating LSTM primitive desc.

### ISSUE THREAD

**Issue by lolbhw** [oneapi-src/oneDNN#1200]
Hello, sir

I'm trying to run some LSTM examples using oneDNN v2.2.  I got this error "could not create a descriptor for an LSTM forward propagation primitive" when the input channel size is not equal to weight hidden size with the layer num > 1.  

Could you please explicitly explain the intent of this restriction？ Also, what should I do exactly when it comes to multi-layers LSTMs. 

Thanks.

**Comment by igorsafo** [comment]
@lolbhw This comes from the RNN architecture -- layers are stacked on top of each other ([Link](https://oneapi-src.github.io/oneDNN/dev_guide_rnn.html)). For the second layer input channels should be equal to output channels of the previous layer to make them compatible. All layers within single RNN primitive are equal, so it is not possible to have different input channels for layers 1 and 2.

**Comment by lolbhw** [comment]
So you are saying that in my case, I have to create two RNN primitives, one for the first layer that have dirrerent input & output channels, another for the rest layers that have same input & output channels? 

> For the current layer input channels should be equal to output channels of the previous layer
I argee what you said above, but according to the LSTM formula，I think the input channel and output channel of each layer could be different.

> All layers within single RNN primitive are equal
About this point，is this for the convenience of primitive implementation or out of the performance considerations？

**Comment by vpirogov** [comment]
+@mgouicem for additional insights

**Comment by mgouicem** [comment]
Hi @lolbhw , yes you have to create separate primitives in your case, one for the first layer and one for the subsequent layers.

 > I argee what you said above, but according to the LSTM formula，I think the input channel and output channel of each layer could be different.

This is true. However, the oneDNN API requires the shape of weights to be the same for all layers in a single primitive since we have only one weights_layer descriptor. This is not a performance consideration, just an API limitation. 
As of now, it should impact performance much because of the way we traverse memory and execute the cells (we traverse timesteps first and then layers).
