### ISSUE TITLE
Can oneDNN automatically adjust the numbers of threads according to the input size?

### ISSUE THREAD

**Issue by lolbhw** [oneapi-src/oneDNN#1201]
dear sir,

I noticed that OpemMP will by default use the number of logical cores，and the number of threads are quite critical to the performance of my net.  The performance actually becomes better when I manully set the OMP threads num to half of the default threads numbers. So I wonder if oneDNN has (or about to have) the function to adjust the threads numbers according to the actual runtime input size for each primitive execution.

Thanks!

**Comment by dzarukin** [comment]
Hi @lolbhw, thank you for the question.
oneDNN doesn't provide any public API to adjust number of threads. For OpenMP runtime it relies on `omp_get_max_threads()` call. So in case you want to adjust the number of threads for whole net unconditionally, oneDNN respects OMP_NUM_THREADS env variable or `omp_set_num_threads(int)` call prior to any of primitive descriptor create calls.
In case you are trying to avoid Hyper-Threading involvement, our regular recommendation is either:
* Switch HT off on the system if it's not generally used, or
* Control number of threads set to physical cores and apply proper affinization of threads.
Some more recommendations may be found here: https://oneapi-src.github.io/oneDNN/dev_guide_performance_settings.html

More info:
oneDNN can't guarantee proper work in case number of threads for a certain primitive changed between creation time and execution time since some implementations may, for example, allocate memory or do specific blocking based on number of threads available at creation time.

Another point here is if number of available threads changed between parallel calls, OMP would re-create internal structure for threads which is way more expensive rather than to run even a small job with all threads available.

And this is what happens inside. oneDNN always calls parallel sections with all threads available but may reduce the number of them being used based on specific heuristics. Sometimes it may even run them sequentially (since it doesn't trigger internal structure re-allocation). This is all done internally. Thanks.

**Comment by lolbhw** [comment]
Thank you for your detailed explanation!

> Another point here is if number of available threads changed between parallel calls, OMP would re-create internal structure for threads which is way more expensive rather than to run even a small job with all threads available.

I understand the harm of resetting the number of available OMP threads. About what you said above that different threads number at creation time and execution time may cause some problems, I'm a little confused, isn't that all parallel sections are synchronous? The threads will be recycled as it's done.  or am I getting it wrong? How could the threads number used for memory allocation at creation time affect the execution time? please enlighten me, thanks!

And another question is that the specific heuristics you mentioned for reducing the number of threads. Is it some work that oneDNN has done internally? If so, please show me some source code where I can get into from.  I believe this is the issue what I'm trying to deal with. Thanks!

**Comment by dzarukin** [comment]
> How could the threads number used for memory allocation at creation time affect the execution time?

The library utilizes so-called scratchpad memory - additional internal buffer(s) to store intermediate output(s). It is booked (defined what size it would be) at pd_t::init stage when primitive descriptor is created. Each implementation defines the way what scratchpad looks like. The most problematic case I've tried to highlight is when scratchpad size depends on number of threads and extending number of threads at runtime may lead to a case a thread would offset out of scratchpad boundaries causing a crash. It's not an often case to allocate memory based on number of threads but still possible.

> Is it some work that oneDNN has done internally?

Just to clarify it, we don't change the number of threads a parallel region would run on. It may happen that during balancing (mostly `balance211` calls) some threads would be given no work and they would just skip an execution. Each parallel region may be supplied with such logic and this is done internally to best of our algorithm knowledge resulting in better performance in most cases. Though some corner cases may happen where such logic would fail to provide better performance.

> If so, please show me some source code where I can get into from.

I may help to identify the spot in case you could share verbose output. I need the header (version and ISA) and specific implementation line to get a proper piece of code for investigation.

If you could also describe your issue with more details, that would also help. Like what's the behavior your observe, what you expect and, maybe, some suspects you've already identified. Thanks.

**Comment by lolbhw** [comment]
I can't provide my whole code here. So I wrote a very simplified version that can reproduce the scene I have observed.

`void muladd() { `
    ` std::vector<float>x(40000);`
   ` std::vector<float>y(40000);`
   ` std::generate(x.begin(), x.end(), []() {`
        `return  rand() / double(RAND_MAX/100);`
   ` });`
   ` std::generate(y.begin(), y.end(), []() {;`
       ` return  rand() / double(RAND_MAX/100);`
  `  });`
   ` auto task = [&](int s, int e) {`
      `  for(int i = s; i<e; ++i) {`
         `   x[i] += x[i] * y[i];`
       ` }`
   ` };`
   ` int thread_num=40;`
    `int stride = 40000/40;`
   ` std::vector<std::thread> threads(thread_num);`
    `for(int l =0; l < thread_num; l++) {`
     `  threads[l] = std::move(std::thread(task, l*stride, (l+1)*stride));`
    `}`
    `for(auto &thr : threads) {`
        `thr.join();`
    `}`
`};`

`void lstm_example() {`
    `auto lstm = LSTM(std::vector<memory::dim> {2000, 100, 256, 4, 4, 1});`
    `lstm.execute();`
   ` muladd();`
  `  lstm.execute();`
    `muladd();`
    `lstm.execute();`
    `muladd();`
    `lstm.execute();`
   ` muladd();`
`}`
`int main() {`
    `lstm_example();`
`}`

The hardware information shows below:
![image](https://user-images.githubusercontent.com/32974998/144398309-2f51f505-ff3d-4e44-a2f7-2da6e4bfbfc2.png)

I run this example with verbose mode on

default case :
>dnnl_verbose,info,oneDNN v2.2.4 (commit c8493289450b919058a0780a5f0a1d417c597ad7)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,4x1x256x4x256,25.854
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,4x1x256x4x256,25.802
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,2001.33
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,1117.58
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,665.43
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,696.056

when export OMP_NUM_THREADS=40 manually：

>dnnl_verbose,info,oneDNN v2.2.4 (commit c8493289450b919058a0780a5f0a1d417c597ad7)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,4x1x256x4x256,1.46216
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,4x1x256x4x256,0.614014
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,1169.03
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,578.701
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,570.798
dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l4t100mb2000sic256slc256dhc256dic256,564.354

in my project the performance varies much more.

**Comment by dzarukin** [comment]
@lolbhw, thanks for posting pseudo-code and machine settings here.
Could you also share how do you run your application, please?
I wonder if you are using any specific affinization or using `numactl` tool in a specific way.
I'm asking since I see HyperThreading on and usually it doesn't bring any good advantage as oneDNN code base doesn't take it into account.
I would recommend to go through [this article](https://oneapi-src.github.io/oneDNN/v2/dev_guide_performance_settings.html) first and try recipes from there if it helps to stabilize performance.
I would rather expect the way to run the application should bring more benefit rather to try to adjust the threading logic inside since it was tested and verified on quite a number of problems and verbose you've shared doesn't look off. Thanks.

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional information.
