### ISSUE TITLE
Computing Convolution Gradients with respect to only one of Bias or Weights

### ISSUE THREAD

**Issue by jacobkahn** [oneapi-src/oneDNN#1227]
I'm looking for a way to compute the gradients of either bias or weights independently for a oneDNN convolution.

It seems like [`convolution_backward_weights`](https://oneapi-src.github.io/oneDNN/v2/structdnnl_1_1convolution__backward__weights.html#a56c06b881cf11a51933d8b05908430fe) computes gradients with respect to both bias and weights simultaneously.

Sometimes, I only need gradients with respect to one of bias or weights — is there a way to only compute gradients with respect to one of them using `convolution_backward_weights`?

Thanks for your help.

**Comment by igorsafo** [comment]
Hi @jacobkahn ,
While there is no straight forward way to compute both weights and bias separately using `convolution_backward_weights` it can be implemented using a combination of the following primitives:
- Use [convolution_backward_weights](https://github.com/oneapi-src/oneDNN/blob/b73e8cba6b0fa4fcdc4baf85dd58c5a218d6d37d/include/oneapi/dnnl/dnnl.hpp#L5116) without bias to compute gradients with respect to weights only;
- Use [reduction](https://github.com/oneapi-src/oneDNN/blob/b73e8cba6b0fa4fcdc4baf85dd58c5a218d6d37d/include/oneapi/dnnl/dnnl.hpp#L11653)  using diff_dst as an input to compute gradients with respect to bias only.

Regards,
Igor

**Comment by jacobkahn** [comment]
Hi @igorsafo — thanks for that information. That's helpful. To clarify:
- It seems I can leave out the bias argument to `convolution_backward_weights` altogether and it will not do the bias computation at all - is that correct?
- Do you anticipate a performance difference between using `reduction` to do the bias gradients and using `convolution_backward_weights` to do them?

Also — can you be a little more specific with what you mean by using `diff_dst` as the input? What is being reduced exactly with that as the input? Thanks for your help.

Jacob

**Comment by igorsafo** [comment]
> * It seems I can leave out the bias argument to `convolution_backward_weights` altogether and it will not do the bias computation at all - is that correct?

Correct, there is a separate [constructor](https://github.com/oneapi-src/oneDNN/blob/b73e8cba6b0fa4fcdc4baf85dd58c5a218d6d37d/include/oneapi/dnnl/dnnl.hpp#L5116) in `convolution_backward_weights` which doesn't have `diff_bias_desc` memory descriptor. If `convolution_backward_weights` is created using that constructor then `diff_bias` computations (gradients with respect to bias) will be skipped.

> * Do you anticipate a performance difference between using `reduction` to do the bias gradients and using `convolution_backward_weights` to do them?

When gradients with respect to weights and bias are computed together implementations can reuse blocks of `diff_dst` (an error that came from the previous operation during backward propagation) while it is still in L1 cache or even on registers. So
in the worst case separate `reduction` will cost moving `diff_dst` from memory to CPU to compute reduction. Aside from an additional memory read threading might add an additional overhead. It might happen that separate `convolution_backward_weights` and `reduction` use different heuristics to distribute computations across cores. Once `convolution_backward_weights` execution is completed, the necessary data (`diff_dst`) will be placed in L1/L2 caches across cores (depends on an actual implementation). If `reduction` implementation distributes work differently between these cores it will lead to unnecessary movements of data between cores during `reduction` execution.

This is why coupling these operations is beneficial from performance perspective.

I would recommend you to create a benchmark and measure actual performance `convolution_backward_weights` against `convolution_backward_weights` (no bias) + `reduction`, because it depends on target CPU, convolution shapes, data type, etc.

> Also — can you be a little more specific with what you mean by using `diff_dst` as the input? What is being reduced exactly with that as the input? Thanks for your help.
> 
> Jacob

As I mentioned earlier in oneDNN notation `diff_dst` is an error which comes from the previous layer/operation during backward propagation. To compute `diff_bias` (gradient with respect to bias) `diff_dst` should be reduced across all dimensions except OC (usually it means {N,H,W}). Here is reference code of backward convolution with respect to weights and bias: [Link](https://github.com/oneapi-src/oneDNN/blob/b73e8cba6b0fa4fcdc4baf85dd58c5a218d6d37d/src/cpu/ref_convolution.cpp#L530)

Reduction is a oneDNN primitive which doesn't have propagation kind. Here is a pseudocode for reusing it for `diff_bias` calculations:
```cpp
    // The following assumptions are made:
    //    - There is conv_diff_bias_md which is used in case of convolution_backward_weights. It is 1d memory descriptor {oc} with tag::x.
    //    - There is conv_diff_bias_memory which is a oneDNN memory object with oc elements.

    // Create operation descriptor.
    // Reduction requires input and output to have the same number of dimensions.
    // Here tag (physical layout) nchw doesn't force any perf limitations, because in reality memory is 1d.
    const auto oc = conv_diff_bias_md.dims()[0];
    auto conv_diff_bias_4d_md =  memory::desc({1, oc, 1, 1}, conv_diff_bias_md.data_type(), tag::nchw);

    auto reduction_d = reduction::desc(
            algorithm::reduction_sum, conv_diff_dst_md, conv_diff_bias_4d_md, 0.f, 0.f);

    // Create primitive descriptor.
    auto reduction_pd = reduction::primitive_desc(reduction_d, engine);

    // Create the primitive.
    auto reduction_prim = reduction(reduction_pd);

    // Primitive arguments.
    std::unordered_map<int, memory> reduction_args;
    reduction_args.insert({DNNL_ARG_SRC, conv_diff_dst_mem});
    reduction_args.insert({DNNL_ARG_DST, conv_diff_bias_mem});

    // Primitive execution: Reduction (Sum).
    reduction_prim.execute(engine_stream, reduction_args);

```

Regards,
Igor

**Comment by jacobkahn** [comment]
@igorsafo thanks for the clarification.

After adding this, it seems I have some subtle accuracy differences in the gradients — for the bias. Is it possible the computation when doing the weight and bias gradient computation at the same time is slightly different compared to doing this reduction?

Thanks again for all of your help.

**Comment by igorsafo** [comment]
Hi @jacobkahn ,

Sure, each of these primitives has its own set of implementations and the end result might be slightly different due to floating point numbers. Reduction operation is especially sensitive to such issues.
