### ISSUE TITLE
benchdnn output

### ISSUE THREAD

**Issue by TharinduRusira** [oneapi-src/oneDNN#1237]
Hi,
I’m running benchdnn built from the GitHub source.

`benchdnn --conv --dir=FWD_I --cfg=f32 --alg=DIRECT g1mb64_ic64id1ih56iw56_oc128_kd1kh3kw3_sh1sw1_ph0pw0`

and I get the following output

```
0:PASSED __REPRO: --conv --dir=FWD_I g1mb64ic64id1ih56iw56oc128od1oh54ow54kd1kh3kw3pd0ph0pw0nS
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total compute_ref: sum(s):97.55 
```

I believe 97.55 is the total elapsed time but I’m just wondering if the benchmark collects other statistics as well such as throughput in GFLOPS/s. I remember seeing this information, probably with an older version of benchdnn.

**Comment by dzarukin** [comment]
Hi @TharinduRusira, thanks for the question. This time refers to number of seconds spent in reference convolution in benchdnn  convolution driver used for results verification. This is reported because correctness validation mode was chosen (it's a default mode). You may want to use a performance mode (`--mode=P`). It will produce metrics you are seeking for. This is a [benchdnn doc main page](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md), might give some hints. Thanks.

**Comment by TharinduRusira** [comment]
Thank you, @dzarukin! Performance mode does the trick.
