### ISSUE TITLE
benchdnn conv WARNING

### ISSUE THREAD

**Issue by TharinduRusira** [oneapi-src/oneDNN#1261]
Hi, I'm running the following benchdnn command,
`benchdnn --conv --dir=FWD_I --cfg=f32 --mode=P --alg=DIRECT mb64_ic64ih58iw58_oc512_kh3kw3_sh1sw1_ph0pw0 --stag=nhwc --wtag=hwio`

and getting the following output. 

`Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,brgconv:avx512_core,,--conv --mode=P --dir=FWD_I mb64ic64ih58oc512oh56kh3ph0,118.38,0,605.213,195.601,605.519,195.502
conv driver: WARNING: No problem found for a given option!
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):605.213 avg(ms):605.519`

I would like to know why I'm getting the `WARNING`. My first guess was incompatible/undefined memory tags but both `nhwc` and `hwio` tags are defined in `include/oneapi/dnnl/dnnl.hpp`.

**Comment by dzarukin** [comment]
Hi @TharinduRusira, thank you for the question. benchdnn expects to see the problem descriptor as the very last piece of the command line. It parses tokens one by one, not the whole line identifying all pieces. Thus, it applies `--dir=FWD_I --cfg=f32 --mode=P --alg=DIRECT` to `mb64_ic64ih58iw58_oc512_kh3kw3_sh1sw1_ph0pw0`, then it reads two more arguments `--stag=nhwc --wtag=hwio` and doesn't see a problem descriptor to apply these two (and others specified earlier, since it saves the state of previously parsed options), literally saying - "No problem found for a given option". Likely not the best message, may consider to update it with better wording.

If the intention is to use those `--stag=nhwc --wtag=hwio` for this problem, the only way to do it is to specify them in from of the problem description:
`--dir=FWD_I --cfg=f32 --mode=P --alg=DIRECT --stag=nhwc --wtag=hwio mb64_ic64ih58iw58_oc512_kh3kw3_sh1sw1_ph0pw0`.
Thank you.

**Comment by densamoilov** [comment]
@dzarukin, looking at verbose output, it seems that `benchdnn` still runs something, not sure if it's correct behavior though.

**Comment by dzarukin** [comment]
@densamoilov it is correct and expected behavior. I've edited a comment to clarify that. Thanks for pointing this out.

**Comment by TharinduRusira** [comment]
Thank you! Reordering the arguments did the trick. 
Closing this issue.
