### ISSUE TITLE
What is BRGEMM?

### ISSUE THREAD

**Issue by dev2y** [oneapi-src/oneDNN#1269]
Hi, general question. I know what SGEMM and DGEMM are from this [doc](https://www.intel.com/content/www/us/en/develop/articles/a-simple-example-to-measure-the-performance-of-an-intel-mkl-function.html) on MKL but I couldn't find any documentation on BRGEMM, which is widely used in oneDNN repo.

**Comment by kwiersch** [comment]
Hi @dev2y, BRGEMM is the so-called batch reduce GEMM introduced by this paper: https://arxiv.org/abs/1906.06440. It's not part of the oneDNN API, which is why you don't find anything about it in the documentation. But it is used as a sort of internal API for certain oneDNN primitive implementations such as convolution, inner product, and matmul. It's interface is defined here: https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/brgemm/brgemm.hpp.
