### ISSUE TITLE
C API to fill memory data

### ISSUE THREAD

**Issue by edubart** [oneapi-src/oneDNN#1294]
I could not find a way to initialize memory data with a constant value in the documentation. Is there a way to do this without using `dnnl_memory_map_data`? Because using it can incur overhead and it may not paralelize. I miss a C API for a primitive capable of initializing memory data in a parallel way. My use case is to initialize large tensors with zeros, ones or other constant value.

**Comment by dzarukin** [comment]
Hi @edubart, thank you for the question.

The best way to initialize memory data with a constant value is to allocate the memory on user side and initialize it in the preferable way, which may include parallelization enabled.

When creating a memory object, just pass a pointer to user data like [here](https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/convolution.cpp#L125) and further [here](https://github.com/oneapi-src/oneDNN/blob/master/examples/example_utils.hpp#L227). On CPU `dnnl_memory_map_data` just saves a pointer inside the object to use it on execution, no copies. On GPU, since there should be a correspondent memory on a device, we rely on the backend call, either `clEnqueueMapBuffer` or `usm::memcpy` for OpenCL, either `sycl::memcpy` or through accessor for sycl buffers for SYCL backend. The call transfers user data to the memory on the device. These calls are not under oneDNN control and their effectiveness is on backend implementation. Thank you.

**Comment by edubart** [comment]
Thanks for the clarification.

> On GPU, since there should be a correspondent memory on a device, we rely on the backend call, either clEnqueueMapBuffer or usm::memcpy for OpenCL, either sycl::memcpy or through accessor for sycl buffers for SYCL backend.

I am using the SYCL backend,  however I am limited to just the C API, so I have no direct access to the sycl interface. I think the mentioned `write_to_dnnl_memory` function could be promoted to an official C API, as it seems to copy data in parallel, and that is useful.

I also thought using `dnnl_eltwise_linear` primitive with `alpha=0` and `beta=k` where `k` is the constant I wish to initialize the memory, however I think this approach will fail in case the uninitialized memory contains `NaN` floats (unless there is some specialization for `alpha=0` skipping the multiplication, thus NaNs would not propagate).

**Comment by vpirogov** [comment]
Closing as there's no plans to cover capabilities supported by general purpose programming model in oneDNN.
