### ISSUE TITLE
How to check memory allocation size for "jit_blk_reorder_t"

### ISSUE THREAD

**Issue by kawakami-k** [oneapi-src/oneDNN#1334]
I'm porting jit_blk_reoreder_t for AArch64. The source code is 
https://github.com/kawakami-k/oneDNN/tree/reorder

I tried the following pattern, and it exited with a segmentation fault.
". /benchdnn --reorder --mode=C --sdt=f32 --ddt=f32 --stag=ab --dtag=BA16a16b --attr-oscale=common:0.125 --attr-post-ops=sum:0.5 89x73"

It seems to be faulting when the benchdnn tries to store data to 25,988 bytes from the beginning of the destination memory. This number is exactly equal to 73 multiplied by 89. I think the destination memory is allocated with no padding area.

In this case, where in the source code should I investigate?
What part of the source code determines the size of the destination memory?

Thank you.

**Comment by dzarukin** [comment]
Hi @kawakami-k, thank you for the question.

The symptoms described seem to be a memory protection trigger. Benchdnn uses `mprotect` to catch out-of-bound accesses and it will crash if such access happens.
The allocation on benchdnn side is done [here](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/dnnl_memory.cpp#L489). It calls every time a `dnn_mem_t` is constructed with allocation (99% of all objects in code).
If you suspect that destination memory descriptor was created wrongly, the best point to start is [here](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/reorder/reorder.cpp#L322). This is where reorder destination memory will be created. You may start with inspecting `dst_md` which comes from the library. It should contain `blocking_desc` with blocks reflecting the tag passed from command line.
If memory descriptor is incorrect, then you may go up and check the implementation's `pd_t::create()` [function](https://github.com/kawakami-k/oneDNN/blob/reorder/src/cpu/x64/jit_uni_reorder.cpp#L2443) to check what may cause the issue.

Since there's a sum post-op, it may also crash [here](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/reorder/reorder.cpp#L331).

If all of this doesn't help, could you, please, share a back trace? Thank you.

**Comment by igorsafo** [comment]
Hi @kawakami-k ,
The size is calculated by `memory_desc_wrapper` based on `memory_desc`, other parts use it to get size and allocate a required memory chunk. Before that the memory descriptor is filled either by a test or by a primitive implementation, for example, sve512 convolution implementation.
Here is the code that calculates amount of memory required for a given memory descriptor: https://github.com/oneapi-src/oneDNN/blob/682a91bdbcc8e494935f9a4d4b98bcd47ac3bfce/src/common/memory_desc_wrapper.hpp#L149-L189

Regards,
Igor Safonov
