### ISSUE TITLE
what is the full name of nstl ?

### ISSUE THREAD

**Issue by wangzy0327** [oneapi-src/oneDNN#1338]
when I read source code, I find nstl namespace in [nstl.hpp](https://github.com/oneapi-src/oneDNN/blob/master/src/common/nstl.hpp)
what is the full name of nstl ? what it means?

**Comment by igorsafo** [comment]
Hi @wangzy0327 ,
I don't remember where the name came from, but the initial idea was to avoid C++ runtime dependency by implementing required stl functionality on oneDNN side in nstl namespace. This would allow users to use oneDNN in environment where C++ is not available, for example, in C applications. In that case C application uses oneDNN C API and oneDNN implementation doesn't have any dependencies on C++.

Since then the vision changed due to lack of pure C users of oneDNN, so there are no requirements to replace stl functionality by implementing nstl analogues hence you can find a lot of stl containers used across the library.

Regards,
Igor
