### ISSUE TITLE
benchdnn reporting 'unimplemented' as 'failed'?

### ISSUE THREAD

**Issue by diaena** [oneapi-src/oneDNN#1359]
# Summary
I think benchdnn is reporting unimplemented test cases as failed:
```
tests:284264 passed:3220 skipped:280322 mistrusted:0 unimplemented:722 invalid_arguments:0 failed:722 listed:0
total compute_ref: sum(s):940.41
```
I grep-ed for FAILED as well as manually looked through the logs for any failed cases but couldn't find any.

# Version
oneDNN master (as of yesterday) (8f18e6380b69cf85ce0e7373b292ba6a315ba92d) 

# Steps to reproduce
I've been running 'test_conv_all' in benchdnn:
`./benchdnn --conv --batch=inputs/conv/test_conv_all`

# Observed behavior
Looks like 'unimplemented' test cases are also counted as 'failed'.

# Expected behavior
Hope I'm not wrong to assume that 'unimplemented' does not count as 'failed'.

**Comment by diaena** [comment]
Hi @dzarukin, thanks for the clear answer.

I had a closer look, and all of the UNIMPLEMENTED tests are configured with `--cfg=f64`, should these even attempt to run on a CPU device? They are part of `test_conv_all` which we're trying to accommodate for `DNNL_AARCH_USE_ACL` builds. I'm thinking maybe we shouldn't worry about the whole suite and instead make our own `test_conv_acl`? What do you think/suggest?

Thanks
_Diana_

**Comment by dzarukin** [comment]
Hi @diaena,
The fact the f64 returns unimplemented on CPU sounds like an issue. I've opened a PR to solve this. It seems that nobody used test_conv_all after f64 was introduced (or nobody reported the problem).

I don't think it's beneficial for ACL builds to introduce a new input file since it means maintenance and following the coverage. I kindly suggest to stay on path of reporting problems once they occur. It also takes time, but I believe it takes way less than keeping infrastructure up-to-date.

Thank you for reporting the issue, the tracker will close once PR lands to master.
