### ISSUE TITLE
Can not use threads

### ISSUE THREAD

**Issue by loveHoloForeever** [oneapi-src/oneDNN#1385]
I am using OneDNN to train LSTM on CPU. I would like to start a thread to run the LSTM forward process and use the main thread to do something else. However, if I put LSTM on the main thread, it can run correctly. But if I put it on another thread, it occur a segment fault when it reaches lstm_prim.execute() function. Is there something I forget when I use threads? Or it just can not support multithreads?

**Comment by densamoilov** [comment]
Hi @loveHoloForeever, it might be caused by using the default scratchpad mode, which requires a primitive to be executed by the thread that created it. You can try to pass a CMake option ONEDNN_ENABLE_CONCURRENT_EXEC=ON to change the default behavior.

You can find more details in the [doc](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_scratchpad.html#doxid-dev-guide-attributes-scratchpad).
