### ISSUE TITLE
[v2.6] fails to build on ppc64el

### ISSUE THREAD

**Issue by cdluminate** [oneapi-src/oneDNN#1390]
# Summary

onednn v2.6 fails to build on ppc64el
https://buildd.debian.org/status/fetch.php?pkg=onednn&arch=ppc64el&ver=2.6-1%7Eexp1&stamp=1654667789&raw=0

Please ignore the ansi escape sequences:
```
[31mFAILED: [0mexamples/CMakeFiles/cnn-inference-f32-c.dir/cnn_inference_f32.c.o 
/usr/bin/cc -DCL_TARGET_OPENCL_VERSION=120 -DDNNL_DLL -DDNNL_PPC64=1 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/obj-powerpc64le-linux-gnu/include -I/<<PKGBUILDDIR>>/examples -I/<<PKGBUILDDIR>>/src/../include -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fdiagnostics-color=always  -Wdate-time -D_FORTIFY_SOURCE=2 -fopenmp  -Wall -Wno-unknown-pragmas -fvisibility=internal -Wno-ignored-attributes   -fPIC -Wformat -Wformat-security -fstack-protector-strong -std=c99    -Wno-strict-overflow -Wno-maybe-uninitialized -O2 -g -DNDEBUG -MD -MT examples/CMakeFiles/cnn-inference-f32-c.dir/cnn_inference_f32.c.o -MF examples/CMakeFiles/cnn-inference-f32-c.dir/cnn_inference_f32.c.o.d -o examples/CMakeFiles/cnn-inference-f32-c.dir/cnn_inference_f32.c.o -c /<<PKGBUILDDIR>>/examples/cnn_inference_f32.c
In file included from [01m[K/<<PKGBUILDDIR>>/examples/cnn_inference_f32.c:50[m[K:
[01m[K/<<PKGBUILDDIR>>/examples/example_utils.h:[m[K In function ‘[01m[Kread_from_dnnl_memory[m[K’:
[01m[K/<<PKGBUILDDIR>>/examples/example_utils.h:108:15:[m[K [01;31m[Kerror: [m[Kincompatible types when initializing type ‘[01m[K__vector __bool int[m[K’ {aka ‘[01m[K__vector(4) __bool int[m[K’} using type ‘[01m[Kint[m[K’
  108 |             = [01;31m[K([m[KDNNL_CPU_RUNTIME == DNNL_RUNTIME_SYCL && eng_kind == dnnl_cpu);
      |               [01;31m[K^[m[K
[01m[K/<<PKGBUILDDIR>>/examples/example_utils.h:110:30:[m[K [01;31m[Kerror: [m[Kinvalid operands to binary || (have ‘[01m[Kint[m[K’ and ‘[01m[K__vector __bool int[m[K’ {aka ‘[01m[K__vector(4) __bool int[m[K’})
  110 |     if ([32m[Keng_kind == dnnl_gpu[m[K [01;31m[K||[m[K is_cpu_sycl) {
      |         [32m[K~~~~~~~~~~~~~~~~~~~~[m[K [01;31m[K^~[m[K
      |                  [32m[K|[m[K
      |                  [32m[Kint[m[K
```

# Version

git tag v2.6

# Environment

* CPU: it should be power8
* OS version (`uname -a`) `Kernel: Linux 5.10.0-14-powerpc64le #1 SMP Debian 5.10.113-1 (2022-04-29) ppc64el (ppc64le)`
* Compiler version (`gcc --version`)  gcc-11
* CMake version (`cmake --version`) maybe irrelevant. can be found in log
* CMake output log: link above

**Comment by dzarukin** [comment]
Hi @cdluminate, thanks for letting us know. Do you have a chance to use older compiler to see if this is the main source of a problem?
The message doesn't make much sense to me (__vector __bool part is very confusing) ...

**Comment by cdluminate** [comment]
Yes. Our tooling also allows us to do qemu compile for ppc64el on amd64 (`schroot` + `qemu-user-static`). I can try to downgrade compiler to gcc-10 for ppc64el and see what happens.

**Comment by frediz** [comment]
This comes from the opencl headers including altivec.h on ppc64el which "#define bool __bool" where __bool is __attribute__((altivec(bool__))) unsigned ( Altivec and c++ types bool, vector, pixel collide)
This happens in examples/example_utils.h at #include "dnnl_ocl.h".
So we lose the actual #define bool _Bool from stdbool.h .
The only line using bool is the one declaring "is_cpu_sycl" so a fix makes
sense only in example_utils.h (anyway above that i.e. dnnl_ocl.h, the whole compilation breaks
because there, altivec is used).

Not sure what is the best way to do that.
Either use _Bool instead of bool on that line (and remove stdbool.h which is only used for that) 
or redefine bool only on ppc64el right after #include "dnnl_ocl.h" or include stdbool.h after "dnnl_ocl.h"...
Not very satisfying, but I hope the explanation helped.

**Comment by igorsafo** [comment]
Hi @frediz ,
While I agree we can fix it and let OpenCL to take care of things, there is no much value in oneDNN GPU support being built on arm64, s390x and ppc since there are no implementation support for these architectures, so even if we fix this issue there is no guarantee it will work and nothing will break in the future (someone who is not aware of altivec issue could change part of tests/implementation). So the most bullet-proof solution is to disable GPU support where it is not implemented. Once GPU support is available for one of architectures (there are implementations and tests in place) then it makes sence to fix issues related to that architecture.

Regards,
Igor

**Comment by vpirogov** [comment]
Closing as not a defect, as OpenCL backend is not supported on the platform in question.
