### ISSUE TITLE
how to solve oneDNN build from source on NVIDIA GPU runtime getting error?

### ISSUE THREAD

**Issue by wangzy0327** [oneapi-src/oneDNN#1392]
I build oneDNN from source files on NVIDIA GPU runtime follow from the doc
[https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html]

this is my build command line:
export CC=$HOME/sycl_workspace/build-cuda-debug
export CXX=$HOME/sycl_workspace/build-cuda-debug
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
-DDNNL_CPU_RUNTIME=NONE -DDNNL_GPU_RUNTIME=DPCPP \
-DDNNL_GPU_VENDOR=NVIDIA -DCMAKE_BUILD_TYPE=Debug \
-DDNNL_BUILD_EXAMPLES=OFF -DDNNL_BUILD_TESTS=ON \
-DCMAKE_INSTALL_PREFIX=$HOME/sycl_workspace/oneDNN-cuda-debug/

This is the build logs:
![image](https://user-images.githubusercontent.com/22990858/172750477-95865f02-e823-4b81-921f-53e2032ba063.png)

how to solve it some libraies may not to be found correctly?

when I run make,it get error

![image](https://user-images.githubusercontent.com/22990858/172753199-8dcb8921-1427-45f9-8392-ab1b74efe7df.png)

**Comment by densamoilov** [comment]
If yo take a look at the error message you will see that `get_native_pointer(...)` cannot be called due to a problem with inferring default argument.
![image](https://user-images.githubusercontent.com/11770112/172754184-66e5ad92-92c1-4838-bc45-05c4a714e659.png)
https://github.com/oneapi-src/oneDNN/blob/372417152365eeba5d020ecc8438f2c829f490c8/src/gpu/nvidia/sycl_cuda_memory_storage_helper.hpp#L72-L74
I suspect `::sycl::backend::ext_oneapi_cuda` is not available for some reason. How did you build the compiler and what commit you used?

**Comment by wangzy0327** [comment]
> If you take a look at the error message you will see that `get_native_pointer(...)` cannot be called due to a problem with inferring default argument. ![image](https://user-images.githubusercontent.com/11770112/172754184-66e5ad92-92c1-4838-bc45-05c4a714e659.png)
> 
> https://github.com/oneapi-src/oneDNN/blob/372417152365eeba5d020ecc8438f2c829f490c8/src/gpu/nvidia/sycl_cuda_memory_storage_helper.hpp#L72-L74
> 
> 
> I suspect `::sycl::backend::ext_oneapi_cuda` is not available for some reason. How did you build the compiler and what commit you used?

I have build llvm toolchain which its tag is [2021-09](https://github.com/intel/llvm/tree/2021-09)  following the [GetStartGuide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md)

**Comment by densamoilov** [comment]
That compiler is too old, it uses a different name for `ext_oneapi_cuda`, please try one of the recent ones.
