### ISSUE TITLE
how to utilize the parallel operators to further improve the performance

### ISSUE THREAD

**Issue by lzwhard** [oneapi-src/oneDNN#1441]
![image](https://user-images.githubusercontent.com/29856952/185284756-778acf89-b2b6-4e9e-a07d-c5dea49f2a43.png)

I want to utilize the parallel operators in the network to further improve the performance. The normal network runs serially, and each operator runs on 16 logical cores. I now find that the network has parallel parts, so I want to make four _convs_ parallel, each using 4 cores (other non parallel operators still use 16 cores). Can this improve the performance? How to set conv to run on 4 cores and other operators to run on 16 cores, or do you have any suggestions?

Thanks a lot!

**Comment by dzarukin** [comment]
Hi @lzwhard, thank you for the question. Both models have their own pros and cons when it comes to performance numbers.
There's a point where both approaches will perform comparably same. The smaller convolutions are, the faster will be a second approach and first one will be slower, and vice versa for big convolutions because 4 convolutions increase pressure on memory roughly 4 times. It likely happens that they will compete for L3 cache and might overwrite each other pieces of data (mostly weights are under concern). This is a likely effect for big convolutions.

Apart of that, oneDNN doesn't give a smooth opportunity to implement a second approach with Threadpool interface. It may be possible with OpenMP backend but the application integration code will become more complex with no clear vision whether it helps much.

This approach might bring benefits in particular models with particular sizes but in general I would not recommend doing split like this just because of memory pressure. Thank you.
