### ISSUE TITLE
conv_scales is not used in 3.0 version's cnn_inference_int8.cpp example

### ISSUE THREAD

**Issue by leslie-fang-intel** [oneapi-src/oneDNN#1516]
In the 3.0 version's cnn_inference_int8.cpp example, I find the `conv_scales` is set but not used. 
https://github.com/oneapi-src/oneDNN/blob/602695eefb6d8e51fadb922e69fd178bd3bbea77/examples/cnn_inference_int8.cpp#L73

Is it desired? Does it mean the convolution's dequant and requant scale will be calculated by `src_scale_memory`, `wei_scale_memory` and `dst_scale_memory`?
https://github.com/oneapi-src/oneDNN/blob/602695eefb6d8e51fadb922e69fd178bd3bbea77/examples/cnn_inference_int8.cpp#L242-L249

**Comment by leslie-fang-intel** [comment]
@igorsafo Could you help to take a look?

**Comment by vpirogov** [comment]
Hi @leslie-fang-intel,

oneDNN v3.0 implements [new quantization scheme](https://github.com/oneapi-src/oneDNN/tree/rfcs/rfcs/20220201-quantization-scaling) that relies on per-argument scales instead of a single output scale. The code related to `conv_scales` in the example seem to be an artifact of the example rewriting to oneDNN v3.0 API.

+@mgouicem

**Comment by vpirogov** [comment]
Fixed by 6b6502e0bce19eaf6650a69b826754eba0eb3c02.
