### ISSUE TITLE
How can I identify which primitive generated the ONEDNN_JIT_DUMP when running a model?

### ISSUE THREAD

**Issue by cfRod** [oneapi-src/oneDNN#1520]
Hi, 

I am running a model with ONEDNN_JIT_DUMP turned on, as I am interested in seeing the generated JIT for a specific reorder kernel  (on AArch64). I can see that the model has generated a number of dnnl_dump_cpu_jit_uni_reorder_kernel_f32.number.bin files where I assumed "number" corresponded to the position of that reorder layer. 
```
-rw-r--r--  1 ubuntu ubuntu   9248 Dec 14 15:41 dnnl_dump_cpu_jit_uni_reorder_kernel_f32.7.bin
-rw-r--r--  1 ubuntu ubuntu   6144 Dec 14 15:41 dnnl_dump_cpu_jit_uni_kernel.3.bin
-rw-r--r--  1 ubuntu ubuntu   6144 Dec 14 15:41 dnnl_dump_cpu_jit_uni_kernel.5.bin
-rw-r--r--  1 ubuntu ubuntu   6880 Dec 14 15:41 dnnl_dump_cpu_jit_uni_reorder_kernel_f32.4.bin
-rw-r--r--  1 ubuntu ubuntu   8352 Dec 14 15:41 dnnl_dump_cpu_jit_uni_reorder_kernel_f32.6.bin
-rw-r--r--  1 ubuntu ubuntu   8384 Dec 14 15:41 dnnl_dump_cpu_jit_uni_reorder_kernel_f32.2.bin
-rw-r--r--  1 ubuntu ubuntu   6144 Dec 14 15:41 dnnl_dump_cpu_jit_uni_kernel.1.bin
-rw-r--r--  1 ubuntu ubuntu   6960 Dec 14 15:41 dnnl_dump_cpu_jit_uni_reorder_kernel_f32.0.bin
```
1) Is there a better way to do this at the model-level?
2) Why would the number dnnl_dump_cpu_jit_uni_reorder_kernel_f32.\*.bin files different to the number of actual reorders I am seeing? I see 76 reorders (without warm up runs) in the onednn verbose logs but I get 32 dnnl_dump_cpu_jit_uni_reorder_kernel_f32.\*.bin files.
3) The generated JIT dump for the reorder from TensorFlow looks different to the one I get from running the layer in benchdnn. Is that expected ( I ran the same problem size and format tags) and it is calling the same implementation)?

In benchdnn
```
ONEDNN_JIT_DUMP=1 DNNL_VERBOSE=1  ./tests/benchdnn/benchdnn --reorder --allow-enum-tags-only=0 --mode=p --stag=ba --dtag=Ab8a 21843x1280
....
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ba:f0 dst_f32:p:blocked:Ab8a:f0,,,21843x1280,22.4209
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ba:f0 dst_f32:p:blocked:Ab8a:f0,,,21843x1280,22.3811
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ba:f0 dst_f32:p:blocked:Ab8a:f0,,,21843x1280,22.376
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ba:f0 dst_f32:p:blocked:Ab8a:f0,,,21843x1280,22.4399
```
In TensorFlow
```
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ba:f0 dst_f32:p:blocked:Ab8a:f0,,,21843x1280,
```

**Comment by dzarukin** [comment]
Hi @cfRod, there's a lot of questions. :)
Let's try to get them one by one.

*) I'm looking at the code and I see this:
`jit_uni_eltwise.cpp:  64       :    DECLARE_CPU_JIT_AUX_FUNCTIONS(jit_uni_kernel)`
It seems that `jit_uni_kernel` dumps are actually eltwise, could you confirm that, please?
I'd probably submit a PR to change the name to reflect `eltwise` component in it.

*) Enumeration of dumped kernels are going from the logical order of kernel generation. It correlates with verbose but only jitted implementation should be counted for such. It means that if you have, e.g., jit conv, simple bnorm, jit eltwise, you'll get two dumped kernels, three rows in verbose, and first kernel will correspond to the first verbose line, while the second one will already correspond to the third verbose row. Note that this is all under assumption that single primitive generates a single kernel, which is not always true.

2) The reason you are seeing less kernels is primitive cache. Primitive kernels gets generated only when primitive->create() call happens and it's skipped if the primitive is already in cache.

1) I guess slightly an easier way to get the desired kernel is to disable primitive cache (preferably build time), then you'll get primitive->create() call every time and files will get generated. Then you'll need to find a spot between two primitives and match the desired one.

3) I don't think this is expected but it may happen you are looking at a wrong kernel. Reorder driver is a little trickster since it's easy to confuse the kernel that runs in the library against the "service" reorder which prepares data for comparison. Here's a little example for x64:
```
onednn_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,16x16x16x16,8.76196
onednn_verbose,exec,cpu,reorder,jit:blk,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:aBcd16b:f0,,,16x16x16x16,0.13501
onednn_verbose,exec,cpu,reorder,jit:blk,undef,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:abcd:f0,,,16x16x16x16,0.045166
0:PASSED __REPRO: --reorder --sdt=f32 --ddt=f32 --stag=abx --dtag=aBx16b 16x16x16x16
```
This generates three kernels:
```
#       dnnl_dump_cpu_jit_single_blk_kernel.0.bin
#       dnnl_dump_cpu_jit_single_blk_kernel.1.bin
#       dnnl_dump_cpu_jit_single_blk_kernel.2.bin
```
while one could expect two. It may happen that the kernel generates tail cases as a separate entity as well. So a developer should make sure they are looking at the right file. Sometimes it takes time to figure it out.

If some of this doesn't help or doesn't cover the topic, please let me know. Thanks.

**Comment by cfRod** [comment]
Thanks @dzarukin ,

>It seems that jit_uni_kernel dumps are actually eltwise, could you confirm that, please?
I'd probably submit a PR to change the name to reflect eltwise component in it.

Yes it is!

Your suggestions definitely made it clearer. I was indeed looking at the wrong bin and comparing. Thanks for pointing that out.
