### ISSUE TITLE
Extending the set of available primitives without modifying the code of the library

### ISSUE THREAD

**Issue by dkireevyadro** [oneapi-src/oneDNN#1522]
Hello, oneDNN team!

I have a rather untypical question, and hope that you can help with it.
Right now I implement my own OpenVINO plugin, for inference, on Intel x86 platform. As such I use some primitives from oneDNN, in my codebase. I can see that some of the primitives that I require are missing from oneDNN. 
With regards to the previous statements, I have two questions:

- Is there a way to somehow provide my own primitive implementations, to oneDNN framework, without modifying the source code of oneDNN itself. For exmaple inheriting from `primitive_t` and supplying an instance of my own primitive, to the map of implementations, returned by oneDNN?
- If such a mechanism exists, is it possible to only provide certain implementation of existing primitives (e.g. optimized for different platform, or using different low level optimizations), or I can add primitives that are missing from oneDNN?

Looking foward to any feedback you can provide.
Thank you in advance!

**Comment by igorsafo** [comment]
Hi @dkireevyadro ,
What is the motivation for adding primitives into oneDNN?

* oneDNN doesn't try to be a framework, it is expected that the application where oneDNN is used has necessary reference implementations and oneDNN is used for performance critical operations. In your case those reference implementations can be placed into your OpenVino plugin. As @feng-intel mentioned for OpenCL and DPCPP runtimes oneDNN provides interoperability API, so application can mix oneDNN calls with the rest of the application compute.

* For the primitives already implemened in oneDNN user can specify workload type and primitives to disable all other implementations in order to minimize oneDNN binary size. Please review https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html#build-options

<html>
<body>


CMake Option | Supported values (defaults in bold) | Description
-- | -- | --
ONEDNN_ENABLE_WORKLOAD | TRAINING , INFERENCE | Specifies a set of functionality to be available based on workload
ONEDNN_ENABLE_PRIMITIVE | ALL , PRIMITIVE_NAME | Specifies a set of functionality to be available based on primitives


</body>
</html>

**Comment by dkireevyadro** [comment]
Hello, @igorsafo !
Thank you for your answer. 
Basically the motivation for trying to extend oneDNN functionality, was due to the need to separate the primitives implementations and plugin code, in such a way, that plugin always calls oneDNN code. Without actually having to implement some primitives inside the plugin itself, and calling that exact implementations, sort of "inplace", e.g. how it is done in Intel CPU OpenVINO plugin, where many primitives are implemented as some classes, that are called from within the same files, where they are implemented.

**Comment by igorsafo** [comment]
@dkireevyadro I see, unfortunately oneDNN doesn't provide such extensibility. The reason we keep oneDNN to support only a limited set of ops is that each new operation adds maintanence cost (a new operation should be properly specified, implemented, tested and documented) and there is a huge amount of operations in , some of them are with semantics inconsitencies across DL frameworks/applications.

As a result we focus on a specific set of operations that satisfy the following properties:
- Performance: the functionality has material impact on a workload level. In other words, this means that for a new primitive it should be demonstrated that it brings visible performance improvement to some workload.

- Generality: the functionality is useful in a wide range of deep learning applications. This implies that when introducing a new primitive, its API needs to be general enough to be integrated into multiple deep learning frameworks that have similar functionality.

- Complexity: it is not trivial to implement the functionality directly in a deep learning application.

Is it possible to reuse part of OpenVino CPU plugin by reusing implementations and recompiling them for the hardware you are targeting?

**Comment by dkireevyadro** [comment]
@igorsafo 
Yeah, it seems there are no other options, but to do it like it's done in existing OV plugin. Thank you for clarifying details of oneDNN philosophy. Thank you!

**Comment by igorsafo** [comment]
Closing the issue
