### ISSUE TITLE
Post op implementation is at micro kernel level?

### ISSUE THREAD

**Issue by avinashcpandey** [oneapi-src/oneDNN#1539]
Hi,

Is Post op associated with conv and matmul primitive are internally implemented at micro kernel level?
By micro kernel, i mean if post op computation is fuse d as soon as o/p element is ready even in Out register/ L1/L2 cache.
This is sometime called pure fusion 
Or 
First primitive computation happens on i/p, o/p buffer get prepared in first pass,  and second pass does the post op calculation like activation or element wise operation?

Thanks in advance.

**Comment by dzarukin** [comment]
Hi @avinashcpandey, the purpose of post-ops is to save memory cycles, otherwise the fusion doesn't fulfil its purpose. oneDNN implements eltwise and binary post-ops on registers (at micro-kernel level as you say so) when the result is ready to be processed. Thank you.

**Comment by rjoursler** [comment]
@avinashcpandey The answer to this depends on the implementation which gets dispatched. In most primitive implementations, the post-ops are fused and calculation happens on the first pass before writing the output from register into memory. This is not the case for all implementations. In some cases ([such as some matrix multiplies on GPU](https://github.com/intel-innersource/libraries.performance.math.onednn/blob/a93bf4ff55f7ac57cb1d5e8510b7d14aa5f9ee6f/src/gpu/ocl/gemm/gemm_with_post_ops.cpp#LL220)), post-ops are calculated in a second pass over the data. This can be necessary in some scenarios which have limited parallelism. In that case, problems may divided so that multiple threads operate on the the same output memory. In this case, post-ops must be evaluated after accumulation on the output is completed.
