### ISSUE TITLE
The meaning and thinking of est_eff() in brgemm

### ISSUE THREAD

**Issue by llxingkongxia** [oneapi-src/oneDNN#1564]
Hi,  How to understand the est_eff() function in[ jit_brgemm_conv_utils.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_brgemm_conv_utils.cpp)，and the meaning of "oc_block_eff、brgemm_microkernel_eff、sp_eff 、job_eff 、ur_eff 、cache_eff 、brgemm_eff".  Could you please provide references to relevant papers? Thanks

**Comment by kwiersch** [comment]
Hi @llxingkongxia, this function estimates the efficiency of a set of blocking parameters that will be used in brgemm-based convolution implementation. Some parts of the efficiency calculation relate to the brgemm kernel (`brgemm_microkernel_eff`, `ur_eff`, `brgemm_eff`), and others relate to the efficiency of the driver (`oc_block_eff`, `sp_eff`, `job_eff`, `cache_eff`). Here's a brief description of some of these:

- `brgemm_microkernel_eff`: efficiency of register blocking. In general we want as dense compute as possible. The product `ocblock * ur` represents the number of accumulation registers and is proportional to the number of multiply-accumulate instructions per iteration of the microkernel, whereas the sum `ur + ocblock` represents the number of input registers and is proportional to the number of loads.
- `ur_eff`: efficiency of spatial unrolling factor. We do not want small tails, especially if spatial size is small (since tails have bigger impact in such cases).
- `oc_block_eff`: efficiency of output channel block size (block size of output channels per call to brgemm). Ideally we want something that will evenly divide the total number of output channels.
- `sp_eff`: efficiency of spatial block size, similar to oc_block_eff.
- `job_eff`: estimate of the threading efficiency (how well the work splits into the available threads)
- `cache_eff`: estimate of cache efficiency based on expected data placement during execution

I am not aware of any relevant papers for these internal heuristics of the brgemm kernel, but there is a paper about the batch-reduce GeMM approach more generally: https://arxiv.org/abs/1906.06440.

Tagging @ankalinin in case he has something to add.

**Comment by llxingkongxia** [comment]
@kwiersch thanks, The meaning of parameters is relatively clear at present,  There are some questions about this code? If the dimensions are small and allcore is selected, performance may deteriorate. Is there any way to avoid these situations? or automatically select the appropriate number of threads.

**Comment by kwiersch** [comment]
Yes, there are several ways to address those types of situations. As you mention, one way would be to adjust the number of threads, but that can sometimes lead to other performance problems (for example, changing the number of threads used in different parallel regions in OpenMP can lead to overhead if the runtime changes the thread pool size). Another way is to adjust the block sizes to take into account the overhead of parallelization, and let extra threads spin-wait if there is not enough work. Do you have some specific model or convolution shapes in mind?

**Comment by llxingkongxia** [comment]
Hi kwiersch, sorry for the late reply, I used a simple test, such as mb1ic16ih14oc16oh14kh3ph1n, The performance of allcore is worse than that of 8core, I read code of adjust_thread_count in [gemm_driver.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/gemm/gemm_driver.cpp)，It can adapt to the number of threads, and it is possible to achieve similar functionality in brgemm.  By the way, What is the meaning of brgemm_eff. Thanks

**Comment by llxingkongxia** [comment]
Can you help me analyze the cache_eff parameter in detail?
for example:
    l++;
    const auto inp_ur = inp_w(ur, kw_block);
    loop[l].src.set(inp_ur * simd_w, 1, bcast_simd);
    loop[l].dst.set(0, 1);
    loop[l].wei.set(oc_block, 1);

For loop src:

itersize = inp_ur * simd_w
repeatn = 1
overlap = bcast_simd;

itersize might mean: The amount of data moved，inp_ur * simd_w
repeatn might mean: Repeat 1 time
overlap might mean: Because it is broadcast, bcast_simd is overlapped several times.

![image](https://user-images.githubusercontent.com/14210127/225235447-cf597019-8ed9-4992-b1ff-2f0241e85dc4.png)

But can't understanding loop dst and wei,  dst is related to ur/ow/sp,  Why itersize = oc_block in wei.

Could you help analyze it? Thank you

**Comment by kwiersch** [comment]
The variable `brgemm_eff` is meant to take into account the efficiency of the spatial block and spatial unroll sizes. Specifically, we want to have `ur` not too small and `sp_block` to be much larger than that (if cache efficiency allows it). The "squeeze" function is basically there to normalize the efficiency in a way that moves it closer to 1.

It sounds like you have a pretty good understanding of the loop terms. For the `itersize` of `wei`, it is `oc_block` as it is counting the size of data used during innermost loop of kernel, where we have a series of small GeMMs of size `ur` by `ic_block` by `oc_block` (see figure below). I think `overlap = bcast_simd` is there to capture the fact that during reduction we broadcast 1 4-byte value from src at a time, but a sequence of those will come from the same 64-byte cache line. But note that `ic` is not the vectorization dimension, so in your picture the zmm's your drew will hold a single value that has been broadcasted or copied from the same value in memory. The vectorization dimension is `oc`, and the fundamental compute unit will be a fused-multiply-add on the broadcasted src data with a full vector of weights data for the same `ic` index but `simd_w` different `oc` indices.

![image](https://user-images.githubusercontent.com/36455077/226087438-092c9f40-00dc-476a-821d-e63f7d477bfd.png)
