### ISSUE TITLE
Error when build oneDNN with Arm Compute Library 19.08

### ISSUE THREAD

**Issue by Airbala** [oneapi-src/oneDNN#1575]
Hi, for some reasons, I want to build oneDNN with ACL 19.08, but the latest version of oneDNN doesn't support ACL 19.08, so I choose oneDNN 2.0 and oneDNN 1.7. But unfortunately when I build with ACL 19.08, I meet with some errors. Could you please help me with this problem?
![image](https://user-images.githubusercontent.com/39217135/222885229-b05452b1-cf97-4bb5-80b0-6a7bda67b664.png)
![image](https://user-images.githubusercontent.com/39217135/222885245-7929762b-cba1-446b-a90e-3058cc6afedf.png)

**Comment by nSircombe** [comment]
Hi @Airbala,

ACL kernels were first integrated into oneDNN with https://github.com/oneapi-src/oneDNN/pull/820, following discussion on this RFC - https://github.com/oneapi-src/oneDNN/pull/795.

This integration work was done with ACL 20.x releases, since then there have been a number of fixes and enhancements in both ACL and oneDNN, which has resulted in breaking changes which have required the assertion of a minimum ACL version (see https://github.com/oneapi-src/oneDNN/commit/79f0a0eb14be6906aaafae4b23d90876016fc4e1). It's strong recommended to use the latest supported version.

In hindsight, It may have been a good idea to enforce a minimum ACL version from the start.

...essentially, there's no support for ACL versions prior to 22.x in any oneDNN release - I recommend you move to a newer version.

**Comment by nSircombe** [comment]
@Airbala - could I ask why you're interested in Compute Library 19.08 in particular, and what would block a move to a more recent release?

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional information.
