### ISSUE TITLE
How to choose the proper kind brgemm

### ISSUE THREAD

**Issue by gengoks** [oneapi-src/oneDNN#1613]
Hi, I notice that there are several implementations in brgemm like brgemm, brgemm_amx_uker, brdgmm. Could you help explain the difference between these several kinds of implementation and how to make a decision about the dispatch among them?

**Comment by kwiersch** [comment]
Hi @gengoks, thanks for your interest in brgemm! Can I ask you to share your motivation for learning about the implementation details? For example, is it for general education, or do you have a specific use in mind?

Also, let me preface the following with a DISCLAIMER: the brgemm API is an internal API that is under active development and is subject to change without notice.

As you noted, there are three different kernel implementations for brgemm kernel. The kernel that is created by [brgemm_kernel_create](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/brgemm/brgemm.hpp#L135) depends on how the brgemm descriptor is initialized. There are two types of brgemm operations:

1. batch reduce general matrix multiply (brgemm), initialized via [brgemm_desc_init](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/brgemm/brgemm.hpp#L64)
2. batch reduce diagonal matrix multiply (brdgmm), initialized via [brdgmm_desc_init](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/brgemm/brgemm.hpp#L98)

Type 1 is an extension of the ubiquitous GEMM operation to include a "batch reduce" feature as mentioned in https://arxiv.org/abs/1906.06440. Type 2 is a specialization for the diagonal matrix multiplications that appear in depthwise convolutions. For type 2, there is a single kernel implementation (`jit_brdgmm_kernel_base_t`) that will be selected automatically during kernel creation. For type 1, there are two implementations:

1. brgemm_kernel_common_t (and it's many descendants): this is the more generic kernel that supports more ISAs.
2. brgemm_amx_uker_t: this is a kernel specifically for Intel AMX instructions that includes additional unrolling and interleaving to achieve best performance.

By default, the common kernel is selected. A hint can be provided to the brgemm implementation that unrolled AMX kernel is desired: if `brgemm_attr_t::use_uker` is set to true in the call to [brgemm_desc_set_attr](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/brgemm/brgemm.hpp#L127), the unrolled kernel will be selected if AMX instructions are supported.

**Comment by gengoks** [comment]
@kwiersch Thanks for your detailed reply and it helps me a lot! I need to write some dl kernels for unpublished hardware and am conducting a survey about how to generate an efficient DL operator. I have several further questions about the brgemm:
1. For the brdgmm, is it correct to regard it as a dot product operation but include the batch reduce feature? And what optimization do you do for such a special gemm?
2. For the general brgemm, does it have the most efficient shape like `32x32x32`, `64x64x64`? Or I just need to call it no matter how large the matrix is. For example, `C(4096x4096) = A(4096x4096) x B(4096x4096)`, which one will have better performance, call `brgemm(4096,4096,4096)` directly or build some outer loop then `call brgemm(32,32,32)` repeatly in the body? If I need to build some outer loops, what loop order and tiling size should I choose or are there any factors and heuristic I need to consider?
3. For the interleave optimization in brgemm_amx_kernel, does the brgemm interleave the memory load and dot product or interleave post-op and dot product? As far as I know, the xeon cpu should have a not small out-of-order buffer and the hardware should be able to issue those instructions without conflict at the same time. Why does the brgemm still need such optimization?

**Comment by kwiersch** [comment]
That sounds interesting, thanks for sharing! Let me try to answer next questions:

1. No, brdgmm does not really perform a dot product. It's more like tying the K and N dimensions together so that each K index corresponds to one and only one N index (thus, the B matrix becomes diagonal). So the main optimization here is that we pass the B dimension to brdgmm as a vector of diagonal elements, whereas with brgemm we would have to pass a full matrix for B (even though only the diagonals are non-zero). This is useful for depthwise convolutions.
2. There are definitely shapes that perform better than others, but it really will depend on the exact hardware being run on. Also, note that brgemm is just the kernel, and for larger problems we will likely need to decompose a problem between threads. It's a really complex problem to get optimal threading and blocking decompositions. You can take a look at the code in `jit_brgemm_conv.cpp`, `jit_brgemm_inner_product.cpp` and `jit_brgemm_matmul.cpp` to get some ideas about how to do this decomposition.
3. It's interleaving the tile dot products (Intel AMX instructions) and vector post-processing instructions (Intel AVX instructions). I think the reason we need to interleave these in the kernel and not simply rely on the out-of-order engine is mainly that the post-processing instructions cannot begin until the AMX compute is complete. Then, once they begin, they fill the pipeline for many cycles before the next set of AMX compute instructions might be decoded and run. So by interleaving them in the kernel, we can help the CPU core to begin the next set of AMX instructions sooner.

**Comment by gengoks** [comment]
I get it and it helps me a lot! Thank you so much for your patience and detailed reply!
