### ISSUE TITLE
in place reorder

### ISSUE THREAD

**Issue by WilliamTambellini** [oneapi-src/oneDNN#1669]
# Summary
Precise in the doc if reorder is safe to use inplace, where src mem = dst mem

# URLs
https://oneapi-src.github.io/oneDNN/dev_guide_reorder.html#doxid-dev-guide-reorder

# Additional details
In General notes, just state if it is safe to reorder in place:
```
...
    auto reorder_prim = reorder(reorder_pd);
    reorder_prim.execute(engine_stream, src_mem, src_mem);

```
best

**Comment by dzarukin** [comment]
Hi @WilliamTambellini, my two cents:
1. In-place means (potentially) different memory descriptors but same memory handle. In this sense reorder is NOT a safe in-place operation.
2. It's hard to find any sense in doing in-place reorder to the nature of the operation.

**Comment by WilliamTambellini** [comment]
Tks @dzarukin 
1 If inplace reorder not safe then you should throw/error out in 1dnn src code that it is not supported/safe: "dest memory must differ from source memory". As today (3.0.0), it runs and making the user assume it is safe. 
2 Makes sens to reorder inplace (for instance ba to ab layout) in order to avoid a mem allocation/copy of a full tensor.
Makes sens?

**Comment by dzarukin** [comment]
For (1) the policy is opposite - if it's not documented it's allowed, then it's disallowed. oneDNN doesn't throw to let users decide what to do with the library errors and doesn't do check on memory pointers to figure if handles are identical or not to preserve the generality.

I don't share the enthusiasm regarding (2) since this is a huge assumption that reorder would use in-place friendly algorithm to do transposition. In general case an additional memory would be required to perform transposition which makes it same memory-consumption-wise with out-of-place version but harder implementation-wise. On top of that, oneDNN provides excessive API to pass whatever format into the primitive to let it handle the case accordingly.

If you observe issues with performance in certain cases that `ba` has to be passed instead of `ab` for better performance, this is a separate discussion and will require data to continue it.
