### ISSUE TITLE
Why choose the direct convolution?

### ISSUE THREAD

**Issue by FollowHeart007** [oneapi-src/oneDNN#1716]
Hi~~I have been using oneDNN to accelerate convolution computations on x86 CPUs recently. I noticed that on CPU, oneDNN performs direct convolution instead of the more general im2col+gemm method or the Winograd algorithm, which can reduce the algorithmic complexity. I am very curious about the reasons behind this approach.
Thanks.

**Comment by vpirogov** [comment]
Hi @FollowHeart007,

oneDNN uses one of three [convolution algorithms](https://oneapi-src.github.io/oneDNN/v3.0/dev_guide_convolution.html#algorithms) depending on the hardware and user settings:
1. Direct
2. Implicit GEMM (im2col+gemm)
3. Winograd

Direct algorithm is the most commonly used as you noticed because it typically results in the best performance results on modern hardware. The implicit GEMM algorithm requires extra memory and additional memory-bound operations and used only to fill the gaps in cases where direct algorithm implementation is not available. Winograd algorithm has lower accuracy and dispatched only when explicitly allowed with `dnnl::algorithm::convolution_auto` or `dnnl::algorithm::convolution_winograd`.

**Comment by MrJungle1** [comment]
@vpirogov Hello, as you said, when I specify convolution_winograd
![企业微信截图_17058187961169](https://github.com/oneapi-src/oneDNN/assets/43968255/f35cc26e-2d10-40e8-9885-88633ff467c5)
unimplemented appears on x86 cpu. 
![企业微信截图_17058186879256](https://github.com/oneapi-src/oneDNN/assets/43968255/a3b0d64e-fed6-4bbc-8773-ce3a8165d86c)
I would like to ask if oneDNN will not run winograd on x86 cpu now.
![企业微信截图_17058188675454](https://github.com/oneapi-src/oneDNN/assets/43968255/eafa5481-c945-4102-b830-0723ba806a66)

**Comment by vpirogov** [comment]
No, there are no benefits in running Winograd convolution on x86 CPUs currently, so the implementation was removed.
