### ISSUE TITLE
Expected Multi-Threaded CPU Performance

### ISSUE THREAD

**Issue by jkbeavers** [oneapi-src/oneDNN#1746]
Hi 1dnn team,

I was hoping to get some confirmation or guidance about some behavior I'm seeing when running a separate network per thread. Specifically, for an 4 physical core machine with hyperthreading, I'm running inference on a network 8 times over 8 threads with independent data in each and with `OMP_NUM_THREADS=1`.

When comparing the speed when I run the same network once on a single thread I see a significant drop in performance. One particular matmul that changes drastically is shaped 1x2x512 * 1x512x30000 -- this is seen to be about 2.5x as slow in the multithreaded case.

I've seen this with `ONEDNN_ENABLE_MAX_CPU_ISA=OFF`, but am mostly interested in the following cases I've observed

- AWS c6 (3rd gen Xeon) with f32 and avx2, avx512
- AWS c7 (4th gen Xeon) with f32, bf16 and avx512, amx

To note, I've been looking at the speed reported from a higher level homebrew profiler, but also via the time reported by the `exec` onednn verbose log.

### Repro
I could spawn separate threads executing a matmul from a single executable and provide that here, but I found a simple way that seems to have the same effect even if it isn't 100% equivalent:
Spawn benchdnn 8 times in the background with shell script using
`OMP_NUM_THREADS=1  ./benchdnn --mode=P --matmul --dt=f32 --stag=abc --wtag=abc --dtag=abc  1x2x512:1x512x30000`
Some effect can also be seen starting with 4 instances.

### Ideas on Cause
I initially thought that this may be due to a lack of the appropriate settings for thread affinity, but wasn't able to consistently change the overall performance or the speed of the aforementioned matmul by using openmp options.

My leading theory is that this is a consequence of downclocking due to the usage of these wide operations (avx, avx512, amx). That said, I've seen similar behavior when disabling the max cpu isa and just using the `gemm` matmul, which has given me some hesitation about this theory as I would expect that implementation to not have the same issue.
**Focusing on c6 with 8 threads or 8 bench dnn processes, I see the slowdown with gemm, avx, avx2, avx512, but only with avx512 do I see the frequency of all by cores drop from the all-core turbo clock speed of 3.5 GHz down to just under 3.3 GHz. This gives me some confirmation, but seeing the speed drop with the non-avx512 cases without a clock speed drop confuses me a bit.**

### Closing Questions
A final point of reference is that I've seen an implementation using [Eigen's tensor module](https://eigen.tuxfamily.org/dox/unsupported/group__CXX11__Tensor__Module.html) provide similar speeds when comparing that matmul with a single threaded and mulithreaded situation.

1. So, is this speed drop when using 8 (application) threads more of a consequence of oneDNN's matmul implementation than the frequency scaling?
2. Are there any other things I should be considering that could be a root cause?
3. Based on this behavior it seems that oneDNN isn't suited to multithreading at the application level and should instead only make use of threading from the cpu backend/OpenMP -- is that correct?

**Comment by dzarukin** [comment]
Hi @jkbeavers, based on the piece of information you've provided I can do the following conclusions:
- `./benchdnn --mode=P --matmul --dt=f32 --stag=abc --wtag=abc --dtag=abc  1x2x512:1x512x30000` problem is memory bound. Activations occupy 4 KB (a single memory page), but weights occupy 58.5 MB. There's (almost) no data re-use so it boils down to the system bandwidth.
- Even c7 instances have at most 120 MB of L3 cache per socket. I have certain level of confidence that AWS instance doesn't provide such high amount of L3 cache, and it's likely 1/7 or 1/8 piece from total size.
- Just speculative math gives us 8 HT * 58.5 MB = 470 MB to run over ~15 MB of L3 cache **concurrently** (which means that when M=2 is computed, the data for weights may not be in cache already, and it has to be brought back from RAM).
- For a bandwidth limited GeMM problem a plain C code would perform as fast as best compute-optimized code, there's nothing one can do about.
- If frequency goes down, it also decreases RAM and caches speed, thus, slower execution. Keep in mind that Hyper-threads only makes the situation worse since compute resources are not helping to compute faster.

I can't imagine why M=2 for the cases of interest, but if you seek for guidance, I can suggest to cut 30000 significantly in pieces (e.g. in 1000), this will let data at least stay in L3 until the problem is done computing. Alternative is to concatenate M over threads and feed a single GeMM to the full system, M=16, K=512, N=30000, any of those approaches will be more efficient ways to manage GeMM. Thanks.

**Comment by WilliamTambellini** [comment]
Tks @dzarukin 
Apologies. Our use case here is really a single process but multi threaded inference with sharing of the weights between threads. For such inference, the speed is good considering there is only 1 weight tensor  not too big for the L3 cache.
Now regarding:
"I have certain level of confidence that AWS instance doesn't provide such high amount of L3 cache, and it's likely 1/7 or 1/8 piece from total size."
Would you have any docs/hints/evidences ?
Kind
WT

**Comment by dzarukin** [comment]
@WilliamTambellini There's no docs, just the observation how virtualization returns nodes of hardware to the user, and it obviously does it in equal pieces. If 8-core node from 56-core socket is given to the user, they can expect roughly 200 MB * (8 / 56) of L3 cache. On practice it may or may not lead to performance problems but simply saying, the user doesn't have any control whether the other 8-core node given to the other user will occupy the cache or not. Stability-wise it comes to the same socket loading from other nodes it was split to.

In case you have control over a problem decomposition, I highly recommend to rely only on L2 just to get stable results.

**Comment by jkbeavers** [comment]
Thanks for the insights @dzarukin ! I just want to follow up as I’ve answered my original question after looking again recently.

With some tangents about the effect of frequency scaling, my original question was: are there any implications or gotchas when using onednn for task parallelism.
When running a network independently over multiple threads with that GeMM above, I was seeing a drop in perf when compared to the single threaded case. All GeMMs — even smaller ones — would be slower on average, but some would be as fast as the single threaded case and others would be much slower.
Using `perf` I saw a bunch of time was spent in 
OpenMP synchronization routines and tracked it down to the inclusion of `pragma omp barrier` when using a build of onednn with the `OMP` runtime.

Switching to the sequential runtime significantly improved the speeds and made them much more stable. Of course we have the memory bound GeMMs that are not ideal, but getting good perf in this case is a good step.

Hopefully this information is useful for any others with a similar use-case. I might submit a patch for a small doc addition sometime later.

Thanks again for the great library!
