### ISSUE TITLE
Use of use_buffer_b pointer in brgemm matrix multiplication

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#1776]
Dear team, 
I have following doubts:
1. Is buffer_b is scratchpad which is cache memory which is used to speed up the calculations?
2. How use_buffer_b as in function at https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/matmul/brgemm_matmul_utils.hpp#L213  is used while copying data from data pointer to buffer b pointer?
3.  Where exactly data is copied into buffer_b and again it is read from buffer_b in the code?

**Comment by igorsafo** [comment]
Hi @vineel96 ,

An additional buffer B is a way to change the layout of memory B at execution implicitly to speedup computations. However comparing to the cachhing, this procedure happens each execution because oneDNN primitives do not have state (for example, to support multi-threading execution). The feature is an implementation detail, so it might be used in some implementations but can be ignored by others.

Here is the algorithm:
1. **(Answers your question 1)** brgemm initialization function `init_brgemm_matmul_conf` initializes `use_buffer_b` using the method you pointed at: https://github.com/oneapi-src/oneDNN/blob/d68912d9745a5abb895612caf935b0e1242136bb/src/cpu/x64/matmul/brgemm_matmul_utils.cpp#L1128  Depending on Matmul/brgemm configuration an additional buffer for matrix B `buffer_b` is either required or not.
2. If `buffer_b` is required:
    1. An additional scratchpad memory is registered so at execution either user or the library will provide this buffer: https://github.com/oneapi-src/oneDNN/blob/d68912d9745a5abb895612caf935b0e1242136bb/src/cpu/x64/matmul/brgemm_matmul_utils.cpp#L1473
    2. Brgemm strides are updated because when B is copied into scratchpad the copy routine could change leading dimensions or the layout in general: https://github.com/oneapi-src/oneDNN/blob/d68912d9745a5abb895612caf935b0e1242136bb/src/cpu/x64/matmul/brgemm_matmul_utils.hpp#L236-L244
    3. An additional kernel `copy_B_kernel_` is created. It is responsible for copying matrix B into the scratchpad buffer: https://github.com/oneapi-src/oneDNN/blob/d68912d9745a5abb895612caf935b0e1242136bb/src/cpu/x64/matmul/brgemm_matmul.cpp#L219
    4. **(Answers your question 2 & 3)** Each matmul execution data from B is copied into `buffer_b` using kernel `copy_B_kernel_` as part of `copy_b_chunk_in_buffer`: https://github.com/oneapi-src/oneDNN/blob/d68912d9745a5abb895612caf935b0e1242136bb/src/cpu/x64/matmul/brgemm_matmul.cpp#L314-L315
    5. Compute kernel uses the scratchpad memory `buffer_b`: https://github.com/oneapi-src/oneDNN/blob/d68912d9745a5abb895612caf935b0e1242136bb/src/cpu/x64/matmul/brgemm_matmul.cpp#L1113

**Comment by vineel96** [comment]
Hi @igorsafo,
Thank you very much for the answers.
1. In brgemm_matmul_copy_utils.cpp, copy_16_x_n_block(), compute_k_loop() and generate() functions are also used for buffer_b ? If they are used, how each function is responsible in creating buffer_b?
2.  Also what is significance of EVEX_compress_addr() function in the copy_16_x_n_block() function?

**Comment by igorsafo** [comment]
1. `create_brgemm_matmul_copy_b` itself does not copy the matrix B, it **generates** a JIT kernel responsible for copying matrix B at `primitive::execute()`.
2. `jit_brgemm_matmul_copy_b_f32_t::generate()` contains all JIT code for the copy routine. `copy_16_x_n_block()` and `compute_k_loop()` are parts of this copy routine, so they are called within `generate()`. For example, `copy_16_x_n_block()` emits instructions responsible for the copying (`vmovups` instructions). The result of `generate()` is a code generated at runtime (Just-In-Time) that will be executed at `primitive::execute()` and will be destroyed later. Comparing to a regular code, JIT code lives on heap (is allocated via `mmap`) so profilers/debuggers might not see this code. Please read the following page: https://oneapi-src.github.io/oneDNN/dev_guide_inspecting_jit.html This will help you to dump binary code for the copy routine to inspect it later.
3. Oh, this is a good question! As far as I remember `EVEX_compress_addr()` was introduced as an optimization for Xeon Phi family of processors, the reason was that if an instruction `vmovups` has an immediate offset bigger than `0x200` then instruction encoding will be increased which will result in bigger code size. This should be useful for any avx512-capable CPU, but it is not required, so `vmovups(zmm_src, EVEX_compress_addr(reg_src, i * src_stride_))` can be safely replaced by `vmovups(zmm_src, ptr[reg_src + i * src_stride_])`

**Comment by vineel96** [comment]
Thank you for the answers.
I have been trying porting matmul for aarch64 machine, where when we enable use_buffer_b, we are getting 0's as output for all input shapes, when we dont enable use_buffer_b, its giving non zero output.
Can you suggest what might be the reason that is causing zero output?

**Comment by igorsafo** [comment]
> Thank you for the answers. I have been trying porting matmul for aarch64 machine, where when we enable use_buffer_b, we are getting 0's as output for all input shapes, when we dont enable use_buffer_b, its giving non zero output. Can you suggest what might be the reason that is causing zero output?

I see, thanks for the details. There are at least the following possible issues:
- Please make sure you initialize contexts correctly for copy and compute kernels. In onednn contexts are used to pass arguments (which contain memory pointers to data) between primitives. Primitive itself has a context with all arguments passed by a user. For example, brgemm matmul implementation then should take these arguments and pass to the context of copy kernel and brgemm kernel:
  - Init `brgemm_ctx` based on primitive `ctx`: https://github.com/intel-innersource/libraries.performance.math.onednn/blob/cec7b41fc4686272a8dec123cb0c871093da3d9c/src/cpu/x64/matmul/brgemm_matmul.cpp#L261
  - Init copy routine `ctx` based on `brgemm_ctx`: https://github.com/intel-innersource/libraries.performance.math.onednn/blob/cec7b41fc4686272a8dec123cb0c871093da3d9c/src/cpu/x64/matmul/brgemm_matmul.cpp#L665
- Please make sure in case of `use_buffer_b` copy routine is invoked. In addition as I explained before you can inspect that JIT code for copy routine to make sure it is correct. If it is not correct it could copy into wrong memory so `tr_src` still contains zeros after copy kernel.

In general, I would recommend you to reduce size of matmul to something like 4x4x4 or even smaller, fill weights and sources by some dummy numbers like `1, 2, 3, ...` and check the data prior to kernels execution, in-between and after to see where the issue comes from.

**Comment by vineel96** [comment]
Thanks for insights @igorsafo.
