### ISSUE TITLE
accuracy issue in a graph conv test

### ISSUE THREAD

**Issue by Mchenr** [oneapi-src/oneDNN#1793]
I run this test in an AArch64 machine that enable sve256, and failed. 
![image](https://github.com/oneapi-src/oneDNN/assets/49141541/08ea4b46-36f9-466b-8670-5164ef5eb187)

I notice the comment report a accuracy issue in AArch64. I want to know what causes the accuracy issue and why to use dnnl_cpu_isa_avx in the if statement. Has the test the same accuracy issue regardless instruments?
![image](https://github.com/oneapi-src/oneDNN/assets/49141541/8fa936ee-5230-4ef6-b1bf-a97d5370a93f)

oneDNN version is v3.3.3, and I get value is 7 from dnnl_get_effective_cpu_isa() method.
![image](https://github.com/oneapi-src/oneDNN/assets/49141541/15cd81d9-2957-4fcc-8555-751a86fcd32f)
@TaoLv

**Comment by TaoLv** [comment]
Hi @Mchenr, I don't know why the slight accuracy issue on these platforms. Possibly it's due to how mish or tanh is calculated.
The check of `dnnl_cpu_isa_avx` is used here to relax the check on Intel Sandy Bridge CPU (SNB as mentioned in the code comments) which only supports AVX. The case is tested on other Intel CPU platforms and runs into the `else` branch when AVX2 and above ISA is supported.

**Comment by Mchenr** [comment]
thanks for your answer!
