### ISSUE TITLE
create memory with tag::any，it crash

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1795]
hi, when i create a memory with tag::any, but with tag::nchw is ok.the app is crashed for windows, the version of oneDNN code is 3.3.4; the code of eg at above:

    for (int n = 0; n < num_src; ++n) {
        //auto md = memory::desc(src_dims, dt::f32, tag::nchw);
        auto md = memory::desc(src_dims, dt::f32, tag::any);
        //auto mem = memory(md, engine);
        memory mem = memory(md, engine);
        // Write data to memory object's handle.
        write_to_dnnl_memory(src_data.data(), mem);

        src_mds.push_back(md);
        src_mems.push_back(mem);
    }
![Uploading 图片.png…]()

**Comment by feixuedudiao** [comment]
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/6505f16f-abb7-471a-972e-8e36806bce08)

**Comment by igorsafo** [comment]
Hi @feixuedudiao !
Creating a memory based on a memory descriptor with tag `any` is illegal, because `any` means memory descriptor doesn't have any particular layout in memory. A memory descriptor with tag `any` is only meant to be passed to a primitive descriptor so oneDNN has information that it can choose the optimal memory layout (versus computing an operation on a user's layout, for example, nchw). Once such primitive descriptor is created the user should query the new memory descriptor from oneDNN, it will contain a particular memory layout (strides, dimensions, etc.) and user can use it to create a memory.
Here is an example: https://github.com/oneapi-src/oneDNN/blob/main/examples/primitives/convolution.cpp

A memory descriptor is created with tag `any` for source so oneDNN can choose the optimal layout:
https://github.com/oneapi-src/oneDNN/blob/4c87e74ea0c453d78a1a759b08dede8dab24d4ee/examples/primitives/convolution.cpp#L116
This memory descriptor is passed to convolution primitive descriptor:
https://github.com/oneapi-src/oneDNN/blob/4c87e74ea0c453d78a1a759b08dede8dab24d4ee/examples/primitives/convolution.cpp#L138-L141
The memory descriptor is queried from the conv primitive descriptor and an additional buffer is created and user's memory is reordered into this buffer if user's memory layout is different from the one requested by oneDNN:
https://github.com/oneapi-src/oneDNN/blob/4c87e74ea0c453d78a1a759b08dede8dab24d4ee/examples/primitives/convolution.cpp#L153-L156

This mechanism is only used by compute  primitives like convolution, matmul, inner product. The rest operations can only work on the layouts set by users (they do not support creation based on memory descriptor with tag `any`).


To avoid segfault you should put oneDNN calls into "try catch" to properly handle exceptions thrown by oneDNN as it most likely happened in this case.
