### ISSUE TITLE
OneDNN graph APi for LLM generation

### ISSUE THREAD

**Issue by sreelekshmyanil** [oneapi-src/oneDNN#1947]
I am trying to run gpt j 6b with generation way (model.generate). But I am facing error - AttributeError: 'RecursiveScriptModule' object has no attribute 'generate'
But this works for conventional way ( like model(input))

Does onednn graph api supports generate type?

flag used for bf16 - 
        torch._C._jit_set_autocast_mode(False)
        torch.jit.enable_onednn_fusion(True)

**Comment by sanchitintel** [comment]
Hi @sreelekshmyanil, TorchScript has been deprecated, and we haven't tried running GPT-J with it.

You could try running it with `torch.compile`, which is PyTorch's replacement for TorchScript based graph compilation solution.
It doesn't use oneDNN Graph at this point, but supports several other fusions. You could also try using [Intel Extension For PyTorch](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/llm.html), which also has several other optimizations for LLMs such as quantization & kv-cache.

**Comment by sanchitintel** [comment]
Hi @sreelekshmyanil, was your code in line with the Intel Extension for PyTorch documentation?

**Comment by sanchitintel** [comment]
`ipex.optimize` should not be used when oneDNN Graph has to be used with Intel Extension for PyTorch (which, BTW, is only officially supported for int8).

Also, Intel Extension for PyTorch also supports some other fusions that don't leverage oneDNN Graph.

**Comment by sreelekshmyanil** [comment]
@sanchitintel 

I am not using IPEX. What I am trying to run is - 

# Disable AMP for JIT (for bf16)
torch._C._jit_set_autocast_mode(False)

# To enable onednn graph api
torch.jit.enable_onednn_fusion(True)

input_ids = tokenizer(prompt, return_tensors="pt").input_ids
model = torch.jit.trace(model, input_ids, check_trace=False, strict=False)
model = torch.jit.freeze(model)

output = model.generate(input_ids)

error is generated when I use model.generate().

_AttributeError: 'RecursiveScriptModule' object has no attribute 'generate'_

**Comment by sanchitintel** [comment]
> I am not using IPEX. What I am trying to run is -

Sorry, but you also commented -

> I am just experimenting with llm on ipex and using torchscript+onednn fusion to see the performance and differences. But onednn doesn't seems to be not working with model.generate

So, my comments on Intel Extension for PyTorch were distinct from my comments on using native PyTorch.
Besides, I also noticed you had opened a separate issue in the Intel Extension for PyTorch GitHub repository.

> AttributeError: 'RecursiveScriptModule' object has no attribute 'generate'

As for the issue you reported, it's related to the technical limitation of TorchScript, and would happen irrespective of whether or not you enable oneDNN Graph with `torch.jit.enable_onednn_fusion(True)`, and is thus orthogonal to oneDNN Graph. Since TorchScript has been deprecated in PyTorch, the issue probably wouldn't be fixed. You could try opening a PyTorch GitHub issue for it, though.

However, there's a workaround you could try, and I'd recommend using Intel Extension for PyTorch instead of native PyTorch if you'd insist on using TorchScript - https://github.com/intel/intel-extension-for-pytorch/blob/dev_demo/examples/cpu/inference/python/LLaMA2/LLaMA2%20inference%20int8-bf16.ipynb

Please replace `ipex._optimize_transformers` with `ipex.llm.optimize` in that code. API reference is [here](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/api_doc.html).
You'd have to look up how to generate a prequantized GPT-J based on the comments in that Jupyter notebook (which are for LLaMA2). Please not that you'd have to use Intel Xeon SP 4th generation processors, as they natively support `AVX512_BF16`, `AMX_BF16` & `AMX_INT8` ISAs. While Intel Xeon SP 3rd generation Cooper Lake (distinct from Ice Lake SP, which is also Xeon 3rd gen) also supports `AVX512_BF16`, AFAIK, public cloud providers such as AWS, GCP & Azure don't have Cooper Lake based machines but do have instances with Sapphire Rapids processors. For example, m7i instances on AWS use Intel Xeon 4th generation processors. Since you were using BFloat16, I'm guessing you were already using such a machine. You could also use int8 static quantization (instead of also using BF16 with AMP alongside int8 static quantization, could be termed `int8-fp32` instead of `int8-bf16`) with Intel Xeon SP 2nd gen & above, but you're likely to see better performance with Intel Xeon 4th gen SP, as it has `AMX_INT8` ISA.

That being said, please try exploring non-TorchScript paths with Intel Extension for PyTorch as well, based on its documentation.
Please not that Intel Extension for PyTorch can be thought of as a staging ground for new features (that improve performance on Intel hardware) geared towards landing in native PyTorch. 

Thanks!
