### ISSUE TITLE
Bnorm tests are mistrusted on aarch64

### ISSUE THREAD

**Issue by Ryo-not-rio** [oneapi-src/oneDNN#1973]
# Summary
When running `./tests/benchdnn/benchdnn -v5 --bnorm --tag=axb --dir=FWD_I --flags=G,GR --attr-post-ops=relu:0.5,linear:3.4:5.0+tanh --inplace=true,false mb1ic19id4ih6iw6nbnorm_3d:2` on aarch64, 2 of the 8 tests are mistrusted.

The same occurs when running with `--skip-impl=acl` with the simple:any kernels being run, which suggests the cause to be outside of acl.

# Version
v3.6.0 (commit 094cc1dda4a24ccf0a54987a34c4475e00a926f9)

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model aarch64 graviton
           flags: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lr
                        cpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs paca pacg dcp
                        odp svei8mm svebf16 i8mm bf16 dgh rng
* OS version - 20~22.04.1-Ubuntu
* Compiler version - 11.4.0

# Steps to reproduce
Run `./tests/benchdnn/benchdnn -v5 --bnorm --tag=axb --dir=FWD_I --flags=G,GR --attr-post-ops=relu:0.5,linear:3.4:5.0+tanh --inplace=true,false mb1ic19id4ih6iw6nbnorm_3d:2` 

# Observed behavior
`tests:8 passed:6 skipped:0 mistrusted:2 unimplemented:0 invalid_arguments:0 failed:0 listed:0`

# Expected behavior
`tests:8 passed:8 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0`

**Comment by dzarukin** [comment]
Hi @Ryo-not-rio, this is rather a benchdnn filling peculiarity rather than an issue. The `mistrust` status just tips that there are more zeros in the output than it should, but the benchmark decides what the number of zeros is expected. It can be treated as passed, it's a suggestion for developers to look into the problem as 100% of zeros can be in the output and it would be impossible to say if the test actually verifies the functionality.
