### ISSUE TITLE
DNNL_TEST_SET NIGHTLY produces duplicate benchdnn tests

### ISSUE THREAD

**Issue by jondea** [oneapi-src/oneDNN#1993]
# Summary
When you configure and build with `cmake -DDNNL_TEST_SET=NIGHTLY ..`, then you get duplicate benchdnn tests. For example, just looking at matmul
```
> ctest -N
...
  Test #245: test_benchdnn_modeC_matmul_all_cpu
  Test #246: test_benchdnn_modeC_matmul_bf32_bf16_cpu
  Test #247: test_benchdnn_modeC_matmul_bfloat16_cpu
  Test #248: test_benchdnn_modeC_matmul_bfloat16_ymm_cpu
  Test #249: test_benchdnn_modeC_matmul_float16_cpu
  Test #250: test_benchdnn_modeC_matmul_int8_cpu
  Test #251: test_benchdnn_modeC_matmul_multidims_cpu
```
`test_matmul_all` contains all of these except `test_matmul_bfloat16_ymm` and `test_matmul_multidims`. And there are a few cases in `test_matmul_all` which are not covered by the separate ones.

There is logic [here](https://github.com/oneapi-src/oneDNN/blob/511d36a8bac01ff54bb929be8699907e2a84d7d4/tests/benchdnn/CMakeLists.txt#L205) to filter out some of the `test_*_all` but not all of them (e.g. matmul).

What's the ideal resolution to the double testing here? My naive view before I found this logic was that `test_matmul_all` was the largest set of things we care about. But I understand that there's a robustness to running on every file we find (only excluding specific ones).

Also, do any other teams use `DNNL_TEST_SET=NIGHTLY`? Or do they do something for their most thorough testing? Previously we had been running `./benchdnn ... test_*_all` manually, is this the correct thing to do?

# Version
oneDNN v3.6 latest main (30354d471e48ab240ab475fd99875b91491869f1)

# Environment
On C7g (AArch64) however the logic appears to be architecture agnostic.
CMake log
```
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- The C compiler identification is GNU 10.5.0
-- The CXX compiler identification is GNU 10.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: AARCH64
-- DNNL_LIBRARY_NAME: dnnl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE)
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.7")
-- Found Sphinx: /usr/bin/sphinx-build (found version "sphinx-build 1.8.5")
-- Found Git: /usr/bin/git (found version "2.25.1")
-- Enabled testing coverage: NIGHTLY
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Enabled GeMM kernels ISA: ALL
-- Primitive cache is enabled
-- Graph component is enabled
-- Graph compiler backend is disabled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jondea01/oneDNN/build
```

**Comment by dzarukin** [comment]
Hi @jondea, those are very good questions. In ideal situation we do want to have two `test_` files which are basically entry points for CI and Nightly kinds of validation. However, it got a little off due to the way internal infrastructure works and hardware availability which dictated to test new features on simulators which are slow and don't let to cover the full scope. That was the primary reason different test_***_DT files appeared.

Internal (and hopefully future external) infrastructure runs each `test_` file on a separate machine, that's why to avoid the fattest file running on a single machine given subfiles are covered, some `_all` files are excluded from testing targets, but not all of those, as you mentioned.

`_all` file MUST contain all the inputs, if it doesn't it's either intended (but should be documented) or a bug. I can take a look what's going on with matmul.

My recommendation would be the following:
* In case you run validation on a single machine, `_all` file is the best choice. It will have all the coverage.
* In case you can split runners of `test_` files between machines, I'd suggest to stick to targets from ctest (which follow the aforementioned logic).

It's a little bit messy the way testing coverage is organized now, but it gets pushed away due to lower priority to keep it neat and clean. I'd love to implement a filter based on arbitrary arguments, starting with data types and get back to a single file practice, but I have no idea when it may happen. Basically, `"--filter=dt(includes only)f32 --batch=test_driver_all"` which would skip everything but f32 cases from the whole coverage. Semantics might be crazy to define different level of inclusions and exclusions, but... it may solve the original issue.

Hope if clarifies the state.
