### ISSUE TITLE
oneDNN - Build failure

### ISSUE THREAD

**Issue by pthorali** [oneapi-src/oneDNN#2050]
Hi Team, 

We are trying to build https://github.com/oneapi-src/oneDNN into Intel Graphics ( Meteor Lake ). We are unable to build it successfully for any combinations of cmake. Attached screenshot with the errors. 
Are we missing something, could you please guide us on what we should do?

![image](https://github.com/user-attachments/assets/c5839a4b-7753-44f7-9e61-9cc729dad74e)

Thank you,
Preethi Raksha

**Comment by vpirogov** [comment]
Please refer to [Build from Source](https://oneapi-src.github.io/oneDNN/dev_guide_build.html) section of the Developer Guide.

**Comment by shu1chen** [comment]
Hi @pthorali, there are 2 options to build oneDNN with Intel GPU support, one via OpenCL runtime and the other via SYCL runtime. Please ensure that [the software requirements for GPU engine](https://github.com/oneapi-src/oneDNN/tree/main?tab=readme-ov-file#gpu-engine) are in place before building from source.

- Via OpenCL runtime, as @vpirogov already shared, it is `DNNL_GPU_RUNTIME=OCL` instead of `DNNL_CPU_RUNTIME=OCL`:

`CC=gcc CXX=g++ cmake -DDNNL_GPU_RUNTIME=OCL -DOPENCLROOT=/path/to/opencl/sdk ..`

- Via SYCL runtime, [Intel oneAPI DPC++/C++ Compiler](https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler.html) and [oneAPI Level Zero](https://github.com/oneapi-src/level-zero) are required and the compilers are `icx` and `icpx` rather than `gcc`/`g++`:

`CC=icx CXX=icpx cmake -DDNNL_GPU_RUNTIME=SYCL ..`

**Comment by pthorali** [comment]
Thank you for the quick solution, I tried all the suggested methods I was able to install it, but it is not working for gpu. 
![image](https://github.com/user-attachments/assets/801fd1ff-c567-457a-b0c7-f58136412a3b)

We are using Meteor lake GPU, which is not a data center GPU, and the code is not identifying the GPU. 
Could you please let us know how to fix it?

**Comment by pthorali** [comment]
Yes, sycl-ls identifies the device. I have attached the screenshot below 
![image](https://github.com/user-attachments/assets/0e94e25f-66c6-4798-bbf9-eaf214bb66e2)

**Comment by yehudaorel** [comment]
@pthorali, I do not see the GPU device from your screenshot you shared. Somewhere in your systems GPU stack has an issue or is missing, have you setup [gpu drivers](https://www.intel.com/content/www/us/en/support/articles/000005629/graphics.html) properly?

**Comment by shu1chen** [comment]
@pthorali From the command lines, it seems that you are running the workload on Linux platform. Please refer to the webpage [https://dgpu-docs.intel.com/driver/client/overview.html](https://dgpu-docs.intel.com/driver/client/overview.html) to setup client GPU drivers properly. You'll see devices starting with [opencl:**gpu**] or with [ext_oneapi_level_zero:**gpu**] using `sycl-ls`

**Comment by pthorali** [comment]
Thanks you for the instruction, we cloned a new driver and set up the drivers again. Now sycl-ls seems to identify the GPU. [opencl:gpu] or with [level_zero:gpu]

But when we build the oneDNN now, it fails with this error. It is not identifying the icpx. 
![image](https://github.com/user-attachments/assets/b35c3483-07d2-474b-ad10-335d95819db7)

In the one DNN source document as a note to use clang/clang++, what is the syntax to use it or is there any other necessity we are missing?
![image](https://github.com/user-attachments/assets/9c9ebf35-1008-4b91-91c5-2405ee4e3290)

**Comment by shu1chen** [comment]
Hello @pthorali, there are two versions of oneAPI DPC++ Compiler: 

- One is the product version installed from [Intel oneAPI website](https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler-download.html) and has the driver names icx/icpx. For this product version, it is expected to run `export CC=icx` and `export CC=icpx` before running cmake.
- The other is open-source version from the github repo [intel/llvm](https://github.com/intel/llvm) and has the driver names clang/clang++. For this open-source version, it is expected to `export CC=clang` and `export CC=clang++` before running cmake.
- You can use either of them if you plan to compile oneDNN based on **SYCL** runtime. Since you have already installed the product version, please run `export CC=icx` and `export CC=icpx`.

For the error in icpx, the error message in the screenshot is incomplete. Did you build a simple program and verified the compiler by referring to the [Intel® oneAPI DPC++/C++ Compiler getting-started guide](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/get-started-guide/2024-2/get-started-on-linux.html)? If the product version of compiler is not working well, please post a question and attach the full error log in the [Intel compiler community](https://community.intel.com/t5/Intel-oneAPI-DPC-C-Compiler/bd-p/oneapi-data-parallel-c) to get the support.

By the way, does OpenCL runtime work for you? OneDNN with Intel GPU support via OpenCL runtime doesn't rely on the oneAPI DPC++ Compiler and gcc/g++ also works:
`CC=gcc CXX=g++ cmake -DDNNL_GPU_RUNTIME=OCL -DOPENCLROOT=/path/to/opencl/sdk ..`

**Comment by pthorali** [comment]
1. For the **export cc=icx and export cc=icpx**. The OneDnn compilation fails with the below error screenshot after 54% is completed. The same error keeps repeating, I had to kill execution. 
![image](https://github.com/user-attachments/assets/762c9de2-bf0b-4e80-a8c8-c50adc50dd6b)

2. I tried running a simple c++ code with icpx complier and it works as expected. 
![image](https://github.com/user-attachments/assets/b585a55f-5bfa-4ba7-b38b-8c9bc50210a6)

3. When I execute this **CC=gcc CXX=g++ cmake -DDNNL_GPU_RUNTIME=OCL -DOPENCLROOT=/path/to/opencl/sdk ..**  This is the error I get.  
![image](https://github.com/user-attachments/assets/44f7063a-1c8a-4623-b8ac-979ef7989b7a)

The files I source and the script I execute are given below 
**source /opt/intel/oneapi/compiler/latest/env/vars.sh 
source /opt/intel/oneapi/mkl/latest/env/vars.sh 
source /opt/intel/oneapi/setvars.sh**
![image](https://github.com/user-attachments/assets/d44f3000-53e7-42ca-86b9-4af2bb56096a)

Could you please point out the mistake I am doing? Am I missing somethin that the icpx drivers does not work for the benchDnn code?

**Comment by shu1chen** [comment]
@pthorali A possible reason is that you have another version of oneDNN library in the environment (Possibly installed in /opt/intel/oneapi/dnnl/) and the compiler was trying to link that libdnnl.so to benchdnn instead of the newly built one. 
Please don't run `source /opt/intel/oneapi/setvars.sh`, which will add every component installed in /opt/intel/oneapi/ into the running environment. Like `source /opt/intel/oneapi/compiler/latest/env/vars.sh`, you can activate the necessary components by running separate `vars.sh` scripts.

**Comment by pthorali** [comment]
Hi Team, 

Thanks a lot for the help! The above issue is caused due to `make -j` when we tried `make -j8` it worked. I am able to run the benchDnn for both GPU and CPU. 

Thanks,
Preethi Raksha
