### ISSUE TITLE
The version on anaconda is outdated

### ISSUE THREAD

**Issue by nudles** [oneapi-src/oneDNN#391]
Can anyone update the [version on anaconda](https://anaconda.org/intel/mkl-dnn) to the latest version (v0.17)?
Thanks.

**Comment by choronz** [comment]
Any updates on the latest build for release v0.21? Thanks.

The last update was v0.14 (1 year and 3 months ago) from https://anaconda.org/intel/mkl-dnn/files

**Comment by chrishkchris** [comment]
Since #666 is duplicated and closed, I wrote the issue here:
Conda Package for DNNL will be very useful amd helpful, when the others need to build a conda package of their application which depends on DNNL. However, the anaconda cloud only provide very old version mkldnn (e.g. v0.14)
Thank you very much!

**Comment by julioasotodv** [comment]
I believe that there are still no updates on this, right?

**Comment by vpirogov** [comment]
Starting from oneDNN v2.0 binary distribution is [available on Anaconda](https://anaconda.org/search?q=onednn). 

oneDNN is also included into [Intel oneAPI Base Toolkit](https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit.html), which has packages in apt, yum, and docker containers.

**Comment by vpirogov** [comment]
oneDNN packages are now also available via [Conda Forge](https://github.com/conda-forge/onednn-feedstock).
