### ISSUE TITLE
Poor CPU Utilization 

### ISSUE THREAD

**Issue by coreyjadams** [oneapi-src/oneDNN#543]
I am seeing strange behavior running tensor flow with MKL-DNN on a KNL CPU.  There are a number of strange results.

Initially, I was testing single node performance for a model that is relatively large.  It is a variant of UNet, implemented in tensorflow, using tensorflow version 1.13 with mkl-dnn on the backend.  I explored single node performance with a variety of parameters:
 * OMP_NUM_THREADS
 * hyper threads per rank
 * hyper threads per core
 * inter-op-parallelism-threads
 * intra-op-parallelism-threads
 * channels_first vs. channels_last
 * number of ranks per node (with all reduce done using horovod)

For all runs, affinity was set to 'granularity=fine,compact,0,1'.  KMP_BLOCKTIME is set to 0.

I measure performance in several ways.  For most runs, I track images per second as the main metric and compare the steady-state values after the first few iterations.  I don't include time for JIT compilation or model building in tensorflow.

For several runs, I captured the MKLDNN verbose output.  For several runs, I profiled the application with Vtune's advanced hotspots.

Some key takeaways:
* Tensorflow reports the total number of floating point operations is 0.967 TOPs for the graph execution.  This is measured with their profiling tools.
* With OMP_NUM_THREADS at 64, batch_size 1, hyper threads per core = 1, hyper threads per rank = 64, ranks per node =1, I varied the inter-parallelism values:
    * (inter == 1, intra == 64) yields 0.14 Img/s
    * (inter == 2, intra == 64) yields 0.17 Img/s
    * (inter == 3, intra == 64) yields 0.21 Img/s
    * (inter == 4, intra == 64) yields 0.21 Img/s
    * (inter == 4, intra == 32) yields 0.20 Img/s
    * (inter == 4, intra == 16) yields 0.22 Img/s
    * My conclusion here is that this tensorflow intra_op_parallelism_threads is largely irrelevant on CPU compared to inter_op_parallelism_threads, at least at this level of low performance.
 * Increasing the batch size leads to increased Img/s (which is expected) but in a strange way:
    * Batch size of 8, 1 rank per node, (inter == 4, intra == 64), OMP_NUM_THREADS==64, hyper_threads_per_core==1, hyper_threads_per_rank == 64 yields 0.41 Img/s
    * Batch size of 8, 8 ranks per node, (inter == 4, intra == 8), OMP_NUM_THREADS==8, hyper_threads_per_core==1, hyper_threads_per_rank == 8 yields 0.58 Img/s
    * To be clear, the scenario that is doing more work to all-reduce gradients (25M parameters in the network, by the way) is performing **50% better**.

In terms of MKL_DNN verbose output, I compared the channels_first and the channels_last metrics for my baseline of 1 image per rank with the "best" configuration above.  In this case, I report the following:
 * With Channels_last, Img/s is 0.20
    * There were 7755 reorders (517 per iteration ) for a total time of 13.168 s
    * There were 6525 convolutions (435 per iteration) for a total time of 103.5 s
    * Total time reported for ALL mkl-dnn operations if 138.2 seconds (9.2 s/step)
 * With Channels_first, Img/s is 0.11
    * There were 10245 reorders (683 per iteration ) for a total time of 15.17 s
    * There were 6525 convolutions (435 per iteration) for a total time of 87.6 s
    * Total time reported for ALL mkl-dnn operations if 116.4 seconds (7.75 s/step)

Looking at this, I see that channels_first *should* be faster: the total time is shorter by nearly 20%, and the reality is the opposite: channels_first is nearly 2x **slower**.

From here, I profiled with VTune's advanced hotspots to see what each core is doing. I observe significant imbalance between threads:

Channels first:
![image](https://user-images.githubusercontent.com/6619961/63798527-dfcc3b80-c8cf-11e9-9e9b-3fbf7f9fe237.png)

![image](https://user-images.githubusercontent.com/6619961/63798603-068a7200-c8d0-11e9-88b5-d37b9ab82a3c.png)

Channels last:

![image](https://user-images.githubusercontent.com/6619961/63798611-0ab68f80-c8d0-11e9-958b-9bd0dfd97f77.png)

![image](https://user-images.githubusercontent.com/6619961/63798615-0e4a1680-c8d0-11e9-80a3-70a38d6f3799.png)

Finally, I noted that the total number of threads used is not 64, despite exporting OMP_NUM_THREADS=64 in both cases.  In channels_first, I see 385 threads, of which at least 250 are OMP (I suspect 256, but they aren't sorted in vtune ...).  In channels_last, I see 505 threads.

When filter the vtune results in the channels_first scenario (in which 2 threads labeled Master do the bulk of the work) and then sort by core/HW context, I see that **all** of the work of these master threads is on just one physical CPU at high utilization.  In the channels_last scenario, the same sorting (but 4 master threads instead of 2) shows work is shared across 3 CPUS at less utilization each.

This is a long issue but I think it boils down to this:
 1. I don't understand how tensorflow + MKL-DNN is deciding on which core to place which work, and why the work-balance is so poor across cores.
2. I don't understand how the number of threads is determined, nor how I end up with more OMP threads than I have set at runtime (set 64, observe at least 250 + many other non-OMP threads)

### Environment
DNNL includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model: KNL with 64 cores, 192 GB RAM (Running on Theta: https://www.alcf.anl.gov/theta)
* OS version Linux (RHEL 7 equivalent)
* Compiler version gcc 7.3.0
* MKLROOT value /opt/intel/compilers_and_libraries_2018.0.128/linux/mkl

### Actual behavior
See above.

### Expected behavior
I would expect parallelization across cores to be a lot more even.

**Comment by coreyjadams** [comment]
Pinging again, as it's been a week.

I have at least two other users reporting issues like this.

**Comment by louie-tsai** [comment]
@coreyjadams 
thanks for your detailed information on this issue. 
**We will try to reproduce your issues on our environment.**

In the meantime, we want to check if there is any issue among workload parallelism like questions for OpenMP master.
**Would you mind to open KMP log by "export KMP_AFFINITY=verbose" and share us the log?**

Moreover, it is great that you profile the workload by VTune hotspot. Hotspot profiling can give you idea which functions may need to be optimized. 
However, concurrency (v2018)/threading (v2019) profiling will give you more information on parallelism by multi-threading. 
**Can you profile your workload again by concurrency/threading profiling type?** 
Please make sure to check  the "Analyze OpenMP regions" checkbox.

thanks

**Comment by vpirogov** [comment]
@louie-tsai, any updates?

**Comment by louie-tsai** [comment]
@coreyjadams 

Hi Corey,

sorry for the late response.
As our email discussion, we saw that couple different openmp regions cause this performance degradation with openmp imbalance issue.
![issue](https://user-images.githubusercontent.com/21761437/66241121-2a9d5800-e6b3-11e9-92d0-56cec7ae47b5.png)

Let us double check which code regions create those openmp regions and then think about possible improvement.

thanks

**Comment by louie-tsai** [comment]
Hi Corey

For multiple OpenMP regions in the workload, we saw different OpenMP regions compete each other among CPU resources from below VTune result.  The purple and orange marks are below to different openmp regions, and both of them may need CPU resources around the same time.

![Capture8](https://user-images.githubusercontent.com/21761437/66523106-eb507c00-eaa3-11e9-993a-4e0f7b6491e4.PNG)

To reduce imbalance issues in openmp region, we need to reduce competitions among openmp regions.

In the meantime, let me also try to answer below questions from you.

_1. I don't understand how tensorflow + MKL-DNN is deciding on which core to place which work, and why the work-balance is so poor across cores._

**Tensorflow will create Openmp master threads in a openmp regions according to the number of inter_op_parallelism, and related openmp worker threads will be created according to the number of intra_op_parallelism or OMP_NUM_THREAD env variable.  
How the openmp worker threads and master threads are executed among CPU cores depends on how you set the OpenMP granularity.
If you set granularity=fine,compact,1,0, each thread should bind to a CPU core.** 

**You can have more than 1 OpenMP master thread, but it will be better to put each OpenMP master thread in different NUMA node.
For example, below VTune result from the workload have two OpenMP master threads.**

![Capture10](https://user-images.githubusercontent.com/21761437/66523447-dc1dfe00-eaa4-11e9-915e-59c85449f889.PNG)

**From OpenMP logs, two OpenMP master threads are on different NUMA nodes.**

![Capture_omp_lstopo](https://user-images.githubusercontent.com/21761437/66523455-dfb18500-eaa4-11e9-88c3-4c0652f1a7a2.PNG)


_2. I don't understand how the number of threads is determined, nor how I end up with more OMP threads than I have set at runtime (set 64, observe at least 250 + many other non-OMP threads)_

**The reason why you have more than 64 OpenMP threads is because you have multiple OpenMP regions. If you have 4 OpenMP regions, you will have 64 x 4 openmp threads because each of OpenMP region creates 64 threads.**

Let me know if you still have confusions for above two questions**
