### ISSUE TITLE
Gemm like interface for bf16

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/oneDNN#671]
# Summary
A sgemm/dgemm style interface that accept bf16 (short?) pointers and do gemm in bf16 data type.

# Problem statement
If we have matrix multiplication interface without the need of memory description we could avoid tensor type transform in PyTorch. Which is cumbersome in current status quo.

# Preferred solution
Same as gemm. Function name could suggest it is doing bf16 gemm.

**Comment by rsdubtso** [comment]
MatMul primitive is the recommended interface for bf16 gemm.

**Comment by emfomenk** [comment]
Hi @CaoZhongZ,

Would it be possible for PyTorch to have the following [helper code](https://gist.github.com/emfomenk/4bdc70908cc5c30ad2a97e5030a22eaf), that provides bf16 gemm-like interface using matmul primitive? The code is fairly trivial, so don't expect any burden on supporting it on the FWK (or maybe ideep) side...

The upside of suggested approach:
- Could easily be extended to support post operations and even bias;
- Doesn't require lots of resources, since gemm kernels are generated and kept statically for the entire life of oneDNN library
- While our internal GEMM API supports only bf16bf16**f32** combination, the proposed approach supports bf16bf16**bf16** case as well.
- Approach can be extended (adopted) to support other engine kinds and run times.

The downside of the approach:
- Currently there is a limitation, that beta needs to be known at primitive creation time. I made it a template parameter, if you only interested in beta = 0 and, say, 1. If you need to support arbitrary beta, we can extend our sum post-op with runtime parameter as well to cover this case.
- There is some overhead on creating memory descriptors and memories before actual matmul call. Should be negligible though.

**Comment by CaoZhongZ** [comment]
I see, makes sense.
