### ISSUE TITLE
Plans for unimplemented reference implementation of the packed SGEMM?

### ISSUE THREAD

**Issue by nSircombe** [oneapi-src/oneDNN#678]
#515 covers the failure of packed GEMM tests, and the implementation of checks to return `mkldnn_unimplemented` if passed packed data.

However, this commit: https://github.com/intel/mkl-dnn/commit/5bc2f6090b6bebb186715abd7a907cdd380c42d2 effectively turns these tests back into failures. 

Are there currently any plans to provide a work-around for this missing reference implementation? I can understand there's little argument for an isa-agnostic packed interface.

For context, I'm looking at AArch64 builds, and options for basic validation on AArch64 (see https://cloud.drone.io/nSircombe/mkl-dnn for example - I intend to raise a separate issue to discuss this). At the moment I have to revert the above commit to pass the test suite, hence why I'd like to know if a reference implementation is being developed, and if it's worth considering reverting the change above in the meantime?

**Comment by emfomenk** [comment]
Hi @nSircombe,

There is no plan to have a reference version of packed gemm -- as the main idea is to get performance. Do I understand correctly that gemm is the only test that currently fail?

I think, the simplest solution for now will be to add a check to the corresponding gtest:

``` patch
diff --git a/tests/gtests/test_gemm_common.hpp b/tests/gtests/test_gemm_common.hpp
index 27b0e5dde..67beaed59 100644
--- a/tests/gtests/test_gemm_common.hpp
+++ b/tests/gtests/test_gemm_common.hpp
@@ -1233,6 +1233,9 @@ protected:
         bool pack = (p.pack_params.pack_a || p.pack_params.pack_b);
         SKIP_IF(get_test_engine_kind() == engine::kind::gpu && pack,
                 "GPU does not support packed GEMM.");
+#ifndef DNNL_X86_64
+        SKIP_IF(true, "Only x64 CPU supports packed GEMM");
+#endif
         SKIP_IF((p.alpha != 1.f || p.igemm_params.oa() != 0
                         || p.igemm_params.ob() != 0)
                         && pack,
```

In the long term, I think we need to have this macro defined by cmake (rather than by `src/common/utils.hpp`) into `1` on x64 and `0` otherwise. In this case the patch would actually be more neat:

``` patch
diff --git a/tests/gtests/test_gemm_common.hpp b/tests/gtests/test_gemm_common.hpp
index 27b0e5dde..67beaed59 100644
--- a/tests/gtests/test_gemm_common.hpp
+++ b/tests/gtests/test_gemm_common.hpp
@@ -1233,6 +1233,9 @@ protected:
         bool pack = (p.pack_params.pack_a || p.pack_params.pack_b);
         SKIP_IF(get_test_engine_kind() == engine::kind::gpu && pack,
                 "GPU does not support packed GEMM.");
+        SKIP_IF(!DNNL_X86_64, "Only x64 CPU supports packed GEMM");
         SKIP_IF((p.alpha != 1.f || p.igemm_params.oa() != 0
                         || p.igemm_params.ob() != 0)
                         && pack,
```

Also, in theory, we could try to make a fallback for packed gemm to not pack the matrices, but rather pick 'N' or 'T'. That would be a more universal solution, as RNN, IP, and MatMul would continue working fine. However, this is much more intrusive change...

**Comment by emfomenk** [comment]
Hi @nSircombe,

Sure, please go ahead! Thanks!

**Comment by nSircombe** [comment]
PR submitted - #685.
