### ISSUE TITLE
Performance of the dilated conv

### ISSUE THREAD

**Issue by lisa0314** [oneapi-src/oneDNN#681]
When I run `deeplab_mobilenetv2_513.tflite` and `deeplab_mobilenetv2_513_dilated.tflite` models for semantic_segmentation using DNNL for inference. Compared  with non-dilated conv, I found that when dilate = 1 the performance enhancement of the dilated conv is almost invisible. However, much more greater performance improvement appears when dilate = 4.
 Is this a normal phenomenon for DNNL? I expect the performace improvement could be better when dilate = 1.

**Comment by rsdubtso** [comment]
Hi @lisa0314. Thanks for the report. Please post a verbose log and hardware details so that we can reproduce this. Also please try running the convolutions of interest using benchdnn and post performance here.

**Comment by lisa0314** [comment]
- Hardware
CPU: 3.4 GHz Intel Core i5
memory: 16 GB 2400 MHz DDR4
-Software
macOS 10.14.6

There are some pairs of comparative data:
- Dilate = 1

1. `dnnl_verbose,exec,cpu,convolution,jit_dw:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:Abcde8a:f0 bia_f32::blocked:a:f0 
dst_f32::blocked:aBcd8b:f0,,alg:convolution_direct,mb1_g384ic384oc384_ih28oh28kh5sh1dh0ph2_iw28ow28kw5sw1dw0pw2,0.109131` (dilate = 0)
2.

**Comment by rsdubtso** [comment]
Thanks. Since these are depthwise convolutions they are very much affected by bandwidth and how often the accessed the data is in cache (which may still happen when applying the convolution kernel).

Nonetheless, on my machine (Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz, Ubuntu 19.10 in a VM, OMP_NUM_THREADS=2), I see better numbers ([google spreadsheet](https://docs.google.com/spreadsheets/d/1dy0qegV7com8i-6tvG2aHE2Epd6Ig27j5y4rpOTCgig/edit?usp=sharing)). The following chart (sorry for the poor picture quality) shows ratios of convolutions above with and without dilation.

![image](https://user-images.githubusercontent.com/15225631/78957037-045cd880-7a99-11ea-87be-33a7cf9a036b.png)

So I can confirm that my measured performance ratios of DNNL convolutions with and without dilation (the red line) are lower then theoretical ratios when (the blue line), but without running some profiling on your side, it is hard to tell why your numbers (the yellow line) are even lower: there are a lot of factors.

**Comment by lisa0314** [comment]
@rsdubtso thanks for your sharing data! I will try to find out the gap root cause.
