### ISSUE TITLE
small error when compiling with DNNL_VERBOSE turned off

### ISSUE THREAD

**Issue by zulma46** [oneapi-src/oneDNN#701]
Hi,

When compiling the latest commit in the master branch I get an error when DNNL_VERBOSE is turned off. It's something that's easy to fix:

in verbose.cpp line 130
```
#if defined(DISABLE_VERBOSE)
void pd_info_t::init(const primitive_desc_t *) {}
```

should be:
```
#if defined(DISABLE_VERBOSE)
void pd_info_t::init(engine_t *, const primitive_desc_t *) {}
```

thanks

**Comment by rsdubtso** [comment]
Confirmed. Broken in 57a98fb6de4b6b9773f70343eba864098c634ab9.

**Comment by emfomenk** [comment]
Hi @zulma46,

Thanks for the report. We will fix the issue soon.

But regardless of that, may I know why you build oneDNN with `VERBOSE` off? Is it because of the slowdown in primitive creation? I want to note that we recently (in DNNL v1.3) made verbose lazy-initialized, so if you don't set `DNNL_VERBOSE` to 1 or 2 you won't observe any perf differences.

**Comment by zulma46** [comment]
Hi,

Yes, I turned `VERBOSE` off for performance reasons. I wasn't aware this is no longer necessary.
Thanks for letting me know.

**Comment by emfomenk** [comment]
Yeah, there was a bunch of micro optimizations made to accelerate primitive descriptor creation. The commit that made verbose initialization lazy is 9d5e7671eb4bc6e496560bd5f658fbff647562a3.
