### ISSUE TITLE
unable to create concat primitive error 

### ISSUE THREAD

**Issue by pranathibl** [oneapi-src/oneDNN#704]
Hi,

I am facing "could not create a concat primitive descriptor" error when any of the inputs is nChw16c format and output data format is any. (using MKLDNN v1.0)

I have attached the setup to reproduce this issue - 
[depthConcatenation_dataFormat.zip](https://github.com/oneapi-src/oneDNN/files/4487824/depthConcatenation_dataFormat.zip)

Could you let me know, why this is seen?

Thanks,
Pranathi

**Comment by dzarukin** [comment]
Hi @pranathibl, thank you for reporting the issue.

The thing is that version 1.0 had a defect when concat was requested on a source with blocked channels format not multiple of block size (like in the reproducer: block size is 16 but there are only 8 channels) + different format for a second source.

Here are available options to work around the issue:
1) Update MKL-DNN to, at least, 1.1 version, the issue was fixed there.
2) Switch blocked format from nChw16c to nChw8c - but this one will work only as long as a blocked dimension has number of channels divisible by block size as mentioned earlier.
3) Use plain nchw format for the first source input instead of blocked one.
4) Use same blocked as for source 1, meaning additional reorder.

My guess will be though blocked format comes from convolution which likely makes (2) unlikely a solution, but plain format for second input likely can be reordered in the same format (4).

By the way, is it intentional to use old MKL-DNN version instead of the latest one available online which is 1.3?

Thanks.

**Comment by vpirogov** [comment]
@pranathibl,

I would suggest to switch to the latest relesed version (v1.3) as of now if possible. It's fully API compatible with v1.0 and includes all the latest optimizations and bug fixes.
