### ISSUE TITLE
oneDNN TensorFlow int8 notebook

### ISSUE THREAD

**Issue by RushivArora** [oneapi-src/oneDNN#750]
Hello,

I am running the int8_inference notebook using the oneapi-cli in devcloud. For some reason it says it can't find the module tensorflow in the notebook (but runs perfectly well in the terminal). Could i get some help with this?

Thank you!

**Comment by vpirogov** [comment]
Hi @RushivArora,

This seems to be related to the Jupyter notebook. Please submit your question to [AIKit samples github](https://github.com/intel/AiKit-code-samples/tree/master/TensorFlow_int8_Inference).

+@louie-tsai

**Comment by vpirogov** [comment]
Hi @RushivArora,

You are getting errors in Jupyter notebook likely because the notebook uses default kernel. When running a Jupyter notebook that uses Tensorflow you need to select `Tensorflow (AI kit)` kernel. 

![Capture](https://user-images.githubusercontent.com/19210288/84409286-11de2e00-abc2-11ea-99a9-829280de7f2a.PNG)

**Comment by RuoshArora** [comment]
That solved it! Thank you so much! @vpirogov
