### ISSUE TITLE
make install issue in linux while compiling WRF

### ISSUE THREAD

**Issue by SHANTIKUMARI12345** [oneapi-src/oneDNN#775]
[shanti@master2 netcdf-4.1.3]$ make install
Making install in include
make[1]: Entering directory `/home/shanti/BUILD_WRF/LIBRARIES/netcdf-4.1.3/include'
make[2]: Entering directory `/home/shanti/BUILD_WRF/LIBRARIES/netcdf-4.1.3/include'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/netcdf/include" || /usr/bin/mkdir -p "/netcdf/include"
/usr/bin/mkdir: cannot create directory ‘/netcdf’: Permission denied
make[2]: *** [install-includeHEADERS] Error 1
make[2]: Leaving directory `/home/shanti/BUILD_WRF/LIBRARIES/netcdf-4.1.3/include'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/shanti/BUILD_WRF/LIBRARIES/netcdf-4.1.3/include'
make: *** [install-recursive] Error 

#BELOW IS THE ATTCHEMENT OF CODE I RUN PLEASE IMPROVE THIS AS I AM NEW TO THIS 
![Screenshot (8)](https://user-images.githubusercontent.com/51417834/87120107-50d4d180-c29d-11ea-8b9c-da52dab77549.png)

**Comment by igorsafo** [comment]
Hi @SHANTIKUMARI12345 , It looks like you have an issue with [netcdf](https://github.com/Unidata/netcdf-cxx4) library. Moreover the issue itself is due to lack of access rights on your machine. User 'shanti' doesn't have permissions to create a directory in '/' directory. If fixing this will not help you to build netcdf please create an issue in the relevant product repository ([netcdf](https://github.com/Unidata/netcdf-cxx4)).

Closing this issue because it is not relevant to oneDNN. Feel free to reopen or create another one in case you have a question related to oneDNN.

**Comment by SHANTIKUMARI12345** [comment]
THANKS
