### ISSUE TITLE
Is engine/stream thread safe and/or cheap to create?

### ISSUE THREAD

**Issue by thefacetakt** [oneapi-src/oneDNN#779]
Hi. I want to use onednn (v0.14 for now, so, actually, mkldnn) for executing different convolutions in different threads.
I am using AlexNet example (https://github.com/oneapi-src/oneDNN/blob/v0.14/examples/simple_net.cpp) as a reference and would like to minimize overhead.

So my questions are:

1) Does it make sense to share engine/stream across different executions, or are they negligently cheap to create?
2) If yes, can we share them across different threads, or each thread should use separate engine/stream?
3) What is "index" parameter of engine? Can i create several engines with same index? Is it somehow beneficial to use engines with different indices?

**Comment by emfomenk** [comment]
Hi @thefacetakt,

Since Intel MKL-DNN v0.14 was only about CPU, let me answer assuming you are interested in CPU implementation only.
Engine and streams are cheap to create.
- For CPU, engine is almost an empty object that contains the references to the (static) list of the implementations. So, you can recreate or share (across multiple threads in particular) -- the effect would be the same.
- In old days, stream took the primitives you are about to run. With that respect it was not thread safe. But just in case of engine, it is nothing more than just a `std::vector<>` that would take the primitives you are about to submit. Feel free to recreate it. In fact, many framework integrations simply created a stream, submitted there one primitive, and destroyed the stream immediately after. For simplicity this is a preferable mode.

---

Off-topic. v0.14 is quite old. I feel obligated to suggest you to switch to the newer version :)
Though, we broke the API compatibility when switched from v0.21 (the last of v0.x version) to v1.x.
Just in case, you can find the migration guides here:
- [v0.x -> v1.x](https://oneapi-src.github.io/oneDNN/dev_guide_transition_to_v1.html)
- [Intel MKL-DNN v1.0 -> DNNL v1.1](https://oneapi-src.github.io/oneDNN/dev_guide_transition_to_dnnl.html), that is just about the renaming, no semantic API changes.
