### ISSUE TITLE
Issue about RELU implemented in example cnn_inference_f32.cpp

### ISSUE THREAD

**Issue by JasonGuo98** [oneapi-src/oneDNN#831]
# Summary
I tried to use **relu** implemented in oneDNN, and I referred to the example code `cnn_inference_f32`. But when I print the result of relu, the numbers do not change.

# URLs
Below is where I looked up: 
https://oneapi-src.github.io/oneDNN/cnn_inference_f32_cpp.html. 
The defination of relu is here:
https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html.

# Additional details
To fix this issue is easy, just change `const float negative1_slope = 1.0f` to `const float negative1_slope = 0.0f`

**Comment by emfomenk** [comment]
Hi @JasonGuo98,

Could you please elaborate on what exactly the issue is? 

oneDNN ReLU (sometimes called also Leaky ReLU) supports an alpha parameter that specifies the negative slope. Just as you mentioned the documented behavior is in the [documentation](https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html).

The example states however it implements AlexNet topology, which is not completely correct as the original paper uses ReLU with negative slope 0. Is this what the issue about?

**Comment by vpirogov** [comment]
Looks like the point is that ReLU with negative slope 1.0 is an identity function and does not affect the computations. So for example to have a little more sense something different from 1.0 would be preferable.

**Comment by emfomenk** [comment]
Indeed :) Well, this will also make the topology more AlexNet-like.
