### ISSUE TITLE
Forward Direct Convolution Algorithm in oneDNN

### ISSUE THREAD

**Issue by OliverScherf** [oneapi-src/oneDNN#833]
Hello,

I try to understand the inner workings of the direct convolution algorithm that is implemented in oneDNN. Lets take the AVX2 version as a example.

[jit_avx2_conv_kernel_f32.cpp](https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp)
[jit_avx2_conv_kernel_f32.hpp](https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.hpp)

I already understood that oneDNN is using a vectorized layout. With AVX2 it's NCHW8c. The most inner part of the convolution  is JITed in [Line 402](https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L402) onwards.

Solely from the code (generated) it's hard to grasp the design choices and details.

I looked for papers, but I couldn't find the specific one. In [this paper](https://arxiv.org/pdf/1808.05567.pdf) they presented a direct convolution which is implemented in libxsmm. This one is similar but still different.

Can anyone give more insights or perhaps a paper describing the implementation details?

Thanks!

EDIT: I already found the [Convolution Dev Guide](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html)

**Comment by emfomenk** [comment]
Hi @OliverScherf,

Unfortunately we don't have any documents that describe the internal implementation of the convolutions and other primitives. However, the paper you mentioned is a good reference as it covers parallelization, vectorization, and blocking -- the main aspects of getting the good performance.

The `jit_avx2_conv_kernel_f32.{c,h}pp`  you mentioned belong to the convolution micro-kernel, that implements the inner-most loops. The outermost loops are handled by "driver" that can be found here:
- The parallelization happens across these dimensions: https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_convolution.cpp#L86-L87 
- The sequential loop over blocks of input channels: https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_convolution.cpp#L92

> The most inner part of the convolution is JITed in [Line 402](https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L402) onwards.

That's correct. The code there might be hard to comprehend, but this is mostly because of the need to support all corner cases. But for understanding it actually should be enough to focus on the "main" cases. For instance:
https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L421-L432

This chunk handles regular and tailing process for output channel blocking. For simplicity, you can focus on just line 424, assuming that `cmp(reg_oc_blocks, jcp.nb_oc_blocking);` returns `equal`.

Similarly, in https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L353 it is enough to review https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L380-L390 as before and after this main loop the padded area is handled, which is similar to "middle" case, but requires more caution.

> Solely from the code (generated) it's hard to grasp the design choices and details.

I definitely agree that inspecting the generated code is not an option. Better to go through the generator. We try to give proper names for the variables and functions and leave the comments so that it would be possible to see the logic behind the code.

**Comment by sotoflom** [comment]
It's also worth mentioning that most implementation choices -and compute parameters within the JIT'ed block focus around performance. For example, choosing the size of 'ur_w' which stands for unroll-width as seen in this heuristic: https://github.com/oneapi-src/oneDNN/blob/613d2308ed9041b01e9c3cbbd2a974bbec906d38/src/cpu/x64/jit_avx2_conv_kernel_f32.cpp#L590-L623

Some of these heuristics can be intuitive to implement, but others are mostly decided by running performance measurements and then tuning them for optimal performance.

**Comment by emfomenk** [comment]
Closing the issue as the question seems to be addressed.
Feel free to reopen or open a new one if you have further questions.

**Comment by OliverScherf** [comment]
Thanks for the great answers  @sotoflom and @emfomenk. I'll dig into it.
