### ISSUE TITLE
Inner product documentation possibly incorrect w.r.t optimized for memory formats

### ISSUE THREAD

**Issue by alexandrelimassantana** [oneapi-src/oneDNN#865]
The [documentation](https://oneapi-src.github.io/oneDNN/dev_guide_inner_product.html) states the optimized plain memory formats for the _src_ and _weight_ tensors for computation with the inner product primitive.
The documentation states that, for 2D-spatial tensors, when _src_ format is set to NCHW (abcd), the optimized memory for the weights would be OIHW (abcd)

However, if the _src_ tensor is fixed to NCHW (abcd) and the _weight_ tensor format tag is set to any, oneDNN will pick the IHWO (bcda) format for the _weigth_ tensor.

As far as I understand, the calculations should be carried out in a similar fashion because the inner product implicitly flattens the _src_ tensor.
If that's the case, shouldn't the documentation be updated to reflect the library behavior?
If not, shouldn't the library pick the format stated in the documentation to avoid reordering in user-level code?

**Comment by sbogusev** [comment]
Hi @alexandrelimassantana . By providing the *any* layout the library is instructed to pick the optimized memory format given the set of memory descriptors, data types, etc. It may happen that the library will pick a blocked memory format for the weights, or there may be other memory format combination occurring here. Therefore the table you are referring to is intended for users who wish to provide a *plain* memory format, which is also mentioned in the paragraph right before the table:
~~~
The table below shows the combinations for which plain memory formats ...
~~~

Use of optimized *any* layouts for weights (and/or data) tensor is discussed in the previous paragraph.

I hope I have understood your question correctly.

**Comment by alexandrelimassantana** [comment]
Hello @sbogusev you did understand the question correctly, thanks for the response.

Is there a reference, or documentation of some sort that would help me understand how the library picks up the optimized formats?
I am looking forward to implementing some primitives and I feel like this part of the process is a little obscure in the user-level documentation (for good reason).

**Comment by sbogusev** [comment]
Hi @alexandrelimassantana . On a higher level the logic of picking the optimized memory format by the library is not complicated, it's all about the details.

Primitives in oneDNN (both on CPU and GPU) are implemented in multiple ways (aka implementations) to enable higher performance for a particular [ISA](https://en.wikipedia.org/wiki/Instruction_set_architecture), tensor data type, and some other parameters. For inner product specifically, the list of implementations for CPU is available in [cpu_inner_product_list.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/cpu_inner_product_list.cpp). 

By providing the memory format `any`, oneDNN will use certain heuristics (cost functions) to estimate the optimized memory format. Most of the time, the library will provide a blocked format, such as `nChw8c` for f32 data type on AVX2 ISA since 8 floats can occupy one YMM register. However, depending on the parameters used to create the primitive descriptor the library may decide that it is more beneficial to use something else. 

Each implementation in the above list has its own heuristic/cost function, and these functions are written based on both theoretical estimations and lots of experiments.

For documentation purposes, such information may be unnecessary for the user since there are too many details. Perhaps the most relevant documentation piece is [Memory format propagation](https://oneapi-src.github.io/oneDNN/memory_format_propagation_cpp.html). However feel free to ask any questions you may have on this or other topic.

Great to hear you're interested in using oneDNN, let us know if you hit any issues or something is unclear to you.

Silviu

**Comment by alexandrelimassantana** [comment]
Perfect, this seems like a good direction to follow!
Thanks for your time and keep up the good work :+1:
