### ISSUE TITLE
How is the primitive executed?

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [oneapi-src/oneDNN#880]
Hi, thanks for the library! I am trying to understand how each primitive is executed. It is calling the dnnl_primitive_execute() API. However, I cannot step into the dnnl_primitive_execute() from my IDE. I also tried to comment out all lines within dnnl_primitive_execute(), build, and run again, all codes still work. I am confused and why is the case? Thanks!

**Comment by dzarukin** [comment]
Hi @LiuXiaoxuanPKU, thanks for the question.

In common words, `dnnl_primitive_execute(...)` takes a user's primitive object and user's memory objects. Primitive object was constructed from some primitive descriptor object which was set up for a specific implementation for a requested op. When primitive is constructed, it makes sure the implementation has everything it needs to be able to run including just-in-time kernel generation. Each implementation has method `execute(...)` which takes those memory objects passed by user, takes pointers from them and applies some kernel(s) over these pointers. E.g. https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_convolution.hpp#L120 and https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_convolution.cpp#L64

I'm not sure what was commented but it looks to me that commenting https://github.com/oneapi-src/oneDNN/blob/master/src/common/primitive.cpp#L120 should be enough if DNNL_VERBOSE is not requested and https://github.com/oneapi-src/oneDNN/blob/master/src/common/primitive.cpp#L114 otherwise. This should lead to the fact the kernel will not be applied and user's memory will remain untouched.

Hope it helps, feel free to post follow up questions. Thanks.

**Comment by LiuXiaoxuanPKU** [comment]
Thanks for the reply! I tried to comment out the entire dnnl_primitive_execute() and return dnnl_success directly. The convolution/reshape primitives can still be executed correctly.  I also tried to add some print statements in that function, but none of my modifications is printed.

**Comment by LiuXiaoxuanPKU** [comment]
Hi, are there any suggestions for playing the library? The VERBOSE mode can provide some information, but is it possible to add a print statement at any places I'm interested in and see the output?

**Comment by dzarukin** [comment]
Hi @LiuXiaoxuanPKU,

I've just recognized that this sentence confuses me:
>However, I cannot step into the dnnl_primitive_execute() from my IDE.

Have you tried to build the library in a debug mode?

Regarding the question, I'm not sure what is the purpose of the question overall and not sure how can we help you with it... It would help me if you could be more specific with the question or maybe even post a piece of code you are working with or specifying files and lines from https://github.com/oneapi-src/oneDNN/tree/master/src you are trying to modify to get any effect. Thanks.

**Comment by LiuXiaoxuanPKU** [comment]
Sorry about the confusion... For example, if I add a line to dnnl_primitive_execute() in src/common/primitive.cpp

`status_t dnnl_primitive_execute(const primitive_iface_t *primitive_iface,
        stream_t *stream, int nargs, const dnnl_exec_arg_t *c_args) {
    printf("I am in dnnl_primitive_execute---------------------\n"); // added line
    bool ok = true && !utils::any_null(primitive_iface, stream)
            && primitive_iface->engine() == stream->engine()
            && IMPLICATION(nargs > 0, c_args != nullptr);
    if (!ok) return invalid_arguments;

    exec_args_t args;
    status_t status = cvt_primtive_args(
            primitive_iface->pd()->impl().get(), nargs, c_args, args);
    if (status != status::success) return status;

    stream->before_exec_hook();

    exec_ctx_t ctx(stream, std::move(args));

    if (get_verbose()) {
        double ms = get_msec();
        status = primitive_iface->execute(ctx);
        stream->wait();
        ms = get_msec() - ms;
        printf("dnnl_verbose,exec,%s,%g\n", primitive_iface->pd()->info(), ms);
        fflush(0);
    } else {
        status = primitive_iface->execute(ctx);
    }

    stream->after_exec_hook();

    if (msan_enabled) unpoison_outputs(ctx.args());

    return status;
}
`
And I go to path/to/oneDNN/build, make build and run examples ./examples/primitives-convolution-cpp. The line I added before is not reflected in the output.

**Comment by dzarukin** [comment]
Could you, please, double check that primitive.cpp file was properly rebuilt and included in the library?

$ ./build/examples/primitives-convolution-cpp
Example passed on CPU.

$ # After modification to primitive.cpp
$ ./build/examples/primitives-convolution-cpp
In dnnl_primitive_execute
In dnnl_primitive_execute
In dnnl_primitive_execute
In dnnl_primitive_execute
Example passed on CPU.

These four lines correspond to reorder, reorder, convolution and reorder execute calls. Maybe clean build with modifications would help...

**Comment by dzarukin** [comment]
Closing an issue due to lack of activity. Feel free to re-open or submit a new one in case of additional questions. Thanks you.
