### ISSUE TITLE
Memory layout for conv

### ISSUE THREAD

**Issue by lilyXXliu** [oneapi-src/oneDNN#882]
I am playing with convolution primitive and memory layout on CPU with AVX2  and I have several questions.

(1) If I specify some bad layouts (for example, chwn for both src, and dst) for conv primitive, it is >100x slower than reorder primitive (reorder from chwn to optimal layout nChw8c) + conv on the optimal layout (nChw8c).  It seems the optimal conv is jit:avx2, while the chwn conv is using ref:any. Does the conv implementation choose the algorithm first, then choose the optimal layout with that algorithm?

(2) Are there cases when chwn will have better performance than nchw (or blocked nchw) on CPUs?  What's the motivation for supporting different input/output formats if format_tag::any can always pick a good layout and reorder is not very expensive?

(3) Why ref:any algorithm for conv? From the doc, it seems gemm will be the fallback choice.

Thanks a lot!

**Comment by dzarukin** [comment]
Hi @lilyXXliu, thanks for questions.

(1). Convolutions in the library are optimized for some framework native layouts (nchw-like and nhwc-like) and also for some SIMD-friendly formats (e.g., nChw16c for AVX512_CORE) when it comes to source memory. Most other formats are either corresponding to weights, such as `chwn` which is `ihwo`, either designed for other primitives. Different formats help to reach higher performance for different architectures and types of convolutions.

There are mostly two scenarios: a) user specifies format 'any' for sources and/or weights. Convolution will choose an optimal layout based on some parameters when creating convolution primitive descriptor. User is expected to query a correspondent memory descriptor from primitive descriptor and get best format for sources, for example, and setup a following reorder for the best performance. b) user forces the layout for memory descriptor. In this case, convolution follows user's choice and provides the implementation it supports for a given layout. For layouts different from mentioned in the first part of message, reference convolution will be likely used.

(2). Currently, there are no cases when `chwn` will out-perform `nchw`. And I don't see it changes in the future. The word "support" may be explained from different perspective. If "support" = "work at all", then it's the library commitment that no matter what physical layout user provided, the library will return a correct result. If "support" = "keeping weird tags", this is done to have a name for a physical layout which reorder and all parts of the library understands. Tags are also operated inside the library to limit algorithms applicability and optimizing certain kernels based on knowledge about specific format. Another thing is weights format list is much longer and any weights format can be passed as source memory format, which leads to the issue you observe.

(3). Gemm implementation has it's own limitations as well, such as trivial strides between dimensions, no blocking layout support and some others. Reference, on the other hand, supports all physical layouts since it uses utilities to figure out a physical point location in the memory. Due to it costs much for each point, it makes it really slow but universal in terms of support.

Hope it helps. Thanks.

**Comment by dzarukin** [comment]
Closing an issue due to lack of activity. Feel free to re-open or submit a new one in case of additional questions. Thank you.
