### ISSUE TITLE
Built v2-dev (with NVIDIA support) from source but fails running convolution example

### ISSUE THREAD

**Issue by Dr-Noob** [oneapi-src/oneDNN#888]
# Summary
I build [convolution example](https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/convolution.cpp) with my manually build of the v2-dev library, but fails on both CPU and GPU.

# Version
oneDNN dev-v2 (commit ad5176c)

# Environment
- Intel Xeon Gold. 
- NVIDIA RTX 2080 Ti.
- CentOS 8.2
- clang 12.0: clang version 12.0.0 (https://github.com/intel/llvm 633691327b3f2d6a2a7a8321244682e91db78e7d).

DPCPP Compiler obtained from https://github.com/intel/llvm and built succesfully with:

```
[drnoob@xeon sycl_workspace]$ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda -t release
[drnoob@xeon sycl_workspace]$ python $DPCPP_HOME/llvm/buildbot/compile.py
```
oneDNN library built with the config showed in issue #885 

# Steps to reproduce
I am able to run the example with the library downloaded from [here](https://github.com/oneapi-src/oneDNN/releases/download/v2.0-beta10/dnnl_lnx_1.96.0_cpu_iomp.tgz)
```
[drnoob@xeon examples]$ wget "https://raw.githubusercontent.com/oneapi-src/oneDNN/master/examples/primitives/convolution.cpp"
[drnoob@xeon examples]$ wget "https://raw.githubusercontent.com/oneapi-src/oneDNN/master/examples/example_utils.hpp"
[drnoob@xeon examples]$ export PATH=$DPCPP_HOME/llvm/build/bin:$PATH
[drnoob@xeon examples]$ clang++ -fsycl -std=c++20 -O2  convolution.cpp -I/path/dnnl_lnx_1.96.0_cpu_iomp//include -L/path/dnnl_lnx_1.96.0_cpu_iomp/lib -ldnnl -o conv
[drnoob@xeon examples]$ LD_LIBRARY_PATH=/path/dnnl_lnx_1.96.0_cpu_iomp/lib/:$DPCPP_HOME/llvm/build/lib:$LD_LIBRARY_PATH ./conv cpu
Example passed on CPU.
```

but if I use my hand built library:

```
[drnoob@xeon examples]$ clang++ -fsycl -std=c++20 -O2  convolution.cpp -I/path/oneDNN/install/include -L/path/oneDNN/install//lib64 -ldnnl -o conv
[drnoob@xeon examples]$ LD_LIBRARY_PATH=$DNNLROOT/lib64:$DPCPP_HOME/llvm/build/lib:$LD_LIBRARY_PATH ./conv 
oneDNN error caught: 
	Status: invalid_arguments
	Message: could not create an engine
Example failed on CPU.
[drnoob@xeon examples]$ LD_LIBRARY_PATH=$DNNLROOT/lib64:$DPCPP_HOME/llvm/build/lib:$LD_LIBRARY_PATH ./conv gpu
Segmentation fault (core dumped)
```

# Observed behavior
I am unable to run a simple example with my custom build. Either I have a segfault or a oneDNN error.

# Expected behavior
I expected the library to work as the prebuilt one.

**Comment by densamoilov** [comment]
Hi @Dr-Noob, unfortunately, current oneDNN examples cannot run with CUDA because oneDNN works with USM memory model by default while CUDA can only work with buffers.
However, oneDNN provides an interoperability API (more details in the [doc](https://oneapi-src.github.io/oneDNN/v2/dev_guide_dpcpp_interoperability.html)) that can be used to adapt examples for CUDA.
You may want to try our [performance benchmark](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md) that is adapted to work with CUDA.

As for the oneDNN pre-built binraries, the configuration you used (cpu_iomp) is a classic one that supports only CPU. In general, we do not guarantee that classic oneDNN configurations will work when used with the DPCPP compiler.

**Comment by Dr-Noob** [comment]
That makes sense. 

Thanks for the clarification about the current CUDA limitations. I'll have a look at the TBB problem. 

Closing the issue.
