### ISSUE TITLE
using openMP takes much more time to create convOp

### ISSUE THREAD

**Issue by EstherBlanchett** [oneapi-src/oneDNN#890]
I am using mkldnn V0.21. When I use the openmp, I find it takes more  times to create convOp than I create OP  in signal thread. I want to know if there is any way to reduce the time and why it takes so much time.

**Comment by densamoilov** [comment]
Hi, @EstherBlanchett, since you have not provided the problem sizes it's hard to say for sure why it happens, but my guess is as follows. Some of the oneDNN primitives use JIT compilation approach meaning that the binary code of the kernel is generated during the primitive creation. The generation step mostly utilizes memory bandwidth and hence is memory bound therefore creation of the oneDNN primitives in parallel may not scale.
