### ISSUE TITLE
[RNN] Do the input size and hidden size have to be the same?

### ISSUE THREAD

**Issue by jacobkahn** [oneapi-src/oneDNN#904]
I'm implementing wrappers around several RNN primitives for [flashlight](https://github.com/facebookresearch/flashlight). Right now, I'm trying to get something incredibly basic working — a `vanilla_rnn_forward` op with ReLU.

The parameters I'd like to use with a sample fwd operation are as follows:
```
int num_layers = 2; // number of layers, aka "L"
int hidden_size = 3; // size of the hidden state
int input_size = 4; // aka number of input channels, "C", (also called SLC?)
int batch_size = 5; // "N"
int seq_length = 6; // aka number of time steps, "T"
```

I'm hitting errors before any computation is even run — I'm trying to create memory descriptors with given dimensions for a `dnnl::vanilla_rnn_forward::desc`, but I'm doing something wrong. I've been logging things in [`check_dim_consistency`](https://github.com/oneapi-src/oneDNN/blob/master/src/common/rnn.cpp#L165) since there's no other way to debug errors. In particular, I'm wondering: *is it possible for the hidden state size and the input size to be of different values?* [These assertions](https://github.com/oneapi-src/oneDNN/blob/master/src/common/rnn.cpp#L188-L193) seem to create internal inconsistency if I try to make the input and hidden sizes different. Assume for the sake of this example that this is unidirectional so `dlc_multiplier` is 1. The function makes the following assertions:
1. `DIC == DLC`
2. `SLC == DLC`
3. `SIC == DIC`
4. Since this isn't an LSTM projection, [this line](https://github.com/oneapi-src/oneDNN/blob/master/src/common/rnn.cpp#L181-L182) means that `DIC == DHC`

Transitively, this means that `DIC == DLC == DHC == SLC == SIC`, which precludes hidden size and input size being different.

I think I'm missing something here — some guidance would be great. Thanks for your time.

**Comment by mgouicem** [comment]
Hi @jacobkahn ,
first clarifying the nomenclature. If we look at a single rnn cell, we have the following:
- slc is the size of the input to the cell, coming from the previous layer
- dlc is the size of the output of the cell, will be consumed by the next layer
- sic is the size of the input to the cell, coming from the previous timestep
- dic is the size of the output of the cell, will be consumed by the next timestep

Now back to your example. I assume that you use `slc = input_size` and `sic = dic = dlc = hidden_size`.
In oneDNN we have some restriction on how fusion can happen. Namely, as you quoted from the code and from the [documentation](https://oneapi-src.github.io/oneDNN/dev_guide_rnn.html):
- if L > 1, we require `slc = dlc` (in your case hidden_size == input_size). The reason is mostly because the weights for all the layers are packed into one single tensor, so these weights should have the same dimensions for all the layers.
- if T > 1, we require `sic == dic` (in your case hidden_size == hidden_size). This is for the dimensions to be mathematically coherent, since the same weights_iter are used across the timesteps of a given layer. 

One workaround the first limitation (which is impacting you), is to split the computation into 2 primitives, one for each layer.

**Comment by jacobkahn** [comment]
@mgouicem — thanks for the explanation and clarification. This makes sense.

To generalize what you've said, if I have an input size and hidden size which are different and an RNN which has arbitrarily many layers, the steps to create the primitive will be to:
1. Create the first layer for which `L = 1` so that `slc =/= dlc`.
2. If I have an "effective" `num_layers > 1`, then I'll need to create another primitive which takes the output of the first layer as input. That layer can have `L > 1` (or `L = num_layers - 1`) - that'll perform the computation for the rest of the layers. Since the output of the first layer will be `T x N x hiddenSize`, the following layers will have `SLC == DLC` and that constraint won't be an issue.

Am I thinking about this the right way? Thanks again.

**Comment by mgouicem** [comment]
yes your thinking is right.

**Comment by mgouicem** [comment]
I am closing this issue seems it looks addressed. Feel free to reopen or open a new issue if you have more questions.
