### ISSUE TITLE
the differnence of libdnnl.so & libmdkdnnl.so

### ISSUE THREAD

**Issue by yuqj1991** [oneapi-src/oneDNN#906]
Hi, Bro
when i make the source code ,i find that two libraries, they are libdnnl.so and libmdkdnnl.so.
so what's the difference between them? and which we should to use in our project?

thanks

**Comment by mgouicem** [comment]
Hi @yuqj1991, `libmkldnn.so` is simply here for compatibility and is used by applications that used to link against oneDNN when it was called mkl-dnn. Those two .so files are identical. On linux, libmkldnn.so is simply a symbolic link to libdnnl.so, and on Windows, libmkldnn.so is a copy of libdnnl.so.

In your project, you can link to libdnnl.so, since this is the current name of the library.

**Comment by mgouicem** [comment]
I am closing this issue since it seems it is addressed. Feel free to reopen or open a new issue if you have more questions.
