### ISSUE TITLE
MatMul asymmetric quantization

### ISSUE THREAD

**Issue by affranchi** [oneapi-src/oneDNN#920]
Hello,

I'm testing asymmetric quantization on matmul to understand on version 1.7.0.
I got an error regarding this feature but don't know why it's happening.

```

    dnnl::engine eng{dnnl::engine::kind::cpu,0};
    dnnl::stream engine_stream(eng);
    constexpr int M = 3;
    constexpr int N = 2;
    constexpr int K = 3;
    std::vector<uint8_t> A_u8(M * K, 0);
    dnnl::memory::desc a_u8_md({M, K}, dnnl::memory::data_type::u8, dnnl::memory::format_tag::ab);
    dnnl::memory A_u8_m(a_u8_md, eng, (void *)A_u8.data());
    std::vector<uint8_t> B_s8(K * N, 0);
    dnnl::memory::desc b_s8_md({K, N}, dnnl::memory::data_type::s8, dnnl::memory::format_tag::ab);
    dnnl::memory B_s8_m(b_s8_md, eng, (void *)B_s8.data());
    std::vector<float> C_f32(M * N, 0);
    dnnl::memory::desc c_f32_md({M, N}, dnnl::memory::data_type::s32, dnnl::memory::format_tag::ab);
    dnnl::memory C_f32_m(c_f32_md, eng, (void *)C_f32.data());

    dnnl::primitive_attr matmul_attr;
    int mask = 1 << 1;
    matmul_attr.set_zero_points(
        DNNL_ARG_SRC, mask, {DNNL_RUNTIME_S32_VAL});
    dnnl::matmul::desc matmul_d(a_u8_md, b_s8_md, c_f32_md);
    dnnl::matmul::primitive_desc matmul_pd(matmul_d, matmul_attr, eng);

    int32_t zp_A;
    dnnl::memory zp_A_m({{3}, dnnl::memory::data_type::s32, {1}}, eng);
    int32_t* zp_data = static_cast<int32_t*>(zp_A_m.get_data_handle());
    zp_data[0] = 2;
    zp_data[1] = 4;
    zp_data[2] = 6;

    dnnl::matmul matmul_p(matmul_pd);
    matmul_p.execute(engine_stream,
            {{DNNL_ARG_SRC, A_u8_m}, {DNNL_ARG_WEIGHTS, B_s8_m},
                    {DNNL_ARG_DST, C_f32_m},
                    {DNNL_ARG_ATTR_ZERO_POINTS | DNNL_ARG_SRC, zp_A_m}});
    engine_stream.wait();

```

This code shows the error that

"could not create a primitive descriptor iterator"

I have several questions regarding tests for this feature

- First of all, did I miss something? Don't know why it's complaining. This error is from " dnnl::matmul::primitive_desc matmul_pd(matmul_d, matmul_attr, eng);"
- I tried to put  `matmul_attr.set_zero_points(DNNL_ARG_SRC, mask, zero_points);` but seems it's prohibited from the code here: https://github.com/oneapi-src/oneDNN/blob/master/src/common/primitive_attr.cpp#L94
   Does it mean that we can't use predefined zero points when mask is larger than 0?
- What I understand about asymmetric quantization is that we can use different zero points per axis. For example, if I have [ [ 2,3 ], [ 3,4 ] ] (2x2) matrix, for 0th dimension (row dimension), we can apply different zero points for each row by having [ 1,2 ] zero points. And it would make the 2x2 matrix into [ [ 1,2 ], [ 1,2 ]]. Please, correct me if this is wrong.
- Is there any document to explain about dynamic quantization part? I can find some example regarding static quantization or per-tensor quantization. But seems there is no documentation regarding asymmetric quantzation.

Thanks!

**Comment by dzarukin** [comment]
Hi @affranchi, thanks for all these good questions!

You are not missing anything. I see that documentation doesn't shed a light on actual limitations of zero points in matmul primitive (will update it soon). It, unfortunately, supports only `mask = 0` or just a single, common for whole tensor, zero point as of now. The main reason is that gemm part in matmul is an external for it kernel, and it's impossible right now to make it subtract a value per row (or column). That's why passing mask different from `0` will result in UNIMPLEMENTED, since there's no actual support. And there's no differentiation whether it's a pre-defined zero point or dynamic, both cases support only `mask = 0` case.

BTW, reference implementation could utilize per row mask, but optimized implementations of matmul can't get this feature as I described above, so we decided not to add it.

As for dynamic quantization, could you please check up with https://oneapi-src.github.io/oneDNN/cpu_matmul_quantization_cpp.html? `void quantize(...)` describes the API to apply dynamic quantization and provides some comments. I don't see any issues in the attached code for dynamic quantization besides the point about mask, thus, the memory should contain a single element only. If more question from example comes, feel free to ask them.

In case you are familiar with benchdnn, this line shows it works for `mask = 0` (or `policy = common`):
> benchdnn --matmul --cfg=u8s8s32 --stag=ab --wtag=ab --dtag=ab --attr-zero-points=src:common:2 3x2:2x3
> 0:PASSED __REPRO: --matmul --cfg=u8s8s32 --stag=ab --wtag=ab --dtag=ab --attr-zero-points=src:common:2 3x2:2x3:3x3

While using `policy = per_dim_1` or `policy = per_oc` results in:
> benchdnn --matmul --cfg=u8s8s32 --stag=ab --wtag=ab --dtag=ab --attr-zero-points=src:per_dim_1:2 3x2:2x3
> error [dnnl_primitive_attr* create_dnnl_attr(const attr_t&, const attr_args_t&):804]: 'dnnl_primitive_attr_set_zero_points( dnnl_attr, arg_name, count, mask, values)' -> unimplemented(3)

This is the fastest way to check whether something is supported or not.

Hope it helps. Thank you.

**Comment by affranchi** [comment]
Thank you for your answer. It helps a lot.

I have some following questions.

- Do you have any plan to support individual zero point set for each index soon? It's an important feature for us.
- Is it only MatMul? Then, Convolution and Inner product would support this individual zero points?
- I haven't checked set_output_scales. It doesn't work for Matmul?

Thanks!

**Comment by dzarukin** [comment]
> Do you have any plan to support individual zero point set for each index soon? It's an important feature for us.

Just for clarification purposes - by "for each index" you mean like per channel support with `mask = 2` or literally do something like (A[m][k] - ZP[m][k]) * B[k][n]? If the latter, not sure we considered such use case. If a first one, that's a good question and I should clarify it with the team.

> Is it only MatMul? Then, Convolution and Inner product would support this individual zero points?

Convolutions support zero points (starting from v1.7) and they can do both a single ZP and per channel ZP (mask = 2, only dynamic quantization, no static one).

Inner Product support won't be extended to support zero points since matmul has it and they have nearly same internal gemm dispatching, meaning that there's no sense in extending Inner Product since they will have same technical issues with providing reasonable performance.

> I haven't checked set_output_scales. It doesn't work for Matmul?

Matmul has output scale support, both masks: 0 and 2, both modes: static and dynamic.

Thanks.

**Comment by affranchi** [comment]
Thank you for the information. It's really helpful to understand current quantization process. I have some follow-up questions.

> Just for clarification purposes - by "for each index" you mean like per channel support with `mask = 2` or literally do something like (A[m][k] - ZP[m][k]) * B[k][n]? If the latter, not sure we considered such use case. If a first one, that's a good question and I should clarify it with the team.

Yes, I meant the first case. Hopefully, it can be supported soon.

> Convolutions support zero points (starting from v1.7) and they can do both a single ZP and per channel ZP (mask = 2, only dynamic quantization, no static one).

As far as I understand, mask 2 means that the second right-most dimension. From NCHW, does mask 2 mean 'H' dim? I think that Per-channel means "C" dimension. If I misunderstood something here, please, let me know.

> The wildcard value for zero points is DNNL_RUNTIME_S32_VAL. During the execution stage, the corresponding memory object must be passed as an argument with its index set to (DNNL_ARG_ATTR_ZERO_POINTS | DNNL_ARG_${MEMORY_INDEX}). Possible ${MEMORY_INDEX} values are DNNL_ARG_SRC and DNNL_ARG_DST.

From this statement on the Convolution document for oneDNN, seems dynamic quantization supports only SRC and DST. Does your team have a plan to support zero point for weight tensor? ONNX (one of the models we are supporting) supports the weight tensor zero point. (https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvInteger)

Thanks!

**Comment by dzarukin** [comment]
> Yes, I meant the first case. Hopefully, it can be supported soon.

I've created a couple stories for our Team to enable and optimize the mask=2 zero point case in matmul primitive. 

> As far as I understand, mask 2 means that the second right-most dimension. From NCHW, does mask 2 mean 'H' dim? I think that Per-channel means "C" dimension. If I misunderstood something here, please, let me know.

Since number of dimensions expand left to right, mask represents left-most dimensions. It means that mask 2 is applied over dim[1] which is channel dimension most of times.

> From this statement on the Convolution document for oneDNN, seems dynamic quantization supports only SRC and DST. Does your team have a plan to support zero point for weight tensor? ONNX (one of the models we are supporting) supports the weight tensor zero point. (https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvInteger)

Yeah, oneDNN convolution does not support WEI zero points yet. Could you describe, please, in more details when does such need in weights zero point happen? Which models utilize this feature? And what is the priority for ONNX to have such support in oneDNN?

Thanks.

**Comment by affranchi** [comment]
>Yeah, oneDNN convolution does not support WEI zero points yet. Could you describe, please, in more details when does such need in weights zero point happen? Which models utilize this feature? And what is the priority for ONNX to have such support in oneDNN?

We don't have a specific customer yet. But we have some  customers waiting for Convolution quantization and basically our inference engine is using ONNX so would be nice if oneDNN can support this weight zero point as ONNX does. We are bypassing this weight quantization currently. It's not high priority compared to MatMul per-row zero point support.

I have enough information regarding asymmetric quantization.
Thank you so much for all your info and responses.

Thanks!
