### ISSUE TITLE
Tag v1.8-rc is after v2.0?

### ISSUE THREAD

**Issue by yurivict** [oneapi-src/oneDNN#925]
These tags seem to be wrong based on their order.

Is the latest version 2.0 or 1.8-rc?

**Comment by dzarukin** [comment]
Hi @yurivict, thanks for the question.
Release branches are not linear for oneDNN. v2.0 is based on top of v1.7 + DPCPP support and has some backward incompatibilities with version v1.
v1.8 is a continuation of v1 branch (no DPCPP support), and since it was published later that v2.0, its position is after v2.0.
Hope it helps. Thanks.

**Comment by yurivict** [comment]
What is the latest version then?

**Comment by vpirogov** [comment]
v2.0 is "the latest and greatest"
