### ISSUE TITLE
Does Softmax support NHWC format with channel axis (i.e. 3)

### ISSUE THREAD

**Issue by avinashcpandey** [oneapi-src/oneDNN#928]
I am trying to use Softmax from MKLDNN 1.3. Input format is NHWC(acdb) and accordingly I am creating the memory for src and dest, using 3 as axis which is channel.
I see my results are not matching.

I see there is no mention of acbd with axis 3 as optmized and non optimized format in Performance Tips section
https://oneapi-src.github.io/oneDNN/dev_guide_softmax.html

Is that not supported?

**Comment by dzarukin** [comment]
Hi @avinashcpandey, thanks for the question.

Unfortunately, there is a little trap with logical and physical memory layouts.
Softmax axis is attached to logical dimensions which always go in a specific order. For softmax it would be N, C, H, W. It means that in your example `W` will be used to as a softmax axis. To make it run over channels, softmax axis should be changed to `1`. Physical memory layout is mostly about blocking descriptor and strides in particular. Using NHWC format should lead to optimized performance since `C` will be dense in memory.

In the given example what happened is softmax was used along axis `W` and it had strides in memory since `W` is followed by `C`. In such scenario the library doesn't have an optimized version and should run reference kernel.

Hope it helps. Thank you.

**Comment by avinashcpandey** [comment]
Thanks @dzarukin for the prompt reply.
With my uses case(NHWC with axis=3) I see below log. 
mkldnn_primitive_execute cpu,softmax,ref:any,forward_inference,data_f32::blocked:acdb:f0 diff_undef::undef::f0,,alg:softmax axis:3,8x16x384x384, 42.657ms
However, the o/p what I get from this is not matching with my reference(TF vanilla softmax with NHWC with axis=3) o/p.

Here is my pseudocode, Let me know if I am missing something here.
//src_dims and output_dims are in NHWC format
//in_arr and output_array are raw buffer pointers

		int axis = 3;
		// Create softmax memory for src, dst,
        using tag = memory::format_tag;
        using dt = memory::data_type;
        mkldnn::memory src_memory = memory({{src_dims}, dt::f32, tag::nhwc},
        eng, in_arr);
        mkldnn::memory dst_memory = memory({{output_dims}, dt::f32, tag::nhwc},
        eng, output_array);

        // Create memory descriptors for src and dst
        memory::desc src_md = memory::desc({src_dims}, dt::f32, tag::nhwc);
        memory::desc dst_md = memory::desc({output_dims}, dt::f32, tag::nhwc);

        // Create forward and primitive descriptor for softmax op
        softmax_forward::desc softmax_fwd_desc = softmax_forward::desc(
                    prop_kind::forward_inference, src_md, axis);
        softmax_forward::primitive_desc softmax_fwd_pd =
            softmax_forward::primitive_desc(softmax_fwd_desc, eng);

        // Finally creating the "softmax op" using the primitive descriptor, src
        // and dst
        auto softmax_fwd = softmax_forward(softmax_fwd_pd);
        net.push_back(softmax_fwd);
        net_args.push_back({{MKLDNN_ARG_SRC, src_memory},
            {MKLDNN_ARG_DST, dst_memory}
        });
        assert(net.size() == net_args.size() && "something is missing");
        for (size_t i = 0; i < net.size(); ++i) {
            net.at(i).execute(s, net_args.at(i));
        }
        s.wait();

**Comment by dzarukin** [comment]
@avinashcpandey, AFAIK, TF uses the following scheme: use logical dimension in oneDNN as N,H,W,C but use nchw format. This way it preserves NHWC physical memory layout specified by logical dimensions. In such scheme axis indeed should be equal to `3` to reflect channels dimension.

Either way from these two should lead to the same result:
1) {{N,C,H,W}, data_type::f32, format_tag::nhwc}; // for axis = 1;
2) {{N,H,W,C}, data_type::f32, format_tag::nchw}; // for axis = 3;

Please let me know if changing tag to `nchw` solved an issue. Thanks.

**Comment by avinashcpandey** [comment]
Thanks @dzarukin. 
Its working with #2.
