### ISSUE TITLE
Is f16 supported in Convolution primitive?

### ISSUE THREAD

**Issue by xhuan28** [oneapi-src/oneDNN#937]
According to the oneDNN [guide](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html), it seems f16 is supported. However, when I use f16 as the data type of input, weights and bias. There is a runtime error: "could not create a primitive descriptor iterator". I also can't find the implementation with f16 in the source code of convolution primitive(v1.7). Is the developer guide out-of-date?

**Comment by dzarukin** [comment]
Hi @xhuan28, thank you for the question.

According to [this article](https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html) at hardware limitation section, fp16 support is only available for GPU engines.

Based on quote:
> I also can't find the implementation with f16 in the source

I make an assumption your are checking CPU codes, not GPU ones. In order to utilize the power of fp16, one needs to build the library with GPU support and run primitives on GPU engine. Thanks.

**Comment by vpirogov** [comment]
You can find more information about data types support in [oneDNN User Guide](https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html).

**Comment by xhuan28** [comment]
Thanks for your answer. It solves my question.

**Comment by feixuedudiao** [comment]
> Thanks for your answer. It solves my question.
@xhuan28 how you solves the question that the fp16 can use for cpu. thanks
