### ISSUE TITLE
OneDNN performance difference with various DNNL_CPU_RUNTIME (OMP, Threadpool and TBB)

### ISSUE THREAD

**Issue by avinashcpandey** [oneapi-src/oneDNN#980]
Hi,
Does OneDNN (with tensorflow) recommends any specific thread runtime for best performance on X86 CPU? 
I see CNN model execution time is dominated by convolution (OneDNN has optimal kernel for those), However NLP models are dominated by MatrixMultiplication (control goes to MKL for that). How thread runtime is making a difference in both the cases assuming underlying platform is CSL.   
I see below list that support is there for few, want to know the best setting(for CNN and NLP) which gives the max perf on CSL. 
https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html

Thanks
Avinash

**Comment by vpirogov** [comment]
@avinashcpandey,

Recent versions of Tensorflow are using oneDNN implementation for both convolutions and matmuls, so the same considerations for threading should apply to both convolutional and NLP models. Tensorflow supports two options for oneDNN threading:
* OpenMP, which is default in Tensorflow build with oneDNN
* TF threadpool, which is available since TF v2.3
I don't think you will be able to build TF with TBB out of the box.

The choice of threading runtime should primarily be defined by your deployment model.

OpenMP threading works best for cases when application has full ownership of compute resources: threads are bound to cores and no competing workloads run in the system. You may also need to set a number of [OpenMP knobs for optimal performance](https://software.intel.com/content/www/us/en/develop/articles/guide-to-tensorflow-runtime-optimizations-for-cpu.html). 

TF Threadpool allows oneDNN to submit work to the same threads as TF native operations and respect TF threading control knobs. This configuration may work better for complex deployment scenarios when multiple applications are competing for compute resources or for models that are not dominated by compute operations.

Hope this helps!

**Comment by avinashcpandey** [comment]
Thanks @vpirogov for the detailed info.

For convolution kernels mkldnn have its own implementation, so it can be used with OpenMP or TF threadpool.  Can you point me to the code where its implemented in generic way to take either of the path(OpenMP and ThreadPool)? 

For MatMul control goes to MKL, which I think is tightly coupled with OpenMP, correct me if I am wrong here. In that case TF threadpool can't be used for MatMul(SGEMM operation) right?  
 
-Avinash

**Comment by vpirogov** [comment]
Parallel implementations of all functions in oneDNN rely on functions like [parallel_nd](https://github.com/oneapi-src/oneDNN/blob/7bd73fb5297425e3d38a80a49559f55fdbad2d8c/src/common/dnnl_thread_parallel_nd.hpp#L22), that are implemented for OpenMP, TBB, or abstract threadpool. I would suggest to review [convolution reference code](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_convolution.cpp#L238) as an example.

oneDNN has SGEMM implementation exposed via [`dnnl_sgemm`](https://oneapi-src.github.io/oneDNN/group__dnnl__api__blas.html#ga75ee119765bdac249200fda42c0617f8) API and other functions relying on matrix-matrix multiplication like `matmul` or `inner product`. Recent versions of Tensorflow (at least v2.3 and later) rely on this implementation. So at least with TF v2.3 you should be able to run oneDNN convolutions and matmuls with TF threadpool.

If you have an older version of Tensorflow that uses Intel MKL then it's indeed tightly coupled with OpenMP. You can see whether your code has any Intel MKL calls by running it with environment variable `MKL_VERBOSE=1`.

**Comment by louie-tsai** [comment]
@avinashcpandey 
For getting the best performance on TF among NLP and CNN, you could also refer to below Tutorials for OMP settings.
The current tutorials only cover OpenMP runtime.
NLP : Bert
https://github.com/IntelAI/models/blob/master/docs/language_modeling/tensorflow/InferenceTutorial.md
CNN: Resnet50
https://github.com/IntelAI/models/blob/master/docs/image_recognition/tensorflow/Tutorial.md
Wish it may help.

**Comment by avinashcpandey** [comment]
Thanks @vpirogov @louie-tsai for the information.
@vpirogov I had look into dnnl_sgemm API and see with TF 2.3 control goes to dnnl_sgemm instead of mkl_sgemm. Thanks for that.

Two questions:
1. I want to configure the application(with TF ) in a way that, use different threads for TF and dnnl_sgemm. So, How to control the no. of threads in dnnl_sgemm during its execution? any API is available for that which take no. of threads as one parameter?

2. If I am using older CPUs which has different cache configs, then Can I play with some tunable parameters(like L1,L2,L3 cache sizes, blocking factor during packing etc.)? I see lots of hard coded values in files present in src/cpu/gemm

Thanks,
Avinash

**Comment by vpirogov** [comment]
oneDNN relies on the same thread controls as Tensorflow when it's using TF Threadpool. There are no other controls available, so the only option you have is to patch the [threadpool implementation](https://github.com/oneapi-src/oneDNN/blob/7bd73fb5297425e3d38a80a49559f55fdbad2d8c/src/common/dnnl_thread.hpp#L91). The same applies for tunable parameters in `dnnl_sgemm`.
